// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: eraftpb.proto

package eraftpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_EntryNormal       EntryType = 0
	EntryType_EntryConfChange   EntryType = 1
	EntryType_EntryConfChangeV2 EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "EntryNormal",
		1: "EntryConfChange",
		2: "EntryConfChangeV2",
	}
	EntryType_value = map[string]int32{
		"EntryNormal":       0,
		"EntryConfChange":   1,
		"EntryConfChangeV2": 2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_eraftpb_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_eraftpb_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MsgHup                    MessageType = 0
	MessageType_MsgBeat                   MessageType = 1
	MessageType_MsgPropose                MessageType = 2
	MessageType_MsgAppend                 MessageType = 3
	MessageType_MsgAppendResponse         MessageType = 4
	MessageType_MsgRequestVote            MessageType = 5
	MessageType_MsgRequestVoteResponse    MessageType = 6
	MessageType_MsgSnapshot               MessageType = 7
	MessageType_MsgHeartbeat              MessageType = 8
	MessageType_MsgHeartbeatResponse      MessageType = 9
	MessageType_MsgUnreachable            MessageType = 10
	MessageType_MsgSnapStatus             MessageType = 11
	MessageType_MsgCheckQuorum            MessageType = 12
	MessageType_MsgTransferLeader         MessageType = 13
	MessageType_MsgTimeoutNow             MessageType = 14
	MessageType_MsgReadIndex              MessageType = 15
	MessageType_MsgReadIndexResp          MessageType = 16
	MessageType_MsgRequestPreVote         MessageType = 17
	MessageType_MsgRequestPreVoteResponse MessageType = 18
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MsgHup",
		1:  "MsgBeat",
		2:  "MsgPropose",
		3:  "MsgAppend",
		4:  "MsgAppendResponse",
		5:  "MsgRequestVote",
		6:  "MsgRequestVoteResponse",
		7:  "MsgSnapshot",
		8:  "MsgHeartbeat",
		9:  "MsgHeartbeatResponse",
		10: "MsgUnreachable",
		11: "MsgSnapStatus",
		12: "MsgCheckQuorum",
		13: "MsgTransferLeader",
		14: "MsgTimeoutNow",
		15: "MsgReadIndex",
		16: "MsgReadIndexResp",
		17: "MsgRequestPreVote",
		18: "MsgRequestPreVoteResponse",
	}
	MessageType_value = map[string]int32{
		"MsgHup":                    0,
		"MsgBeat":                   1,
		"MsgPropose":                2,
		"MsgAppend":                 3,
		"MsgAppendResponse":         4,
		"MsgRequestVote":            5,
		"MsgRequestVoteResponse":    6,
		"MsgSnapshot":               7,
		"MsgHeartbeat":              8,
		"MsgHeartbeatResponse":      9,
		"MsgUnreachable":            10,
		"MsgSnapStatus":             11,
		"MsgCheckQuorum":            12,
		"MsgTransferLeader":         13,
		"MsgTimeoutNow":             14,
		"MsgReadIndex":              15,
		"MsgReadIndexResp":          16,
		"MsgRequestPreVote":         17,
		"MsgRequestPreVoteResponse": 18,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_eraftpb_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_eraftpb_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{1}
}

type ConfChangeTransition int32

const (
	// Automatically use the simple protocol if possible, otherwise fall back
	// to ConfChangeType::Implicit. Most applications will want to use this.
	ConfChangeTransition_Auto ConfChangeTransition = 0
	// Use joint consensus unconditionally, and transition out of them
	// automatically (by proposing a zero configuration change).
	//
	// This option is suitable for applications that want to minimize the time
	// spent in the joint configuration and do not store the joint configuration
	// in the state machine (outside of InitialState).
	ConfChangeTransition_Implicit ConfChangeTransition = 1
	// Use joint consensus and remain in the joint configuration until the
	// application proposes a no-op configuration change. This is suitable for
	// applications that want to explicitly control the transitions, for example
	// to use a custom payload (via the Context field).
	ConfChangeTransition_Explicit ConfChangeTransition = 2
)

// Enum value maps for ConfChangeTransition.
var (
	ConfChangeTransition_name = map[int32]string{
		0: "Auto",
		1: "Implicit",
		2: "Explicit",
	}
	ConfChangeTransition_value = map[string]int32{
		"Auto":     0,
		"Implicit": 1,
		"Explicit": 2,
	}
)

func (x ConfChangeTransition) Enum() *ConfChangeTransition {
	p := new(ConfChangeTransition)
	*p = x
	return p
}

func (x ConfChangeTransition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfChangeTransition) Descriptor() protoreflect.EnumDescriptor {
	return file_eraftpb_proto_enumTypes[2].Descriptor()
}

func (ConfChangeTransition) Type() protoreflect.EnumType {
	return &file_eraftpb_proto_enumTypes[2]
}

func (x ConfChangeTransition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfChangeTransition.Descriptor instead.
func (ConfChangeTransition) EnumDescriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{2}
}

type ConfChangeType int32

const (
	ConfChangeType_AddNode        ConfChangeType = 0
	ConfChangeType_RemoveNode     ConfChangeType = 1
	ConfChangeType_AddLearnerNode ConfChangeType = 2
)

// Enum value maps for ConfChangeType.
var (
	ConfChangeType_name = map[int32]string{
		0: "AddNode",
		1: "RemoveNode",
		2: "AddLearnerNode",
	}
	ConfChangeType_value = map[string]int32{
		"AddNode":        0,
		"RemoveNode":     1,
		"AddLearnerNode": 2,
	}
)

func (x ConfChangeType) Enum() *ConfChangeType {
	p := new(ConfChangeType)
	*p = x
	return p
}

func (x ConfChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_eraftpb_proto_enumTypes[3].Descriptor()
}

func (ConfChangeType) Type() protoreflect.EnumType {
	return &file_eraftpb_proto_enumTypes[3]
}

func (x ConfChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfChangeType.Descriptor instead.
func (ConfChangeType) EnumDescriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{3}
}

// The entry is a type of change that needs to be applied. It contains two data fields.
// While the fields are built into the model; their usage is determined by the entry_type.
//
// For normal entries, the data field should contain the data change that should be applied.
// The context field can be used for any contextual data that might be relevant to the
// application of the data.
//
// For configuration changes, the data will contain the ConfChange message and the
// context will provide anything needed to assist the configuration change. The context
// if for the user to set and use in this case.
type Entry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EntryType EntryType              `protobuf:"varint,1,opt,name=entry_type,json=entryType,proto3,enum=eraftpb.EntryType" json:"entry_type,omitempty"`
	Term      uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Index     uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Data      []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Context   []byte                 `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	// Deprecated! It is kept for backward compatibility.
	// TODO: remove it in the next major release.
	SyncLog       bool `protobuf:"varint,5,opt,name=sync_log,json=syncLog,proto3" json:"sync_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_eraftpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_EntryNormal
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entry) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Entry) GetSyncLog() bool {
	if x != nil {
		return x.SyncLog
	}
	return false
}

type SnapshotMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current `ConfState`.
	ConfState *ConfState `protobuf:"bytes,1,opt,name=conf_state,json=confState,proto3" json:"conf_state,omitempty"`
	// The applied index.
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// The term of the applied index.
	Term          uint64 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_eraftpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotMetadata) GetConfState() *ConfState {
	if x != nil {
		return x.ConfState
	}
	return nil
}

func (x *SnapshotMetadata) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotMetadata) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_eraftpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Message struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MsgType            MessageType            `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=eraftpb.MessageType" json:"msg_type,omitempty"`
	To                 uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	From               uint64                 `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Term               uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LogTerm            uint64                 `protobuf:"varint,5,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"`
	Index              uint64                 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	Entries            []*Entry               `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	Commit             uint64                 `protobuf:"varint,8,opt,name=commit,proto3" json:"commit,omitempty"`
	Snapshot           *Snapshot              `protobuf:"bytes,9,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	RequestSnapshot    uint64                 `protobuf:"varint,13,opt,name=request_snapshot,json=requestSnapshot,proto3" json:"request_snapshot,omitempty"`
	Reject             bool                   `protobuf:"varint,10,opt,name=reject,proto3" json:"reject,omitempty"`
	RejectHint         uint64                 `protobuf:"varint,11,opt,name=reject_hint,json=rejectHint,proto3" json:"reject_hint,omitempty"`
	Context            []byte                 `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	DeprecatedPriority uint64                 `protobuf:"varint,14,opt,name=deprecated_priority,json=deprecatedPriority,proto3" json:"deprecated_priority,omitempty"`
	// If this new field is not set, then use the above old field; otherwise
	// use the new field. When broadcasting request vote, both fields are
	// set if the priority is larger than 0. This change is not a fully
	// compatible change, but it makes minimal impact that only new priority
	// is not recognized by the old nodes during rolling update.
	Priority      int64 `protobuf:"varint,15,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_eraftpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MsgHup
}

func (x *Message) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *Message) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Message) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

func (x *Message) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Message) GetRequestSnapshot() uint64 {
	if x != nil {
		return x.RequestSnapshot
	}
	return 0
}

func (x *Message) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *Message) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

func (x *Message) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Message) GetDeprecatedPriority() uint64 {
	if x != nil {
		return x.DeprecatedPriority
	}
	return 0
}

func (x *Message) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type HardState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Vote          uint64                 `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	Commit        uint64                 `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardState) Reset() {
	*x = HardState{}
	mi := &file_eraftpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardState) ProtoMessage() {}

func (x *HardState) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardState.ProtoReflect.Descriptor instead.
func (*HardState) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{4}
}

func (x *HardState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HardState) GetVote() uint64 {
	if x != nil {
		return x.Vote
	}
	return 0
}

func (x *HardState) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

type ConfState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Voters   []uint64               `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	Learners []uint64               `protobuf:"varint,2,rep,packed,name=learners,proto3" json:"learners,omitempty"`
	// The voters in the outgoing config. If not empty the node is in joint consensus.
	VotersOutgoing []uint64 `protobuf:"varint,3,rep,packed,name=voters_outgoing,json=votersOutgoing,proto3" json:"voters_outgoing,omitempty"`
	// The nodes that will become learners when the outgoing config is removed.
	// These nodes are necessarily currently in nodes_joint (or they would have
	// been added to the incoming config right away).
	LearnersNext []uint64 `protobuf:"varint,4,rep,packed,name=learners_next,json=learnersNext,proto3" json:"learners_next,omitempty"`
	// If set, the config is joint and Raft will automatically transition into
	// the final config (i.e. remove the outgoing config) when this is safe.
	AutoLeave     bool `protobuf:"varint,5,opt,name=auto_leave,json=autoLeave,proto3" json:"auto_leave,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfState) Reset() {
	*x = ConfState{}
	mi := &file_eraftpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfState) ProtoMessage() {}

func (x *ConfState) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfState.ProtoReflect.Descriptor instead.
func (*ConfState) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{5}
}

func (x *ConfState) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *ConfState) GetLearners() []uint64 {
	if x != nil {
		return x.Learners
	}
	return nil
}

func (x *ConfState) GetVotersOutgoing() []uint64 {
	if x != nil {
		return x.VotersOutgoing
	}
	return nil
}

func (x *ConfState) GetLearnersNext() []uint64 {
	if x != nil {
		return x.LearnersNext
	}
	return nil
}

func (x *ConfState) GetAutoLeave() bool {
	if x != nil {
		return x.AutoLeave
	}
	return false
}

type ConfChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ConfChangeType         `protobuf:"varint,2,opt,name=change_type,json=changeType,proto3,enum=eraftpb.ConfChangeType" json:"change_type,omitempty"`
	NodeId        uint64                 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Context       []byte                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfChange) Reset() {
	*x = ConfChange{}
	mi := &file_eraftpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfChange) ProtoMessage() {}

func (x *ConfChange) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfChange.ProtoReflect.Descriptor instead.
func (*ConfChange) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{6}
}

func (x *ConfChange) GetChangeType() ConfChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConfChangeType_AddNode
}

func (x *ConfChange) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ConfChange) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConfChange) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ConfChangeSingle is an individual configuration change operation. Multiple
// such operations can be carried out atomically via a ConfChangeV2.
type ConfChangeSingle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ConfChangeType         `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=eraftpb.ConfChangeType" json:"change_type,omitempty"`
	NodeId        uint64                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfChangeSingle) Reset() {
	*x = ConfChangeSingle{}
	mi := &file_eraftpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfChangeSingle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfChangeSingle) ProtoMessage() {}

func (x *ConfChangeSingle) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfChangeSingle.ProtoReflect.Descriptor instead.
func (*ConfChangeSingle) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{7}
}

func (x *ConfChangeSingle) GetChangeType() ConfChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConfChangeType_AddNode
}

func (x *ConfChangeSingle) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// ConfChangeV2 messages initiate configuration changes. They support both the
// simple "one at a time" membership change protocol and full Joint Consensus
// allowing for arbitrary changes in membership.
//
// The supplied context is treated as an opaque payload and can be used to
// attach an action on the state machine to the application of the config change
// proposal. Note that contrary to Joint Consensus as outlined in the Raft
// paper[1], configuration changes become active when they are *applied* to the
// state machine (not when they are appended to the log).
//
// The simple protocol can be used whenever only a single change is made.
//
// Non-simple changes require the use of Joint Consensus, for which two
// configuration changes are run. The first configuration change specifies the
// desired changes and transitions the Raft group into the joint configuration,
// in which quorum requires a majority of both the pre-changes and post-changes
// configuration. Joint Consensus avoids entering fragile intermediate
// configurations that could compromise survivability. For example, without the
// use of Joint Consensus and running across three availability zones with a
// replication factor of three, it is not possible to replace a voter without
// entering an intermediate configuration that does not survive the outage of
// one availability zone.
//
// The provided ConfChangeTransition specifies how (and whether) Joint Consensus
// is used, and assigns the task of leaving the joint configuration either to
// Raft or the application. Leaving the joint configuration is accomplished by
// proposing a ConfChangeV2 with only and optionally the Context field
// populated.
//
// For details on Raft membership changes, see:
//
// [1]: https://github.com/ongardie/dissertation/blob/master/online-trim.pdf
type ConfChangeV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transition    ConfChangeTransition   `protobuf:"varint,1,opt,name=transition,proto3,enum=eraftpb.ConfChangeTransition" json:"transition,omitempty"`
	Changes       []*ConfChangeSingle    `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	Context       []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfChangeV2) Reset() {
	*x = ConfChangeV2{}
	mi := &file_eraftpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfChangeV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfChangeV2) ProtoMessage() {}

func (x *ConfChangeV2) ProtoReflect() protoreflect.Message {
	mi := &file_eraftpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfChangeV2.ProtoReflect.Descriptor instead.
func (*ConfChangeV2) Descriptor() ([]byte, []int) {
	return file_eraftpb_proto_rawDescGZIP(), []int{8}
}

func (x *ConfChangeV2) GetTransition() ConfChangeTransition {
	if x != nil {
		return x.Transition
	}
	return ConfChangeTransition_Auto
}

func (x *ConfChangeV2) GetChanges() []*ConfChangeSingle {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ConfChangeV2) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_eraftpb_proto protoreflect.FileDescriptor

const file_eraftpb_proto_rawDesc = "" +
	"\n" +
	"\reraftpb.proto\x12\aeraftpb\"\xad\x01\n" +
	"\x05Entry\x121\n" +
	"\n" +
	"entry_type\x18\x01 \x01(\x0e2\x12.eraftpb.EntryTypeR\tentryType\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x18\n" +
	"\acontext\x18\x06 \x01(\fR\acontext\x12\x19\n" +
	"\bsync_log\x18\x05 \x01(\bR\asyncLog\"o\n" +
	"\x10SnapshotMetadata\x121\n" +
	"\n" +
	"conf_state\x18\x01 \x01(\v2\x12.eraftpb.ConfStateR\tconfState\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\"U\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.eraftpb.SnapshotMetadataR\bmetadata\"\xdf\x03\n" +
	"\aMessage\x12/\n" +
	"\bmsg_type\x18\x01 \x01(\x0e2\x14.eraftpb.MessageTypeR\amsgType\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x04R\x04from\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x19\n" +
	"\blog_term\x18\x05 \x01(\x04R\alogTerm\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x04R\x05index\x12(\n" +
	"\aentries\x18\a \x03(\v2\x0e.eraftpb.EntryR\aentries\x12\x16\n" +
	"\x06commit\x18\b \x01(\x04R\x06commit\x12-\n" +
	"\bsnapshot\x18\t \x01(\v2\x11.eraftpb.SnapshotR\bsnapshot\x12)\n" +
	"\x10request_snapshot\x18\r \x01(\x04R\x0frequestSnapshot\x12\x16\n" +
	"\x06reject\x18\n" +
	" \x01(\bR\x06reject\x12\x1f\n" +
	"\vreject_hint\x18\v \x01(\x04R\n" +
	"rejectHint\x12\x18\n" +
	"\acontext\x18\f \x01(\fR\acontext\x12/\n" +
	"\x13deprecated_priority\x18\x0e \x01(\x04R\x12deprecatedPriority\x12\x1a\n" +
	"\bpriority\x18\x0f \x01(\x03R\bpriority\"K\n" +
	"\tHardState\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x12\n" +
	"\x04vote\x18\x02 \x01(\x04R\x04vote\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\x04R\x06commit\"\xac\x01\n" +
	"\tConfState\x12\x16\n" +
	"\x06voters\x18\x01 \x03(\x04R\x06voters\x12\x1a\n" +
	"\blearners\x18\x02 \x03(\x04R\blearners\x12'\n" +
	"\x0fvoters_outgoing\x18\x03 \x03(\x04R\x0evotersOutgoing\x12#\n" +
	"\rlearners_next\x18\x04 \x03(\x04R\flearnersNext\x12\x1d\n" +
	"\n" +
	"auto_leave\x18\x05 \x01(\bR\tautoLeave\"\x89\x01\n" +
	"\n" +
	"ConfChange\x128\n" +
	"\vchange_type\x18\x02 \x01(\x0e2\x17.eraftpb.ConfChangeTypeR\n" +
	"changeType\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x04R\x06nodeId\x12\x18\n" +
	"\acontext\x18\x04 \x01(\fR\acontext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"e\n" +
	"\x10ConfChangeSingle\x128\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x17.eraftpb.ConfChangeTypeR\n" +
	"changeType\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x04R\x06nodeId\"\x9c\x01\n" +
	"\fConfChangeV2\x12=\n" +
	"\n" +
	"transition\x18\x01 \x01(\x0e2\x1d.eraftpb.ConfChangeTransitionR\n" +
	"transition\x123\n" +
	"\achanges\x18\x02 \x03(\v2\x19.eraftpb.ConfChangeSingleR\achanges\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext*H\n" +
	"\tEntryType\x12\x0f\n" +
	"\vEntryNormal\x10\x00\x12\x13\n" +
	"\x0fEntryConfChange\x10\x01\x12\x15\n" +
	"\x11EntryConfChangeV2\x10\x02*\x8c\x03\n" +
	"\vMessageType\x12\n" +
	"\n" +
	"\x06MsgHup\x10\x00\x12\v\n" +
	"\aMsgBeat\x10\x01\x12\x0e\n" +
	"\n" +
	"MsgPropose\x10\x02\x12\r\n" +
	"\tMsgAppend\x10\x03\x12\x15\n" +
	"\x11MsgAppendResponse\x10\x04\x12\x12\n" +
	"\x0eMsgRequestVote\x10\x05\x12\x1a\n" +
	"\x16MsgRequestVoteResponse\x10\x06\x12\x0f\n" +
	"\vMsgSnapshot\x10\a\x12\x10\n" +
	"\fMsgHeartbeat\x10\b\x12\x18\n" +
	"\x14MsgHeartbeatResponse\x10\t\x12\x12\n" +
	"\x0eMsgUnreachable\x10\n" +
	"\x12\x11\n" +
	"\rMsgSnapStatus\x10\v\x12\x12\n" +
	"\x0eMsgCheckQuorum\x10\f\x12\x15\n" +
	"\x11MsgTransferLeader\x10\r\x12\x11\n" +
	"\rMsgTimeoutNow\x10\x0e\x12\x10\n" +
	"\fMsgReadIndex\x10\x0f\x12\x14\n" +
	"\x10MsgReadIndexResp\x10\x10\x12\x15\n" +
	"\x11MsgRequestPreVote\x10\x11\x12\x1d\n" +
	"\x19MsgRequestPreVoteResponse\x10\x12*<\n" +
	"\x14ConfChangeTransition\x12\b\n" +
	"\x04Auto\x10\x00\x12\f\n" +
	"\bImplicit\x10\x01\x12\f\n" +
	"\bExplicit\x10\x02*A\n" +
	"\x0eConfChangeType\x12\v\n" +
	"\aAddNode\x10\x00\x12\x0e\n" +
	"\n" +
	"RemoveNode\x10\x01\x12\x12\n" +
	"\x0eAddLearnerNode\x10\x02b\x06proto3"

var (
	file_eraftpb_proto_rawDescOnce sync.Once
	file_eraftpb_proto_rawDescData []byte
)

func file_eraftpb_proto_rawDescGZIP() []byte {
	file_eraftpb_proto_rawDescOnce.Do(func() {
		file_eraftpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eraftpb_proto_rawDesc), len(file_eraftpb_proto_rawDesc)))
	})
	return file_eraftpb_proto_rawDescData
}

var file_eraftpb_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_eraftpb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_eraftpb_proto_goTypes = []any{
	(EntryType)(0),            // 0: eraftpb.EntryType
	(MessageType)(0),          // 1: eraftpb.MessageType
	(ConfChangeTransition)(0), // 2: eraftpb.ConfChangeTransition
	(ConfChangeType)(0),       // 3: eraftpb.ConfChangeType
	(*Entry)(nil),             // 4: eraftpb.Entry
	(*SnapshotMetadata)(nil),  // 5: eraftpb.SnapshotMetadata
	(*Snapshot)(nil),          // 6: eraftpb.Snapshot
	(*Message)(nil),           // 7: eraftpb.Message
	(*HardState)(nil),         // 8: eraftpb.HardState
	(*ConfState)(nil),         // 9: eraftpb.ConfState
	(*ConfChange)(nil),        // 10: eraftpb.ConfChange
	(*ConfChangeSingle)(nil),  // 11: eraftpb.ConfChangeSingle
	(*ConfChangeV2)(nil),      // 12: eraftpb.ConfChangeV2
}
var file_eraftpb_proto_depIdxs = []int32{
	0,  // 0: eraftpb.Entry.entry_type:type_name -> eraftpb.EntryType
	9,  // 1: eraftpb.SnapshotMetadata.conf_state:type_name -> eraftpb.ConfState
	5,  // 2: eraftpb.Snapshot.metadata:type_name -> eraftpb.SnapshotMetadata
	1,  // 3: eraftpb.Message.msg_type:type_name -> eraftpb.MessageType
	4,  // 4: eraftpb.Message.entries:type_name -> eraftpb.Entry
	6,  // 5: eraftpb.Message.snapshot:type_name -> eraftpb.Snapshot
	3,  // 6: eraftpb.ConfChange.change_type:type_name -> eraftpb.ConfChangeType
	3,  // 7: eraftpb.ConfChangeSingle.change_type:type_name -> eraftpb.ConfChangeType
	2,  // 8: eraftpb.ConfChangeV2.transition:type_name -> eraftpb.ConfChangeTransition
	11, // 9: eraftpb.ConfChangeV2.changes:type_name -> eraftpb.ConfChangeSingle
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_eraftpb_proto_init() }
func file_eraftpb_proto_init() {
	if File_eraftpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eraftpb_proto_rawDesc), len(file_eraftpb_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eraftpb_proto_goTypes,
		DependencyIndexes: file_eraftpb_proto_depIdxs,
		EnumInfos:         file_eraftpb_proto_enumTypes,
		MessageInfos:      file_eraftpb_proto_msgTypes,
	}.Build()
	File_eraftpb_proto = out.File
	file_eraftpb_proto_goTypes = nil
	file_eraftpb_proto_depIdxs = nil
}
