// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: resource_usage_agent.proto

package resource_usage_agent

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceUsageAgent_Report_FullMethodName = "/resource_usage_agent.ResourceUsageAgent/Report"
)

// ResourceUsageAgentClient is the client API for ResourceUsageAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ResourceUsageAgent is the service for storing resource usage records.
type ResourceUsageAgentClient interface {
	// Report the resource usage records. By default, the records with the same
	// resource group tag will be batched by minute.
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResourceUsageRecord, EmptyResponse], error)
}

type resourceUsageAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceUsageAgentClient(cc grpc.ClientConnInterface) ResourceUsageAgentClient {
	return &resourceUsageAgentClient{cc}
}

func (c *resourceUsageAgentClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ResourceUsageRecord, EmptyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceUsageAgent_ServiceDesc.Streams[0], ResourceUsageAgent_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResourceUsageRecord, EmptyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceUsageAgent_ReportClient = grpc.ClientStreamingClient[ResourceUsageRecord, EmptyResponse]

// ResourceUsageAgentServer is the server API for ResourceUsageAgent service.
// All implementations must embed UnimplementedResourceUsageAgentServer
// for forward compatibility.
//
// ResourceUsageAgent is the service for storing resource usage records.
type ResourceUsageAgentServer interface {
	// Report the resource usage records. By default, the records with the same
	// resource group tag will be batched by minute.
	Report(grpc.ClientStreamingServer[ResourceUsageRecord, EmptyResponse]) error
	mustEmbedUnimplementedResourceUsageAgentServer()
}

// UnimplementedResourceUsageAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceUsageAgentServer struct{}

func (UnimplementedResourceUsageAgentServer) Report(grpc.ClientStreamingServer[ResourceUsageRecord, EmptyResponse]) error {
	return status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedResourceUsageAgentServer) mustEmbedUnimplementedResourceUsageAgentServer() {}
func (UnimplementedResourceUsageAgentServer) testEmbeddedByValue()                            {}

// UnsafeResourceUsageAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceUsageAgentServer will
// result in compilation errors.
type UnsafeResourceUsageAgentServer interface {
	mustEmbedUnimplementedResourceUsageAgentServer()
}

func RegisterResourceUsageAgentServer(s grpc.ServiceRegistrar, srv ResourceUsageAgentServer) {
	// If the following call panics, it indicates UnimplementedResourceUsageAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceUsageAgent_ServiceDesc, srv)
}

func _ResourceUsageAgent_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ResourceUsageAgentServer).Report(&grpc.GenericServerStream[ResourceUsageRecord, EmptyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceUsageAgent_ReportServer = grpc.ClientStreamingServer[ResourceUsageRecord, EmptyResponse]

// ResourceUsageAgent_ServiceDesc is the grpc.ServiceDesc for ResourceUsageAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceUsageAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource_usage_agent.ResourceUsageAgent",
	HandlerType: (*ResourceUsageAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _ResourceUsageAgent_Report_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "resource_usage_agent.proto",
}

const (
	ResourceMeteringPubSub_Subscribe_FullMethodName = "/resource_usage_agent.ResourceMeteringPubSub/Subscribe"
)

// ResourceMeteringPubSubClient is the client API for ResourceMeteringPubSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TiKV implements ResourceMeteringPubSub service for clients to subscribe to resource metering records.
type ResourceMeteringPubSubClient interface {
	// Clients subscribe to resource metering records through this RPC, and TiKV periodically (e.g. per minute)
	// publishes resource metering records to clients via gRPC stream.
	Subscribe(ctx context.Context, in *ResourceMeteringRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceUsageRecord], error)
}

type resourceMeteringPubSubClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceMeteringPubSubClient(cc grpc.ClientConnInterface) ResourceMeteringPubSubClient {
	return &resourceMeteringPubSubClient{cc}
}

func (c *resourceMeteringPubSubClient) Subscribe(ctx context.Context, in *ResourceMeteringRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceUsageRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ResourceMeteringPubSub_ServiceDesc.Streams[0], ResourceMeteringPubSub_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResourceMeteringRequest, ResourceUsageRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceMeteringPubSub_SubscribeClient = grpc.ServerStreamingClient[ResourceUsageRecord]

// ResourceMeteringPubSubServer is the server API for ResourceMeteringPubSub service.
// All implementations must embed UnimplementedResourceMeteringPubSubServer
// for forward compatibility.
//
// TiKV implements ResourceMeteringPubSub service for clients to subscribe to resource metering records.
type ResourceMeteringPubSubServer interface {
	// Clients subscribe to resource metering records through this RPC, and TiKV periodically (e.g. per minute)
	// publishes resource metering records to clients via gRPC stream.
	Subscribe(*ResourceMeteringRequest, grpc.ServerStreamingServer[ResourceUsageRecord]) error
	mustEmbedUnimplementedResourceMeteringPubSubServer()
}

// UnimplementedResourceMeteringPubSubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceMeteringPubSubServer struct{}

func (UnimplementedResourceMeteringPubSubServer) Subscribe(*ResourceMeteringRequest, grpc.ServerStreamingServer[ResourceUsageRecord]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedResourceMeteringPubSubServer) mustEmbedUnimplementedResourceMeteringPubSubServer() {
}
func (UnimplementedResourceMeteringPubSubServer) testEmbeddedByValue() {}

// UnsafeResourceMeteringPubSubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceMeteringPubSubServer will
// result in compilation errors.
type UnsafeResourceMeteringPubSubServer interface {
	mustEmbedUnimplementedResourceMeteringPubSubServer()
}

func RegisterResourceMeteringPubSubServer(s grpc.ServiceRegistrar, srv ResourceMeteringPubSubServer) {
	// If the following call panics, it indicates UnimplementedResourceMeteringPubSubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceMeteringPubSub_ServiceDesc, srv)
}

func _ResourceMeteringPubSub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResourceMeteringRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceMeteringPubSubServer).Subscribe(m, &grpc.GenericServerStream[ResourceMeteringRequest, ResourceUsageRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ResourceMeteringPubSub_SubscribeServer = grpc.ServerStreamingServer[ResourceUsageRecord]

// ResourceMeteringPubSub_ServiceDesc is the grpc.ServiceDesc for ResourceMeteringPubSub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceMeteringPubSub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource_usage_agent.ResourceMeteringPubSub",
	HandlerType: (*ResourceMeteringPubSubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ResourceMeteringPubSub_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "resource_usage_agent.proto",
}
