// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: resource_usage_agent.proto

package resource_usage_agent

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceMeteringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMeteringRequest) Reset() {
	*x = ResourceMeteringRequest{}
	mi := &file_resource_usage_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMeteringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMeteringRequest) ProtoMessage() {}

func (x *ResourceMeteringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_usage_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMeteringRequest.ProtoReflect.Descriptor instead.
func (*ResourceMeteringRequest) Descriptor() ([]byte, []int) {
	return file_resource_usage_agent_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_resource_usage_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_usage_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_resource_usage_agent_proto_rawDescGZIP(), []int{1}
}

type ResourceUsageRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RecordOneof:
	//
	//	*ResourceUsageRecord_Record
	//	*ResourceUsageRecord_RegionRecord
	RecordOneof   isResourceUsageRecord_RecordOneof `protobuf_oneof:"record_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsageRecord) Reset() {
	*x = ResourceUsageRecord{}
	mi := &file_resource_usage_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsageRecord) ProtoMessage() {}

func (x *ResourceUsageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_resource_usage_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsageRecord.ProtoReflect.Descriptor instead.
func (*ResourceUsageRecord) Descriptor() ([]byte, []int) {
	return file_resource_usage_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUsageRecord) GetRecordOneof() isResourceUsageRecord_RecordOneof {
	if x != nil {
		return x.RecordOneof
	}
	return nil
}

func (x *ResourceUsageRecord) GetRecord() *GroupTagRecord {
	if x != nil {
		if x, ok := x.RecordOneof.(*ResourceUsageRecord_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *ResourceUsageRecord) GetRegionRecord() *RegionRecord {
	if x != nil {
		if x, ok := x.RecordOneof.(*ResourceUsageRecord_RegionRecord); ok {
			return x.RegionRecord
		}
	}
	return nil
}

type isResourceUsageRecord_RecordOneof interface {
	isResourceUsageRecord_RecordOneof()
}

type ResourceUsageRecord_Record struct {
	Record *GroupTagRecord `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type ResourceUsageRecord_RegionRecord struct {
	RegionRecord *RegionRecord `protobuf:"bytes,2,opt,name=region_record,json=regionRecord,proto3,oneof"`
}

func (*ResourceUsageRecord_Record) isResourceUsageRecord_RecordOneof() {}

func (*ResourceUsageRecord_RegionRecord) isResourceUsageRecord_RecordOneof() {}

// GroupTagRecord is a set of resource usage data grouped by resource_group_tag.
type GroupTagRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceGroupTag []byte                 `protobuf:"bytes,1,opt,name=resource_group_tag,json=resourceGroupTag,proto3" json:"resource_group_tag,omitempty"`
	Items            []*GroupTagRecordItem  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupTagRecord) Reset() {
	*x = GroupTagRecord{}
	mi := &file_resource_usage_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTagRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTagRecord) ProtoMessage() {}

func (x *GroupTagRecord) ProtoReflect() protoreflect.Message {
	mi := &file_resource_usage_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTagRecord.ProtoReflect.Descriptor instead.
func (*GroupTagRecord) Descriptor() ([]byte, []int) {
	return file_resource_usage_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GroupTagRecord) GetResourceGroupTag() []byte {
	if x != nil {
		return x.ResourceGroupTag
	}
	return nil
}

func (x *GroupTagRecord) GetItems() []*GroupTagRecordItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupTagRecordItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampSec      uint64                 `protobuf:"varint,1,opt,name=timestamp_sec,json=timestampSec,proto3" json:"timestamp_sec,omitempty"`
	CpuTimeMs         uint32                 `protobuf:"varint,2,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	ReadKeys          uint32                 `protobuf:"varint,3,opt,name=read_keys,json=readKeys,proto3" json:"read_keys,omitempty"`
	WriteKeys         uint32                 `protobuf:"varint,4,opt,name=write_keys,json=writeKeys,proto3" json:"write_keys,omitempty"`
	NetworkInBytes    uint64                 `protobuf:"varint,5,opt,name=network_in_bytes,json=networkInBytes,proto3" json:"network_in_bytes,omitempty"`
	NetworkOutBytes   uint64                 `protobuf:"varint,6,opt,name=network_out_bytes,json=networkOutBytes,proto3" json:"network_out_bytes,omitempty"`
	LogicalReadBytes  uint64                 `protobuf:"varint,7,opt,name=logical_read_bytes,json=logicalReadBytes,proto3" json:"logical_read_bytes,omitempty"`
	LogicalWriteBytes uint64                 `protobuf:"varint,8,opt,name=logical_write_bytes,json=logicalWriteBytes,proto3" json:"logical_write_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GroupTagRecordItem) Reset() {
	*x = GroupTagRecordItem{}
	mi := &file_resource_usage_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTagRecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTagRecordItem) ProtoMessage() {}

func (x *GroupTagRecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_resource_usage_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTagRecordItem.ProtoReflect.Descriptor instead.
func (*GroupTagRecordItem) Descriptor() ([]byte, []int) {
	return file_resource_usage_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GroupTagRecordItem) GetTimestampSec() uint64 {
	if x != nil {
		return x.TimestampSec
	}
	return 0
}

func (x *GroupTagRecordItem) GetCpuTimeMs() uint32 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *GroupTagRecordItem) GetReadKeys() uint32 {
	if x != nil {
		return x.ReadKeys
	}
	return 0
}

func (x *GroupTagRecordItem) GetWriteKeys() uint32 {
	if x != nil {
		return x.WriteKeys
	}
	return 0
}

func (x *GroupTagRecordItem) GetNetworkInBytes() uint64 {
	if x != nil {
		return x.NetworkInBytes
	}
	return 0
}

func (x *GroupTagRecordItem) GetNetworkOutBytes() uint64 {
	if x != nil {
		return x.NetworkOutBytes
	}
	return 0
}

func (x *GroupTagRecordItem) GetLogicalReadBytes() uint64 {
	if x != nil {
		return x.LogicalReadBytes
	}
	return 0
}

func (x *GroupTagRecordItem) GetLogicalWriteBytes() uint64 {
	if x != nil {
		return x.LogicalWriteBytes
	}
	return 0
}

// RegionRecord is a set of resource usage data grouped by region.
type RegionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Items         []*GroupTagRecordItem  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionRecord) Reset() {
	*x = RegionRecord{}
	mi := &file_resource_usage_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRecord) ProtoMessage() {}

func (x *RegionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_resource_usage_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRecord.ProtoReflect.Descriptor instead.
func (*RegionRecord) Descriptor() ([]byte, []int) {
	return file_resource_usage_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegionRecord) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RegionRecord) GetItems() []*GroupTagRecordItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_resource_usage_agent_proto protoreflect.FileDescriptor

const file_resource_usage_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aresource_usage_agent.proto\x12\x14resource_usage_agent\x1a\x0frustproto.proto\"\x19\n" +
	"\x17ResourceMeteringRequest\"\x0f\n" +
	"\rEmptyResponse\"\xb0\x01\n" +
	"\x13ResourceUsageRecord\x12>\n" +
	"\x06record\x18\x01 \x01(\v2$.resource_usage_agent.GroupTagRecordH\x00R\x06record\x12I\n" +
	"\rregion_record\x18\x02 \x01(\v2\".resource_usage_agent.RegionRecordH\x00R\fregionRecordB\x0e\n" +
	"\frecord_oneof\"~\n" +
	"\x0eGroupTagRecord\x12,\n" +
	"\x12resource_group_tag\x18\x01 \x01(\fR\x10resourceGroupTag\x12>\n" +
	"\x05items\x18\x02 \x03(\v2(.resource_usage_agent.GroupTagRecordItemR\x05items\"\xc9\x02\n" +
	"\x12GroupTagRecordItem\x12#\n" +
	"\rtimestamp_sec\x18\x01 \x01(\x04R\ftimestampSec\x12\x1e\n" +
	"\vcpu_time_ms\x18\x02 \x01(\rR\tcpuTimeMs\x12\x1b\n" +
	"\tread_keys\x18\x03 \x01(\rR\breadKeys\x12\x1d\n" +
	"\n" +
	"write_keys\x18\x04 \x01(\rR\twriteKeys\x12(\n" +
	"\x10network_in_bytes\x18\x05 \x01(\x04R\x0enetworkInBytes\x12*\n" +
	"\x11network_out_bytes\x18\x06 \x01(\x04R\x0fnetworkOutBytes\x12,\n" +
	"\x12logical_read_bytes\x18\a \x01(\x04R\x10logicalReadBytes\x12.\n" +
	"\x13logical_write_bytes\x18\b \x01(\x04R\x11logicalWriteBytes\"k\n" +
	"\fRegionRecord\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12>\n" +
	"\x05items\x18\x02 \x03(\v2(.resource_usage_agent.GroupTagRecordItemR\x05items2r\n" +
	"\x12ResourceUsageAgent\x12\\\n" +
	"\x06Report\x12).resource_usage_agent.ResourceUsageRecord\x1a#.resource_usage_agent.EmptyResponse\"\x00(\x012\x83\x01\n" +
	"\x16ResourceMeteringPubSub\x12i\n" +
	"\tSubscribe\x12-.resource_usage_agent.ResourceMeteringRequest\x1a).resource_usage_agent.ResourceUsageRecord\"\x000\x01B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_resource_usage_agent_proto_rawDescOnce sync.Once
	file_resource_usage_agent_proto_rawDescData []byte
)

func file_resource_usage_agent_proto_rawDescGZIP() []byte {
	file_resource_usage_agent_proto_rawDescOnce.Do(func() {
		file_resource_usage_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_usage_agent_proto_rawDesc), len(file_resource_usage_agent_proto_rawDesc)))
	})
	return file_resource_usage_agent_proto_rawDescData
}

var file_resource_usage_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resource_usage_agent_proto_goTypes = []any{
	(*ResourceMeteringRequest)(nil), // 0: resource_usage_agent.ResourceMeteringRequest
	(*EmptyResponse)(nil),           // 1: resource_usage_agent.EmptyResponse
	(*ResourceUsageRecord)(nil),     // 2: resource_usage_agent.ResourceUsageRecord
	(*GroupTagRecord)(nil),          // 3: resource_usage_agent.GroupTagRecord
	(*GroupTagRecordItem)(nil),      // 4: resource_usage_agent.GroupTagRecordItem
	(*RegionRecord)(nil),            // 5: resource_usage_agent.RegionRecord
}
var file_resource_usage_agent_proto_depIdxs = []int32{
	3, // 0: resource_usage_agent.ResourceUsageRecord.record:type_name -> resource_usage_agent.GroupTagRecord
	5, // 1: resource_usage_agent.ResourceUsageRecord.region_record:type_name -> resource_usage_agent.RegionRecord
	4, // 2: resource_usage_agent.GroupTagRecord.items:type_name -> resource_usage_agent.GroupTagRecordItem
	4, // 3: resource_usage_agent.RegionRecord.items:type_name -> resource_usage_agent.GroupTagRecordItem
	2, // 4: resource_usage_agent.ResourceUsageAgent.Report:input_type -> resource_usage_agent.ResourceUsageRecord
	0, // 5: resource_usage_agent.ResourceMeteringPubSub.Subscribe:input_type -> resource_usage_agent.ResourceMeteringRequest
	1, // 6: resource_usage_agent.ResourceUsageAgent.Report:output_type -> resource_usage_agent.EmptyResponse
	2, // 7: resource_usage_agent.ResourceMeteringPubSub.Subscribe:output_type -> resource_usage_agent.ResourceUsageRecord
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resource_usage_agent_proto_init() }
func file_resource_usage_agent_proto_init() {
	if File_resource_usage_agent_proto != nil {
		return
	}
	file_resource_usage_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*ResourceUsageRecord_Record)(nil),
		(*ResourceUsageRecord_RegionRecord)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_usage_agent_proto_rawDesc), len(file_resource_usage_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_resource_usage_agent_proto_goTypes,
		DependencyIndexes: file_resource_usage_agent_proto_depIdxs,
		MessageInfos:      file_resource_usage_agent_proto_msgTypes,
	}.Build()
	File_resource_usage_agent_proto = out.File
	file_resource_usage_agent_proto_goTypes = nil
	file_resource_usage_agent_proto_depIdxs = nil
}
