// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mpp.proto

package mpp

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	coprocessor "github.com/pingcap/kvproto/pkg/coprocessor"
	kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"
	metapb "github.com/pingcap/kvproto/pkg/metapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskMeta contains meta of a mpp plan, including query's ts and task address.
type TaskMeta struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StartTs                uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`                                                 // start ts of a query
	TaskId                 int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                    // if task id is -1 , it indicates a tidb task.
	PartitionId            int64                  `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`                                     // Only used for hash partition
	Address                string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                                                                 // target address of this task.
	GatherId               uint64                 `protobuf:"varint,5,opt,name=gather_id,json=gatherId,proto3" json:"gather_id,omitempty"`                                              // used to distinguish different gathers in the mpp query.
	QueryTs                uint64                 `protobuf:"varint,6,opt,name=query_ts,json=queryTs,proto3" json:"query_ts,omitempty"`                                                 // timestamp when start to execute query, used for TiFlash miniTSO schedule.
	LocalQueryId           uint64                 `protobuf:"varint,7,opt,name=local_query_id,json=localQueryId,proto3" json:"local_query_id,omitempty"`                                // unique local query_id if tidb don't restart. So we can use gather_id + query_ts + local_query_id + server_id to represent a global unique query.
	ServerId               uint64                 `protobuf:"varint,8,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                                              // TiDB server id
	MppVersion             int64                  `protobuf:"varint,9,opt,name=mpp_version,json=mppVersion,proto3" json:"mpp_version,omitempty"`                                        // mpp version
	KeyspaceId             uint32                 `protobuf:"varint,10,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`                                       // keyspace id of the request
	CoordinatorAddress     string                 `protobuf:"bytes,11,opt,name=coordinator_address,json=coordinatorAddress,proto3" json:"coordinator_address,omitempty"`                // coordinator_address of this query
	ReportExecutionSummary bool                   `protobuf:"varint,12,opt,name=report_execution_summary,json=reportExecutionSummary,proto3" json:"report_execution_summary,omitempty"` // Only when coordinator_address is not empty, this flag can be true. When set to true, TiFlash only report execution summary through ReportMPPTaskStatus service, don't include summaries in MppDataPacket
	ApiVersion             kvrpcpb.APIVersion     `protobuf:"varint,16,opt,name=api_version,json=apiVersion,proto3,enum=kvrpcpb.APIVersion" json:"api_version,omitempty"`               // API version of the request
	ResourceGroupName      string                 `protobuf:"bytes,17,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	ConnectionId           uint64                 `protobuf:"varint,18,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`         // This is the session id between a client and tidb
	ConnectionAlias        string                 `protobuf:"bytes,19,opt,name=connection_alias,json=connectionAlias,proto3" json:"connection_alias,omitempty"` // This is the session alias between a client and tidb
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TaskMeta) Reset() {
	*x = TaskMeta{}
	mi := &file_mpp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMeta) ProtoMessage() {}

func (x *TaskMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMeta.ProtoReflect.Descriptor instead.
func (*TaskMeta) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMeta) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TaskMeta) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskMeta) GetPartitionId() int64 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *TaskMeta) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TaskMeta) GetGatherId() uint64 {
	if x != nil {
		return x.GatherId
	}
	return 0
}

func (x *TaskMeta) GetQueryTs() uint64 {
	if x != nil {
		return x.QueryTs
	}
	return 0
}

func (x *TaskMeta) GetLocalQueryId() uint64 {
	if x != nil {
		return x.LocalQueryId
	}
	return 0
}

func (x *TaskMeta) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *TaskMeta) GetMppVersion() int64 {
	if x != nil {
		return x.MppVersion
	}
	return 0
}

func (x *TaskMeta) GetKeyspaceId() uint32 {
	if x != nil {
		return x.KeyspaceId
	}
	return 0
}

func (x *TaskMeta) GetCoordinatorAddress() string {
	if x != nil {
		return x.CoordinatorAddress
	}
	return ""
}

func (x *TaskMeta) GetReportExecutionSummary() bool {
	if x != nil {
		return x.ReportExecutionSummary
	}
	return false
}

func (x *TaskMeta) GetApiVersion() kvrpcpb.APIVersion {
	if x != nil {
		return x.ApiVersion
	}
	return kvrpcpb.APIVersion(0)
}

func (x *TaskMeta) GetResourceGroupName() string {
	if x != nil {
		return x.ResourceGroupName
	}
	return ""
}

func (x *TaskMeta) GetConnectionId() uint64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

func (x *TaskMeta) GetConnectionAlias() string {
	if x != nil {
		return x.ConnectionAlias
	}
	return ""
}

type IsAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAliveRequest) Reset() {
	*x = IsAliveRequest{}
	mi := &file_mpp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveRequest) ProtoMessage() {}

func (x *IsAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveRequest.ProtoReflect.Descriptor instead.
func (*IsAliveRequest) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{1}
}

type IsAliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	MppVersion    int64                  `protobuf:"varint,2,opt,name=mpp_version,json=mppVersion,proto3" json:"mpp_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAliveResponse) Reset() {
	*x = IsAliveResponse{}
	mi := &file_mpp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveResponse) ProtoMessage() {}

func (x *IsAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveResponse.ProtoReflect.Descriptor instead.
func (*IsAliveResponse) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{2}
}

func (x *IsAliveResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *IsAliveResponse) GetMppVersion() int64 {
	if x != nil {
		return x.MppVersion
	}
	return 0
}

// Dipsatch the task request to different tiflash servers.
type DispatchTaskRequest struct {
	state       protoimpl.MessageState    `protogen:"open.v1"`
	Meta        *TaskMeta                 `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	EncodedPlan []byte                    `protobuf:"bytes,2,opt,name=encoded_plan,json=encodedPlan,proto3" json:"encoded_plan,omitempty"`
	Timeout     int64                     `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Regions     []*coprocessor.RegionInfo `protobuf:"bytes,4,rep,name=regions,proto3" json:"regions,omitempty"`
	// If this task contains table scan, we still need their region info.
	SchemaVer int64 `protobuf:"varint,5,opt,name=schema_ver,json=schemaVer,proto3" json:"schema_ver,omitempty"`
	// Used for partition table scan
	TableRegions  []*coprocessor.TableRegions `protobuf:"bytes,6,rep,name=table_regions,json=tableRegions,proto3" json:"table_regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_mpp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchTaskRequest) GetMeta() *TaskMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DispatchTaskRequest) GetEncodedPlan() []byte {
	if x != nil {
		return x.EncodedPlan
	}
	return nil
}

func (x *DispatchTaskRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *DispatchTaskRequest) GetRegions() []*coprocessor.RegionInfo {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *DispatchTaskRequest) GetSchemaVer() int64 {
	if x != nil {
		return x.SchemaVer
	}
	return 0
}

func (x *DispatchTaskRequest) GetTableRegions() []*coprocessor.TableRegions {
	if x != nil {
		return x.TableRegions
	}
	return nil
}

// Get response of DispatchTaskRequest.
type DispatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	RetryRegions  []*metapb.Region       `protobuf:"bytes,2,rep,name=retry_regions,json=retryRegions,proto3" json:"retry_regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_mpp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchTaskResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DispatchTaskResponse) GetRetryRegions() []*metapb.Region {
	if x != nil {
		return x.RetryRegions
	}
	return nil
}

// CancelTaskRequest closes the execution of a task.
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *TaskMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_mpp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskRequest) GetMeta() *TaskMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CancelTaskRequest) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_mpp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// ReportTaskStatus reports the execution status of a task.
// when TiFlash reports status to TiDB, ReportTaskStatusRequest serialize tipb.TiFlashExecutionInfo into data;
type ReportTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *TaskMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusRequest) Reset() {
	*x = ReportTaskStatusRequest{}
	mi := &file_mpp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusRequest) ProtoMessage() {}

func (x *ReportTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{7}
}

func (x *ReportTaskStatusRequest) GetMeta() *TaskMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReportTaskStatusRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReportTaskStatusRequest) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReportTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusResponse) Reset() {
	*x = ReportTaskStatusResponse{}
	mi := &file_mpp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusResponse) ProtoMessage() {}

func (x *ReportTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{8}
}

func (x *ReportTaskStatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// build connection between different tasks. Data is sent by the tasks that are closer to the data sources.
type EstablishMPPConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderMeta    *TaskMeta              `protobuf:"bytes,1,opt,name=sender_meta,json=senderMeta,proto3" json:"sender_meta,omitempty"`       // node closer to the source
	ReceiverMeta  *TaskMeta              `protobuf:"bytes,2,opt,name=receiver_meta,json=receiverMeta,proto3" json:"receiver_meta,omitempty"` // node closer to the tidb mpp gather.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishMPPConnectionRequest) Reset() {
	*x = EstablishMPPConnectionRequest{}
	mi := &file_mpp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishMPPConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishMPPConnectionRequest) ProtoMessage() {}

func (x *EstablishMPPConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishMPPConnectionRequest.ProtoReflect.Descriptor instead.
func (*EstablishMPPConnectionRequest) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{9}
}

func (x *EstablishMPPConnectionRequest) GetSenderMeta() *TaskMeta {
	if x != nil {
		return x.SenderMeta
	}
	return nil
}

func (x *EstablishMPPConnectionRequest) GetReceiverMeta() *TaskMeta {
	if x != nil {
		return x.ReceiverMeta
	}
	return nil
}

// when TiFlash sends data to TiDB, Data packets wrap tipb.SelectResponse, i.e., serialize tipb.SelectResponse into data;
// when TiFlash sends data to TiFlash, data blocks are serialized into chunks, and the execution_summaries in tipb.SelectResponse are serialized into data only for the last packet.
type MPPDataPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Chunks        [][]byte               `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	StreamIds     []uint64               `protobuf:"varint,4,rep,packed,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"` // version of data packet format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPPDataPacket) Reset() {
	*x = MPPDataPacket{}
	mi := &file_mpp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPPDataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPPDataPacket) ProtoMessage() {}

func (x *MPPDataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPPDataPacket.ProtoReflect.Descriptor instead.
func (*MPPDataPacket) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{10}
}

func (x *MPPDataPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MPPDataPacket) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MPPDataPacket) GetChunks() [][]byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *MPPDataPacket) GetStreamIds() []uint64 {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

func (x *MPPDataPacket) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MppVersion    int64                  `protobuf:"varint,3,opt,name=mpp_version,json=mppVersion,proto3" json:"mpp_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_mpp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_mpp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_mpp_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetMppVersion() int64 {
	if x != nil {
		return x.MppVersion
	}
	return 0
}

var File_mpp_proto protoreflect.FileDescriptor

const file_mpp_proto_rawDesc = "" +
	"\n" +
	"\tmpp.proto\x12\x03mpp\x1a\x11coprocessor.proto\x1a\fmetapb.proto\x1a\rkvrpcpb.proto\x1a\x0frustproto.proto\"\xd9\x04\n" +
	"\bTaskMeta\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\x03R\vpartitionId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1b\n" +
	"\tgather_id\x18\x05 \x01(\x04R\bgatherId\x12\x19\n" +
	"\bquery_ts\x18\x06 \x01(\x04R\aqueryTs\x12$\n" +
	"\x0elocal_query_id\x18\a \x01(\x04R\flocalQueryId\x12\x1b\n" +
	"\tserver_id\x18\b \x01(\x04R\bserverId\x12\x1f\n" +
	"\vmpp_version\x18\t \x01(\x03R\n" +
	"mppVersion\x12\x1f\n" +
	"\vkeyspace_id\x18\n" +
	" \x01(\rR\n" +
	"keyspaceId\x12/\n" +
	"\x13coordinator_address\x18\v \x01(\tR\x12coordinatorAddress\x128\n" +
	"\x18report_execution_summary\x18\f \x01(\bR\x16reportExecutionSummary\x124\n" +
	"\vapi_version\x18\x10 \x01(\x0e2\x13.kvrpcpb.APIVersionR\n" +
	"apiVersion\x12.\n" +
	"\x13resource_group_name\x18\x11 \x01(\tR\x11resourceGroupName\x12#\n" +
	"\rconnection_id\x18\x12 \x01(\x04R\fconnectionId\x12)\n" +
	"\x10connection_alias\x18\x13 \x01(\tR\x0fconnectionAlias\"\x10\n" +
	"\x0eIsAliveRequest\"P\n" +
	"\x0fIsAliveResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1f\n" +
	"\vmpp_version\x18\x02 \x01(\x03R\n" +
	"mppVersion\"\x87\x02\n" +
	"\x13DispatchTaskRequest\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.mpp.TaskMetaR\x04meta\x12!\n" +
	"\fencoded_plan\x18\x02 \x01(\fR\vencodedPlan\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x121\n" +
	"\aregions\x18\x04 \x03(\v2\x17.coprocessor.RegionInfoR\aregions\x12\x1d\n" +
	"\n" +
	"schema_ver\x18\x05 \x01(\x03R\tschemaVer\x12>\n" +
	"\rtable_regions\x18\x06 \x03(\v2\x19.coprocessor.TableRegionsR\ftableRegions\"m\n" +
	"\x14DispatchTaskResponse\x12 \n" +
	"\x05error\x18\x01 \x01(\v2\n" +
	".mpp.ErrorR\x05error\x123\n" +
	"\rretry_regions\x18\x02 \x03(\v2\x0e.metapb.RegionR\fretryRegions\"X\n" +
	"\x11CancelTaskRequest\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.mpp.TaskMetaR\x04meta\x12 \n" +
	"\x05error\x18\x02 \x01(\v2\n" +
	".mpp.ErrorR\x05error\"6\n" +
	"\x12CancelTaskResponse\x12 \n" +
	"\x05error\x18\x01 \x01(\v2\n" +
	".mpp.ErrorR\x05error\"r\n" +
	"\x17ReportTaskStatusRequest\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.mpp.TaskMetaR\x04meta\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12 \n" +
	"\x05error\x18\x03 \x01(\v2\n" +
	".mpp.ErrorR\x05error\"<\n" +
	"\x18ReportTaskStatusResponse\x12 \n" +
	"\x05error\x18\x01 \x01(\v2\n" +
	".mpp.ErrorR\x05error\"\x83\x01\n" +
	"\x1dEstablishMPPConnectionRequest\x12.\n" +
	"\vsender_meta\x18\x01 \x01(\v2\r.mpp.TaskMetaR\n" +
	"senderMeta\x122\n" +
	"\rreceiver_meta\x18\x02 \x01(\v2\r.mpp.TaskMetaR\freceiverMeta\"\x96\x01\n" +
	"\rMPPDataPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12 \n" +
	"\x05error\x18\x02 \x01(\v2\n" +
	".mpp.ErrorR\x05error\x12\x16\n" +
	"\x06chunks\x18\x03 \x03(\fR\x06chunks\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x04 \x03(\x04R\tstreamIds\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"N\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vmpp_version\x18\x03 \x01(\x03R\n" +
	"mppVersionB\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_mpp_proto_rawDescOnce sync.Once
	file_mpp_proto_rawDescData []byte
)

func file_mpp_proto_rawDescGZIP() []byte {
	file_mpp_proto_rawDescOnce.Do(func() {
		file_mpp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpp_proto_rawDesc), len(file_mpp_proto_rawDesc)))
	})
	return file_mpp_proto_rawDescData
}

var file_mpp_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_mpp_proto_goTypes = []any{
	(*TaskMeta)(nil),                      // 0: mpp.TaskMeta
	(*IsAliveRequest)(nil),                // 1: mpp.IsAliveRequest
	(*IsAliveResponse)(nil),               // 2: mpp.IsAliveResponse
	(*DispatchTaskRequest)(nil),           // 3: mpp.DispatchTaskRequest
	(*DispatchTaskResponse)(nil),          // 4: mpp.DispatchTaskResponse
	(*CancelTaskRequest)(nil),             // 5: mpp.CancelTaskRequest
	(*CancelTaskResponse)(nil),            // 6: mpp.CancelTaskResponse
	(*ReportTaskStatusRequest)(nil),       // 7: mpp.ReportTaskStatusRequest
	(*ReportTaskStatusResponse)(nil),      // 8: mpp.ReportTaskStatusResponse
	(*EstablishMPPConnectionRequest)(nil), // 9: mpp.EstablishMPPConnectionRequest
	(*MPPDataPacket)(nil),                 // 10: mpp.MPPDataPacket
	(*Error)(nil),                         // 11: mpp.Error
	(kvrpcpb.APIVersion)(0),               // 12: kvrpcpb.APIVersion
	(*coprocessor.RegionInfo)(nil),        // 13: coprocessor.RegionInfo
	(*coprocessor.TableRegions)(nil),      // 14: coprocessor.TableRegions
	(*metapb.Region)(nil),                 // 15: metapb.Region
}
var file_mpp_proto_depIdxs = []int32{
	12, // 0: mpp.TaskMeta.api_version:type_name -> kvrpcpb.APIVersion
	0,  // 1: mpp.DispatchTaskRequest.meta:type_name -> mpp.TaskMeta
	13, // 2: mpp.DispatchTaskRequest.regions:type_name -> coprocessor.RegionInfo
	14, // 3: mpp.DispatchTaskRequest.table_regions:type_name -> coprocessor.TableRegions
	11, // 4: mpp.DispatchTaskResponse.error:type_name -> mpp.Error
	15, // 5: mpp.DispatchTaskResponse.retry_regions:type_name -> metapb.Region
	0,  // 6: mpp.CancelTaskRequest.meta:type_name -> mpp.TaskMeta
	11, // 7: mpp.CancelTaskRequest.error:type_name -> mpp.Error
	11, // 8: mpp.CancelTaskResponse.error:type_name -> mpp.Error
	0,  // 9: mpp.ReportTaskStatusRequest.meta:type_name -> mpp.TaskMeta
	11, // 10: mpp.ReportTaskStatusRequest.error:type_name -> mpp.Error
	11, // 11: mpp.ReportTaskStatusResponse.error:type_name -> mpp.Error
	0,  // 12: mpp.EstablishMPPConnectionRequest.sender_meta:type_name -> mpp.TaskMeta
	0,  // 13: mpp.EstablishMPPConnectionRequest.receiver_meta:type_name -> mpp.TaskMeta
	11, // 14: mpp.MPPDataPacket.error:type_name -> mpp.Error
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_mpp_proto_init() }
func file_mpp_proto_init() {
	if File_mpp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpp_proto_rawDesc), len(file_mpp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mpp_proto_goTypes,
		DependencyIndexes: file_mpp_proto_depIdxs,
		MessageInfos:      file_mpp_proto_msgTypes,
	}.Build()
	File_mpp_proto = out.File
	file_mpp_proto_goTypes = nil
	file_mpp_proto_depIdxs = nil
}
