// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: keyspacepb.proto

package keyspacepb

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Keyspace_LoadKeyspace_FullMethodName        = "/keyspacepb.Keyspace/LoadKeyspace"
	Keyspace_WatchKeyspaces_FullMethodName      = "/keyspacepb.Keyspace/WatchKeyspaces"
	Keyspace_UpdateKeyspaceState_FullMethodName = "/keyspacepb.Keyspace/UpdateKeyspaceState"
	Keyspace_GetAllKeyspaces_FullMethodName     = "/keyspacepb.Keyspace/GetAllKeyspaces"
)

// KeyspaceClient is the client API for Keyspace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Keyspace provides services to manage keyspaces.
type KeyspaceClient interface {
	LoadKeyspace(ctx context.Context, in *LoadKeyspaceRequest, opts ...grpc.CallOption) (*LoadKeyspaceResponse, error)
	// WatchKeyspaces first return all current keyspaces' metadata as its first response.
	// Then, it returns responses containing keyspaces that had their metadata changed.
	WatchKeyspaces(ctx context.Context, in *WatchKeyspacesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchKeyspacesResponse], error)
	UpdateKeyspaceState(ctx context.Context, in *UpdateKeyspaceStateRequest, opts ...grpc.CallOption) (*UpdateKeyspaceStateResponse, error)
	GetAllKeyspaces(ctx context.Context, in *GetAllKeyspacesRequest, opts ...grpc.CallOption) (*GetAllKeyspacesResponse, error)
}

type keyspaceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyspaceClient(cc grpc.ClientConnInterface) KeyspaceClient {
	return &keyspaceClient{cc}
}

func (c *keyspaceClient) LoadKeyspace(ctx context.Context, in *LoadKeyspaceRequest, opts ...grpc.CallOption) (*LoadKeyspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadKeyspaceResponse)
	err := c.cc.Invoke(ctx, Keyspace_LoadKeyspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyspaceClient) WatchKeyspaces(ctx context.Context, in *WatchKeyspacesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchKeyspacesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Keyspace_ServiceDesc.Streams[0], Keyspace_WatchKeyspaces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchKeyspacesRequest, WatchKeyspacesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keyspace_WatchKeyspacesClient = grpc.ServerStreamingClient[WatchKeyspacesResponse]

func (c *keyspaceClient) UpdateKeyspaceState(ctx context.Context, in *UpdateKeyspaceStateRequest, opts ...grpc.CallOption) (*UpdateKeyspaceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKeyspaceStateResponse)
	err := c.cc.Invoke(ctx, Keyspace_UpdateKeyspaceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyspaceClient) GetAllKeyspaces(ctx context.Context, in *GetAllKeyspacesRequest, opts ...grpc.CallOption) (*GetAllKeyspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllKeyspacesResponse)
	err := c.cc.Invoke(ctx, Keyspace_GetAllKeyspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyspaceServer is the server API for Keyspace service.
// All implementations must embed UnimplementedKeyspaceServer
// for forward compatibility.
//
// Keyspace provides services to manage keyspaces.
type KeyspaceServer interface {
	LoadKeyspace(context.Context, *LoadKeyspaceRequest) (*LoadKeyspaceResponse, error)
	// WatchKeyspaces first return all current keyspaces' metadata as its first response.
	// Then, it returns responses containing keyspaces that had their metadata changed.
	WatchKeyspaces(*WatchKeyspacesRequest, grpc.ServerStreamingServer[WatchKeyspacesResponse]) error
	UpdateKeyspaceState(context.Context, *UpdateKeyspaceStateRequest) (*UpdateKeyspaceStateResponse, error)
	GetAllKeyspaces(context.Context, *GetAllKeyspacesRequest) (*GetAllKeyspacesResponse, error)
	mustEmbedUnimplementedKeyspaceServer()
}

// UnimplementedKeyspaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyspaceServer struct{}

func (UnimplementedKeyspaceServer) LoadKeyspace(context.Context, *LoadKeyspaceRequest) (*LoadKeyspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadKeyspace not implemented")
}
func (UnimplementedKeyspaceServer) WatchKeyspaces(*WatchKeyspacesRequest, grpc.ServerStreamingServer[WatchKeyspacesResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchKeyspaces not implemented")
}
func (UnimplementedKeyspaceServer) UpdateKeyspaceState(context.Context, *UpdateKeyspaceStateRequest) (*UpdateKeyspaceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKeyspaceState not implemented")
}
func (UnimplementedKeyspaceServer) GetAllKeyspaces(context.Context, *GetAllKeyspacesRequest) (*GetAllKeyspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllKeyspaces not implemented")
}
func (UnimplementedKeyspaceServer) mustEmbedUnimplementedKeyspaceServer() {}
func (UnimplementedKeyspaceServer) testEmbeddedByValue()                  {}

// UnsafeKeyspaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyspaceServer will
// result in compilation errors.
type UnsafeKeyspaceServer interface {
	mustEmbedUnimplementedKeyspaceServer()
}

func RegisterKeyspaceServer(s grpc.ServiceRegistrar, srv KeyspaceServer) {
	// If the following call panics, it indicates UnimplementedKeyspaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Keyspace_ServiceDesc, srv)
}

func _Keyspace_LoadKeyspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadKeyspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyspaceServer).LoadKeyspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keyspace_LoadKeyspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyspaceServer).LoadKeyspace(ctx, req.(*LoadKeyspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keyspace_WatchKeyspaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchKeyspacesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyspaceServer).WatchKeyspaces(m, &grpc.GenericServerStream[WatchKeyspacesRequest, WatchKeyspacesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keyspace_WatchKeyspacesServer = grpc.ServerStreamingServer[WatchKeyspacesResponse]

func _Keyspace_UpdateKeyspaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyspaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyspaceServer).UpdateKeyspaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keyspace_UpdateKeyspaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyspaceServer).UpdateKeyspaceState(ctx, req.(*UpdateKeyspaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keyspace_GetAllKeyspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllKeyspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyspaceServer).GetAllKeyspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keyspace_GetAllKeyspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyspaceServer).GetAllKeyspaces(ctx, req.(*GetAllKeyspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keyspace_ServiceDesc is the grpc.ServiceDesc for Keyspace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keyspace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keyspacepb.Keyspace",
	HandlerType: (*KeyspaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadKeyspace",
			Handler:    _Keyspace_LoadKeyspace_Handler,
		},
		{
			MethodName: "UpdateKeyspaceState",
			Handler:    _Keyspace_UpdateKeyspaceState_Handler,
		},
		{
			MethodName: "GetAllKeyspaces",
			Handler:    _Keyspace_GetAllKeyspaces_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchKeyspaces",
			Handler:       _Keyspace_WatchKeyspaces_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "keyspacepb.proto",
}
