// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: import_kvpb.proto

package import_kvpb

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImportKV_SwitchMode_FullMethodName     = "/import_kvpb.ImportKV/SwitchMode"
	ImportKV_OpenEngine_FullMethodName     = "/import_kvpb.ImportKV/OpenEngine"
	ImportKV_WriteEngine_FullMethodName    = "/import_kvpb.ImportKV/WriteEngine"
	ImportKV_WriteEngineV3_FullMethodName  = "/import_kvpb.ImportKV/WriteEngineV3"
	ImportKV_CloseEngine_FullMethodName    = "/import_kvpb.ImportKV/CloseEngine"
	ImportKV_ImportEngine_FullMethodName   = "/import_kvpb.ImportKV/ImportEngine"
	ImportKV_CleanupEngine_FullMethodName  = "/import_kvpb.ImportKV/CleanupEngine"
	ImportKV_CompactCluster_FullMethodName = "/import_kvpb.ImportKV/CompactCluster"
	ImportKV_GetVersion_FullMethodName     = "/import_kvpb.ImportKV/GetVersion"
	ImportKV_GetMetrics_FullMethodName     = "/import_kvpb.ImportKV/GetMetrics"
)

// ImportKVClient is the client API for ImportKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ImportKV provides a service to import key-value pairs to TiKV.
//
// In order to import key-value pairs to TiKV, the user should:
//  1. Open an engine identified by an UUID.
//  2. Open write streams to write key-value batches to the opened engine.
//     Different streams/clients can write to the same engine concurrently.
//  3. Close the engine after all write batches have been finished. An
//     engine can only be closed when all write streams are closed. An
//     engine can only be closed once, and it can not be opened again
//     once it is closed.
//  4. Import the data in the engine to the target cluster. Note that
//     the import process is not atomic, it requires the data to be
//     idempotent on retry. An engine can only be imported after it is
//     closed. An engine can be imported multiple times, but can not be
//     imported concurrently.
//  5. Clean up the engine after it has been imported. Delete all data
//     in the engine. An engine can not be cleaned up when it is
//     writing or importing.
type ImportKVClient interface {
	// Switch the target cluster to normal/import mode.
	SwitchMode(ctx context.Context, in *SwitchModeRequest, opts ...grpc.CallOption) (*SwitchModeResponse, error)
	// Open an engine.
	OpenEngine(ctx context.Context, in *OpenEngineRequest, opts ...grpc.CallOption) (*OpenEngineResponse, error)
	// Open a write stream to the engine.
	WriteEngine(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteEngineRequest, WriteEngineResponse], error)
	// Write to engine, single message version
	WriteEngineV3(ctx context.Context, in *WriteEngineV3Request, opts ...grpc.CallOption) (*WriteEngineResponse, error)
	// Close the engine.
	CloseEngine(ctx context.Context, in *CloseEngineRequest, opts ...grpc.CallOption) (*CloseEngineResponse, error)
	// Import the engine to the target cluster.
	ImportEngine(ctx context.Context, in *ImportEngineRequest, opts ...grpc.CallOption) (*ImportEngineResponse, error)
	// Clean up the engine.
	CleanupEngine(ctx context.Context, in *CleanupEngineRequest, opts ...grpc.CallOption) (*CleanupEngineResponse, error)
	// Compact the target cluster for better performance.
	CompactCluster(ctx context.Context, in *CompactClusterRequest, opts ...grpc.CallOption) (*CompactClusterResponse, error)
	// Get current version and commit hash
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Get importer metrics
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type importKVClient struct {
	cc grpc.ClientConnInterface
}

func NewImportKVClient(cc grpc.ClientConnInterface) ImportKVClient {
	return &importKVClient{cc}
}

func (c *importKVClient) SwitchMode(ctx context.Context, in *SwitchModeRequest, opts ...grpc.CallOption) (*SwitchModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchModeResponse)
	err := c.cc.Invoke(ctx, ImportKV_SwitchMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) OpenEngine(ctx context.Context, in *OpenEngineRequest, opts ...grpc.CallOption) (*OpenEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenEngineResponse)
	err := c.cc.Invoke(ctx, ImportKV_OpenEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) WriteEngine(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteEngineRequest, WriteEngineResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImportKV_ServiceDesc.Streams[0], ImportKV_WriteEngine_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteEngineRequest, WriteEngineResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImportKV_WriteEngineClient = grpc.ClientStreamingClient[WriteEngineRequest, WriteEngineResponse]

func (c *importKVClient) WriteEngineV3(ctx context.Context, in *WriteEngineV3Request, opts ...grpc.CallOption) (*WriteEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteEngineResponse)
	err := c.cc.Invoke(ctx, ImportKV_WriteEngineV3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) CloseEngine(ctx context.Context, in *CloseEngineRequest, opts ...grpc.CallOption) (*CloseEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseEngineResponse)
	err := c.cc.Invoke(ctx, ImportKV_CloseEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) ImportEngine(ctx context.Context, in *ImportEngineRequest, opts ...grpc.CallOption) (*ImportEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportEngineResponse)
	err := c.cc.Invoke(ctx, ImportKV_ImportEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) CleanupEngine(ctx context.Context, in *CleanupEngineRequest, opts ...grpc.CallOption) (*CleanupEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupEngineResponse)
	err := c.cc.Invoke(ctx, ImportKV_CleanupEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) CompactCluster(ctx context.Context, in *CompactClusterRequest, opts ...grpc.CallOption) (*CompactClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactClusterResponse)
	err := c.cc.Invoke(ctx, ImportKV_CompactCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, ImportKV_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importKVClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ImportKV_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportKVServer is the server API for ImportKV service.
// All implementations must embed UnimplementedImportKVServer
// for forward compatibility.
//
// ImportKV provides a service to import key-value pairs to TiKV.
//
// In order to import key-value pairs to TiKV, the user should:
//  1. Open an engine identified by an UUID.
//  2. Open write streams to write key-value batches to the opened engine.
//     Different streams/clients can write to the same engine concurrently.
//  3. Close the engine after all write batches have been finished. An
//     engine can only be closed when all write streams are closed. An
//     engine can only be closed once, and it can not be opened again
//     once it is closed.
//  4. Import the data in the engine to the target cluster. Note that
//     the import process is not atomic, it requires the data to be
//     idempotent on retry. An engine can only be imported after it is
//     closed. An engine can be imported multiple times, but can not be
//     imported concurrently.
//  5. Clean up the engine after it has been imported. Delete all data
//     in the engine. An engine can not be cleaned up when it is
//     writing or importing.
type ImportKVServer interface {
	// Switch the target cluster to normal/import mode.
	SwitchMode(context.Context, *SwitchModeRequest) (*SwitchModeResponse, error)
	// Open an engine.
	OpenEngine(context.Context, *OpenEngineRequest) (*OpenEngineResponse, error)
	// Open a write stream to the engine.
	WriteEngine(grpc.ClientStreamingServer[WriteEngineRequest, WriteEngineResponse]) error
	// Write to engine, single message version
	WriteEngineV3(context.Context, *WriteEngineV3Request) (*WriteEngineResponse, error)
	// Close the engine.
	CloseEngine(context.Context, *CloseEngineRequest) (*CloseEngineResponse, error)
	// Import the engine to the target cluster.
	ImportEngine(context.Context, *ImportEngineRequest) (*ImportEngineResponse, error)
	// Clean up the engine.
	CleanupEngine(context.Context, *CleanupEngineRequest) (*CleanupEngineResponse, error)
	// Compact the target cluster for better performance.
	CompactCluster(context.Context, *CompactClusterRequest) (*CompactClusterResponse, error)
	// Get current version and commit hash
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Get importer metrics
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	mustEmbedUnimplementedImportKVServer()
}

// UnimplementedImportKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportKVServer struct{}

func (UnimplementedImportKVServer) SwitchMode(context.Context, *SwitchModeRequest) (*SwitchModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchMode not implemented")
}
func (UnimplementedImportKVServer) OpenEngine(context.Context, *OpenEngineRequest) (*OpenEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenEngine not implemented")
}
func (UnimplementedImportKVServer) WriteEngine(grpc.ClientStreamingServer[WriteEngineRequest, WriteEngineResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteEngine not implemented")
}
func (UnimplementedImportKVServer) WriteEngineV3(context.Context, *WriteEngineV3Request) (*WriteEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteEngineV3 not implemented")
}
func (UnimplementedImportKVServer) CloseEngine(context.Context, *CloseEngineRequest) (*CloseEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseEngine not implemented")
}
func (UnimplementedImportKVServer) ImportEngine(context.Context, *ImportEngineRequest) (*ImportEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportEngine not implemented")
}
func (UnimplementedImportKVServer) CleanupEngine(context.Context, *CleanupEngineRequest) (*CleanupEngineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupEngine not implemented")
}
func (UnimplementedImportKVServer) CompactCluster(context.Context, *CompactClusterRequest) (*CompactClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompactCluster not implemented")
}
func (UnimplementedImportKVServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedImportKVServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedImportKVServer) mustEmbedUnimplementedImportKVServer() {}
func (UnimplementedImportKVServer) testEmbeddedByValue()                  {}

// UnsafeImportKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportKVServer will
// result in compilation errors.
type UnsafeImportKVServer interface {
	mustEmbedUnimplementedImportKVServer()
}

func RegisterImportKVServer(s grpc.ServiceRegistrar, srv ImportKVServer) {
	// If the following call panics, it indicates UnimplementedImportKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportKV_ServiceDesc, srv)
}

func _ImportKV_SwitchMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).SwitchMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_SwitchMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).SwitchMode(ctx, req.(*SwitchModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_OpenEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).OpenEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_OpenEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).OpenEngine(ctx, req.(*OpenEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_WriteEngine_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImportKVServer).WriteEngine(&grpc.GenericServerStream[WriteEngineRequest, WriteEngineResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImportKV_WriteEngineServer = grpc.ClientStreamingServer[WriteEngineRequest, WriteEngineResponse]

func _ImportKV_WriteEngineV3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteEngineV3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).WriteEngineV3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_WriteEngineV3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).WriteEngineV3(ctx, req.(*WriteEngineV3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_CloseEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).CloseEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_CloseEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).CloseEngine(ctx, req.(*CloseEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_ImportEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).ImportEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_ImportEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).ImportEngine(ctx, req.(*ImportEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_CleanupEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).CleanupEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_CleanupEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).CleanupEngine(ctx, req.(*CleanupEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_CompactCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).CompactCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_CompactCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).CompactCluster(ctx, req.(*CompactClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportKV_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportKVServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportKV_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportKVServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportKV_ServiceDesc is the grpc.ServiceDesc for ImportKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "import_kvpb.ImportKV",
	HandlerType: (*ImportKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SwitchMode",
			Handler:    _ImportKV_SwitchMode_Handler,
		},
		{
			MethodName: "OpenEngine",
			Handler:    _ImportKV_OpenEngine_Handler,
		},
		{
			MethodName: "WriteEngineV3",
			Handler:    _ImportKV_WriteEngineV3_Handler,
		},
		{
			MethodName: "CloseEngine",
			Handler:    _ImportKV_CloseEngine_Handler,
		},
		{
			MethodName: "ImportEngine",
			Handler:    _ImportKV_ImportEngine_Handler,
		},
		{
			MethodName: "CleanupEngine",
			Handler:    _ImportKV_CleanupEngine_Handler,
		},
		{
			MethodName: "CompactCluster",
			Handler:    _ImportKV_CompactCluster_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ImportKV_GetVersion_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ImportKV_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteEngine",
			Handler:       _ImportKV_WriteEngine_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "import_kvpb.proto",
}
