// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: disk_usage.proto

package disk_usage

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiskUsage int32

const (
	DiskUsage_Normal      DiskUsage = 0
	DiskUsage_AlmostFull  DiskUsage = 1
	DiskUsage_AlreadyFull DiskUsage = 2
)

// Enum value maps for DiskUsage.
var (
	DiskUsage_name = map[int32]string{
		0: "Normal",
		1: "AlmostFull",
		2: "AlreadyFull",
	}
	DiskUsage_value = map[string]int32{
		"Normal":      0,
		"AlmostFull":  1,
		"AlreadyFull": 2,
	}
)

func (x DiskUsage) Enum() *DiskUsage {
	p := new(DiskUsage)
	*p = x
	return p
}

func (x DiskUsage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskUsage) Descriptor() protoreflect.EnumDescriptor {
	return file_disk_usage_proto_enumTypes[0].Descriptor()
}

func (DiskUsage) Type() protoreflect.EnumType {
	return &file_disk_usage_proto_enumTypes[0]
}

func (x DiskUsage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskUsage.Descriptor instead.
func (DiskUsage) EnumDescriptor() ([]byte, []int) {
	return file_disk_usage_proto_rawDescGZIP(), []int{0}
}

var File_disk_usage_proto protoreflect.FileDescriptor

const file_disk_usage_proto_rawDesc = "" +
	"\n" +
	"\x10disk_usage.proto\x12\n" +
	"disk_usage\x1a\x0frustproto.proto*8\n" +
	"\tDiskUsage\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\x0e\n" +
	"\n" +
	"AlmostFull\x10\x01\x12\x0f\n" +
	"\vAlreadyFull\x10\x02B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_disk_usage_proto_rawDescOnce sync.Once
	file_disk_usage_proto_rawDescData []byte
)

func file_disk_usage_proto_rawDescGZIP() []byte {
	file_disk_usage_proto_rawDescOnce.Do(func() {
		file_disk_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disk_usage_proto_rawDesc), len(file_disk_usage_proto_rawDesc)))
	})
	return file_disk_usage_proto_rawDescData
}

var file_disk_usage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_disk_usage_proto_goTypes = []any{
	(DiskUsage)(0), // 0: disk_usage.DiskUsage
}
var file_disk_usage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_disk_usage_proto_init() }
func file_disk_usage_proto_init() {
	if File_disk_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disk_usage_proto_rawDesc), len(file_disk_usage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_disk_usage_proto_goTypes,
		DependencyIndexes: file_disk_usage_proto_depIdxs,
		EnumInfos:         file_disk_usage_proto_enumTypes,
	}.Build()
	File_disk_usage_proto = out.File
	file_disk_usage_proto_goTypes = nil
	file_disk_usage_proto_depIdxs = nil
}
