// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tsopb.proto

package tsopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	pdpb "github.com/pingcap/kvproto/pkg/pdpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_OK                   ErrorType = 0
	ErrorType_UNKNOWN              ErrorType = 1
	ErrorType_NOT_BOOTSTRAPPED     ErrorType = 2
	ErrorType_ALREADY_BOOTSTRAPPED ErrorType = 3
	ErrorType_INVALID_VALUE        ErrorType = 4
	ErrorType_CLUSTER_MISMATCHED   ErrorType = 5
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "OK",
		1: "UNKNOWN",
		2: "NOT_BOOTSTRAPPED",
		3: "ALREADY_BOOTSTRAPPED",
		4: "INVALID_VALUE",
		5: "CLUSTER_MISMATCHED",
	}
	ErrorType_value = map[string]int32{
		"OK":                   0,
		"UNKNOWN":              1,
		"NOT_BOOTSTRAPPED":     2,
		"ALREADY_BOOTSTRAPPED": 3,
		"INVALID_VALUE":        4,
		"CLUSTER_MISMATCHED":   5,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_tsopb_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_tsopb_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{0}
}

type RequestHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the ID of the cluster which be sent to.
	ClusterId uint64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// sender_id is the ID of the sender server.
	SenderId uint64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// keyspace_id is the unique id of the tenant/keyspace.
	KeyspaceId uint32 `protobuf:"varint,3,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	// keyspace_group_id is the unique id of the keyspace group to which the tenant/keyspace belongs.
	KeyspaceGroupId uint32 `protobuf:"varint,4,opt,name=keyspace_group_id,json=keyspaceGroupId,proto3" json:"keyspace_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_tsopb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *RequestHeader) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *RequestHeader) GetKeyspaceId() uint32 {
	if x != nil {
		return x.KeyspaceId
	}
	return 0
}

func (x *RequestHeader) GetKeyspaceGroupId() uint32 {
	if x != nil {
		return x.KeyspaceGroupId
	}
	return 0
}

type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the ID of the cluster which sent the response.
	ClusterId uint64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Error     *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// keyspace_id is the unique id of the tenant/keyspace as the response receiver.
	KeyspaceId uint32 `protobuf:"varint,3,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	// keyspace_group_id is the unique id of the keyspace group to which the tenant/keyspace belongs.
	KeyspaceGroupId uint32 `protobuf:"varint,4,opt,name=keyspace_group_id,json=keyspaceGroupId,proto3" json:"keyspace_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_tsopb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ResponseHeader) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ResponseHeader) GetKeyspaceId() uint32 {
	if x != nil {
		return x.KeyspaceId
	}
	return 0
}

func (x *ResponseHeader) GetKeyspaceGroupId() uint32 {
	if x != nil {
		return x.KeyspaceGroupId
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ErrorType              `protobuf:"varint,1,opt,name=type,proto3,enum=tsopb.ErrorType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_tsopb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_OK
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TsoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	DcLocation    string                 `protobuf:"bytes,3,opt,name=dc_location,json=dcLocation,proto3" json:"dc_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsoRequest) Reset() {
	*x = TsoRequest{}
	mi := &file_tsopb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsoRequest) ProtoMessage() {}

func (x *TsoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsoRequest.ProtoReflect.Descriptor instead.
func (*TsoRequest) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{3}
}

func (x *TsoRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TsoRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TsoRequest) GetDcLocation() string {
	if x != nil {
		return x.DcLocation
	}
	return ""
}

type TsoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Timestamp     *pdpb.Timestamp        `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TsoResponse) Reset() {
	*x = TsoResponse{}
	mi := &file_tsopb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsoResponse) ProtoMessage() {}

func (x *TsoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsoResponse.ProtoReflect.Descriptor instead.
func (*TsoResponse) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{4}
}

func (x *TsoResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TsoResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TsoResponse) GetTimestamp() *pdpb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Participant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique name of the TSO participant.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// id is the unique id of the TSO participant.
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// listen_urls is the serivce endpoint list in the url format.
	// listen_urls[0] is primary service endpoint.
	ListenUrls    []string `protobuf:"bytes,3,rep,name=listen_urls,json=listenUrls,proto3" json:"listen_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_tsopb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{5}
}

func (x *Participant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Participant) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Participant) GetListenUrls() []string {
	if x != nil {
		return x.ListenUrls
	}
	return nil
}

type KeyspaceGroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,2,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyspaceGroupMember) Reset() {
	*x = KeyspaceGroupMember{}
	mi := &file_tsopb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyspaceGroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyspaceGroupMember) ProtoMessage() {}

func (x *KeyspaceGroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyspaceGroupMember.ProtoReflect.Descriptor instead.
func (*KeyspaceGroupMember) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{6}
}

func (x *KeyspaceGroupMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeyspaceGroupMember) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type SplitState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SplitSource   uint32                 `protobuf:"varint,1,opt,name=split_source,json=splitSource,proto3" json:"split_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitState) Reset() {
	*x = SplitState{}
	mi := &file_tsopb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitState) ProtoMessage() {}

func (x *SplitState) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitState.ProtoReflect.Descriptor instead.
func (*SplitState) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{7}
}

func (x *SplitState) GetSplitSource() uint32 {
	if x != nil {
		return x.SplitSource
	}
	return 0
}

type KeyspaceGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserKind      string                 `protobuf:"bytes,2,opt,name=user_kind,json=userKind,proto3" json:"user_kind,omitempty"`
	SplitState    *SplitState            `protobuf:"bytes,3,opt,name=split_state,json=splitState,proto3" json:"split_state,omitempty"`
	Members       []*KeyspaceGroupMember `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyspaceGroup) Reset() {
	*x = KeyspaceGroup{}
	mi := &file_tsopb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyspaceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyspaceGroup) ProtoMessage() {}

func (x *KeyspaceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyspaceGroup.ProtoReflect.Descriptor instead.
func (*KeyspaceGroup) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{8}
}

func (x *KeyspaceGroup) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KeyspaceGroup) GetUserKind() string {
	if x != nil {
		return x.UserKind
	}
	return ""
}

func (x *KeyspaceGroup) GetSplitState() *SplitState {
	if x != nil {
		return x.SplitState
	}
	return nil
}

func (x *KeyspaceGroup) GetMembers() []*KeyspaceGroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type FindGroupByKeyspaceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyspaceId    uint32                 `protobuf:"varint,2,opt,name=keyspace_id,json=keyspaceId,proto3" json:"keyspace_id,omitempty"`
	ModRevision   uint64                 `protobuf:"varint,3,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindGroupByKeyspaceIDRequest) Reset() {
	*x = FindGroupByKeyspaceIDRequest{}
	mi := &file_tsopb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindGroupByKeyspaceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGroupByKeyspaceIDRequest) ProtoMessage() {}

func (x *FindGroupByKeyspaceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGroupByKeyspaceIDRequest.ProtoReflect.Descriptor instead.
func (*FindGroupByKeyspaceIDRequest) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{9}
}

func (x *FindGroupByKeyspaceIDRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindGroupByKeyspaceIDRequest) GetKeyspaceId() uint32 {
	if x != nil {
		return x.KeyspaceId
	}
	return 0
}

func (x *FindGroupByKeyspaceIDRequest) GetModRevision() uint64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

type FindGroupByKeyspaceIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyspaceGroup *KeyspaceGroup         `protobuf:"bytes,2,opt,name=keyspace_group,json=keyspaceGroup,proto3" json:"keyspace_group,omitempty"`
	ModRevision   uint64                 `protobuf:"varint,3,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindGroupByKeyspaceIDResponse) Reset() {
	*x = FindGroupByKeyspaceIDResponse{}
	mi := &file_tsopb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindGroupByKeyspaceIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGroupByKeyspaceIDResponse) ProtoMessage() {}

func (x *FindGroupByKeyspaceIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGroupByKeyspaceIDResponse.ProtoReflect.Descriptor instead.
func (*FindGroupByKeyspaceIDResponse) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{10}
}

func (x *FindGroupByKeyspaceIDResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindGroupByKeyspaceIDResponse) GetKeyspaceGroup() *KeyspaceGroup {
	if x != nil {
		return x.KeyspaceGroup
	}
	return nil
}

func (x *FindGroupByKeyspaceIDResponse) GetModRevision() uint64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

type GetMinTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RequestHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	DcLocation    string                 `protobuf:"bytes,2,opt,name=dc_location,json=dcLocation,proto3" json:"dc_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinTSRequest) Reset() {
	*x = GetMinTSRequest{}
	mi := &file_tsopb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinTSRequest) ProtoMessage() {}

func (x *GetMinTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinTSRequest.ProtoReflect.Descriptor instead.
func (*GetMinTSRequest) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{11}
}

func (x *GetMinTSRequest) GetHeader() *RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetMinTSRequest) GetDcLocation() string {
	if x != nil {
		return x.DcLocation
	}
	return ""
}

type GetMinTSResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Header    *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Timestamp *pdpb.Timestamp        `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// the count of keyspace group primaries that the TSO server/pod is serving
	KeyspaceGroupsServing uint32 `protobuf:"varint,3,opt,name=keyspace_groups_serving,json=keyspaceGroupsServing,proto3" json:"keyspace_groups_serving,omitempty"`
	// the total count of keyspace groups
	KeyspaceGroupsTotal uint32 `protobuf:"varint,4,opt,name=keyspace_groups_total,json=keyspaceGroupsTotal,proto3" json:"keyspace_groups_total,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMinTSResponse) Reset() {
	*x = GetMinTSResponse{}
	mi := &file_tsopb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinTSResponse) ProtoMessage() {}

func (x *GetMinTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsopb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinTSResponse.ProtoReflect.Descriptor instead.
func (*GetMinTSResponse) Descriptor() ([]byte, []int) {
	return file_tsopb_proto_rawDescGZIP(), []int{12}
}

func (x *GetMinTSResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetMinTSResponse) GetTimestamp() *pdpb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetMinTSResponse) GetKeyspaceGroupsServing() uint32 {
	if x != nil {
		return x.KeyspaceGroupsServing
	}
	return 0
}

func (x *GetMinTSResponse) GetKeyspaceGroupsTotal() uint32 {
	if x != nil {
		return x.KeyspaceGroupsTotal
	}
	return 0
}

var File_tsopb_proto protoreflect.FileDescriptor

const file_tsopb_proto_rawDesc = "" +
	"\n" +
	"\vtsopb.proto\x12\x05tsopb\x1a\n" +
	"pdpb.proto\x1a\x0frustproto.proto\"\x98\x01\n" +
	"\rRequestHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x04R\bsenderId\x12\x1f\n" +
	"\vkeyspace_id\x18\x03 \x01(\rR\n" +
	"keyspaceId\x12*\n" +
	"\x11keyspace_group_id\x18\x04 \x01(\rR\x0fkeyspaceGroupId\"\xa0\x01\n" +
	"\x0eResponseHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\"\n" +
	"\x05error\x18\x02 \x01(\v2\f.tsopb.ErrorR\x05error\x12\x1f\n" +
	"\vkeyspace_id\x18\x03 \x01(\rR\n" +
	"keyspaceId\x12*\n" +
	"\x11keyspace_group_id\x18\x04 \x01(\rR\x0fkeyspaceGroupId\"G\n" +
	"\x05Error\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.tsopb.ErrorTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\n" +
	"TsoRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.tsopb.RequestHeaderR\x06header\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1f\n" +
	"\vdc_location\x18\x03 \x01(\tR\n" +
	"dcLocation\"\x81\x01\n" +
	"\vTsoResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.tsopb.ResponseHeaderR\x06header\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12-\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x0f.pdpb.TimestampR\ttimestamp\"R\n" +
	"\vParticipant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x1f\n" +
	"\vlisten_urls\x18\x03 \x03(\tR\n" +
	"listenUrls\"N\n" +
	"\x13KeyspaceGroupMember\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x02 \x01(\bR\tisPrimary\"/\n" +
	"\n" +
	"SplitState\x12!\n" +
	"\fsplit_source\x18\x01 \x01(\rR\vsplitSource\"\xa6\x01\n" +
	"\rKeyspaceGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tuser_kind\x18\x02 \x01(\tR\buserKind\x122\n" +
	"\vsplit_state\x18\x03 \x01(\v2\x11.tsopb.SplitStateR\n" +
	"splitState\x124\n" +
	"\amembers\x18\x04 \x03(\v2\x1a.tsopb.KeyspaceGroupMemberR\amembers\"\x90\x01\n" +
	"\x1cFindGroupByKeyspaceIDRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.tsopb.RequestHeaderR\x06header\x12\x1f\n" +
	"\vkeyspace_id\x18\x02 \x01(\rR\n" +
	"keyspaceId\x12!\n" +
	"\fmod_revision\x18\x03 \x01(\x04R\vmodRevision\"\xae\x01\n" +
	"\x1dFindGroupByKeyspaceIDResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.tsopb.ResponseHeaderR\x06header\x12;\n" +
	"\x0ekeyspace_group\x18\x02 \x01(\v2\x14.tsopb.KeyspaceGroupR\rkeyspaceGroup\x12!\n" +
	"\fmod_revision\x18\x03 \x01(\x04R\vmodRevision\"`\n" +
	"\x0fGetMinTSRequest\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.tsopb.RequestHeaderR\x06header\x12\x1f\n" +
	"\vdc_location\x18\x02 \x01(\tR\n" +
	"dcLocation\"\xdc\x01\n" +
	"\x10GetMinTSResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x15.tsopb.ResponseHeaderR\x06header\x12-\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x0f.pdpb.TimestampR\ttimestamp\x126\n" +
	"\x17keyspace_groups_serving\x18\x03 \x01(\rR\x15keyspaceGroupsServing\x122\n" +
	"\x15keyspace_groups_total\x18\x04 \x01(\rR\x13keyspaceGroupsTotal*{\n" +
	"\tErrorType\x12\x06\n" +
	"\x02OK\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x14\n" +
	"\x10NOT_BOOTSTRAPPED\x10\x02\x12\x18\n" +
	"\x14ALREADY_BOOTSTRAPPED\x10\x03\x12\x11\n" +
	"\rINVALID_VALUE\x10\x04\x12\x16\n" +
	"\x12CLUSTER_MISMATCHED\x10\x052\xde\x01\n" +
	"\x03TSO\x122\n" +
	"\x03Tso\x12\x11.tsopb.TsoRequest\x1a\x12.tsopb.TsoResponse\"\x00(\x010\x01\x12d\n" +
	"\x15FindGroupByKeyspaceID\x12#.tsopb.FindGroupByKeyspaceIDRequest\x1a$.tsopb.FindGroupByKeyspaceIDResponse\"\x00\x12=\n" +
	"\bGetMinTS\x12\x16.tsopb.GetMinTSRequest\x1a\x17.tsopb.GetMinTSResponse\"\x00B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_tsopb_proto_rawDescOnce sync.Once
	file_tsopb_proto_rawDescData []byte
)

func file_tsopb_proto_rawDescGZIP() []byte {
	file_tsopb_proto_rawDescOnce.Do(func() {
		file_tsopb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsopb_proto_rawDesc), len(file_tsopb_proto_rawDesc)))
	})
	return file_tsopb_proto_rawDescData
}

var file_tsopb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tsopb_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tsopb_proto_goTypes = []any{
	(ErrorType)(0),                        // 0: tsopb.ErrorType
	(*RequestHeader)(nil),                 // 1: tsopb.RequestHeader
	(*ResponseHeader)(nil),                // 2: tsopb.ResponseHeader
	(*Error)(nil),                         // 3: tsopb.Error
	(*TsoRequest)(nil),                    // 4: tsopb.TsoRequest
	(*TsoResponse)(nil),                   // 5: tsopb.TsoResponse
	(*Participant)(nil),                   // 6: tsopb.Participant
	(*KeyspaceGroupMember)(nil),           // 7: tsopb.KeyspaceGroupMember
	(*SplitState)(nil),                    // 8: tsopb.SplitState
	(*KeyspaceGroup)(nil),                 // 9: tsopb.KeyspaceGroup
	(*FindGroupByKeyspaceIDRequest)(nil),  // 10: tsopb.FindGroupByKeyspaceIDRequest
	(*FindGroupByKeyspaceIDResponse)(nil), // 11: tsopb.FindGroupByKeyspaceIDResponse
	(*GetMinTSRequest)(nil),               // 12: tsopb.GetMinTSRequest
	(*GetMinTSResponse)(nil),              // 13: tsopb.GetMinTSResponse
	(*pdpb.Timestamp)(nil),                // 14: pdpb.Timestamp
}
var file_tsopb_proto_depIdxs = []int32{
	3,  // 0: tsopb.ResponseHeader.error:type_name -> tsopb.Error
	0,  // 1: tsopb.Error.type:type_name -> tsopb.ErrorType
	1,  // 2: tsopb.TsoRequest.header:type_name -> tsopb.RequestHeader
	2,  // 3: tsopb.TsoResponse.header:type_name -> tsopb.ResponseHeader
	14, // 4: tsopb.TsoResponse.timestamp:type_name -> pdpb.Timestamp
	8,  // 5: tsopb.KeyspaceGroup.split_state:type_name -> tsopb.SplitState
	7,  // 6: tsopb.KeyspaceGroup.members:type_name -> tsopb.KeyspaceGroupMember
	1,  // 7: tsopb.FindGroupByKeyspaceIDRequest.header:type_name -> tsopb.RequestHeader
	2,  // 8: tsopb.FindGroupByKeyspaceIDResponse.header:type_name -> tsopb.ResponseHeader
	9,  // 9: tsopb.FindGroupByKeyspaceIDResponse.keyspace_group:type_name -> tsopb.KeyspaceGroup
	1,  // 10: tsopb.GetMinTSRequest.header:type_name -> tsopb.RequestHeader
	2,  // 11: tsopb.GetMinTSResponse.header:type_name -> tsopb.ResponseHeader
	14, // 12: tsopb.GetMinTSResponse.timestamp:type_name -> pdpb.Timestamp
	4,  // 13: tsopb.TSO.Tso:input_type -> tsopb.TsoRequest
	10, // 14: tsopb.TSO.FindGroupByKeyspaceID:input_type -> tsopb.FindGroupByKeyspaceIDRequest
	12, // 15: tsopb.TSO.GetMinTS:input_type -> tsopb.GetMinTSRequest
	5,  // 16: tsopb.TSO.Tso:output_type -> tsopb.TsoResponse
	11, // 17: tsopb.TSO.FindGroupByKeyspaceID:output_type -> tsopb.FindGroupByKeyspaceIDResponse
	13, // 18: tsopb.TSO.GetMinTS:output_type -> tsopb.GetMinTSResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tsopb_proto_init() }
func file_tsopb_proto_init() {
	if File_tsopb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsopb_proto_rawDesc), len(file_tsopb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsopb_proto_goTypes,
		DependencyIndexes: file_tsopb_proto_depIdxs,
		EnumInfos:         file_tsopb_proto_enumTypes,
		MessageInfos:      file_tsopb_proto_msgTypes,
	}.Build()
	File_tsopb_proto = out.File
	file_tsopb_proto_goTypes = nil
	file_tsopb_proto_depIdxs = nil
}
