// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: metapb.proto

package metapb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	encryptionpb "github.com/pingcap/kvproto/pkg/encryptionpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreState int32

const (
	StoreState_Up        StoreState = 0
	StoreState_Offline   StoreState = 1
	StoreState_Tombstone StoreState = 2
)

// Enum value maps for StoreState.
var (
	StoreState_name = map[int32]string{
		0: "Up",
		1: "Offline",
		2: "Tombstone",
	}
	StoreState_value = map[string]int32{
		"Up":        0,
		"Offline":   1,
		"Tombstone": 2,
	}
)

func (x StoreState) Enum() *StoreState {
	p := new(StoreState)
	*p = x
	return p
}

func (x StoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_metapb_proto_enumTypes[0].Descriptor()
}

func (StoreState) Type() protoreflect.EnumType {
	return &file_metapb_proto_enumTypes[0]
}

func (x StoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreState.Descriptor instead.
func (StoreState) EnumDescriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{0}
}

// NodeState is going to replace StoreState to make the state concept more clear.
// "Up" is devided into "Preparing" and "Serving" stages so that we can better describe the online process.
// "Removing" is just like previous `Offline` which is more accurate.
// "Removed" has the same meaning with `Tombstone`.
type NodeState int32

const (
	NodeState_Preparing NodeState = 0
	NodeState_Serving   NodeState = 1
	NodeState_Removing  NodeState = 2
	NodeState_Removed   NodeState = 3
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "Preparing",
		1: "Serving",
		2: "Removing",
		3: "Removed",
	}
	NodeState_value = map[string]int32{
		"Preparing": 0,
		"Serving":   1,
		"Removing":  2,
		"Removed":   3,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_metapb_proto_enumTypes[1].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_metapb_proto_enumTypes[1]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{1}
}

type PeerRole int32

const (
	// Voter -> Voter
	PeerRole_Voter PeerRole = 0
	// Learner/None -> Learner
	PeerRole_Learner PeerRole = 1
	// Learner/None -> Voter
	PeerRole_IncomingVoter PeerRole = 2
	// Voter -> Learner
	PeerRole_DemotingVoter PeerRole = 3
)

// Enum value maps for PeerRole.
var (
	PeerRole_name = map[int32]string{
		0: "Voter",
		1: "Learner",
		2: "IncomingVoter",
		3: "DemotingVoter",
	}
	PeerRole_value = map[string]int32{
		"Voter":         0,
		"Learner":       1,
		"IncomingVoter": 2,
		"DemotingVoter": 3,
	}
)

func (x PeerRole) Enum() *PeerRole {
	p := new(PeerRole)
	*p = x
	return p
}

func (x PeerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_metapb_proto_enumTypes[2].Descriptor()
}

func (PeerRole) Type() protoreflect.EnumType {
	return &file_metapb_proto_enumTypes[2]
}

func (x PeerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerRole.Descriptor instead.
func (PeerRole) EnumDescriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{2}
}

type Cluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// max peer count for a region.
	// pd will do the auto-balance if region peer count mismatches.
	MaxPeerCount  uint32 `protobuf:"varint,2,opt,name=max_peer_count,json=maxPeerCount,proto3" json:"max_peer_count,omitempty"` // more attributes......
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_metapb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cluster) GetMaxPeerCount() uint32 {
	if x != nil {
		return x.MaxPeerCount
	}
	return 0
}

// Case insensitive key/value for replica constraints.
type StoreLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreLabel) Reset() {
	*x = StoreLabel{}
	mi := &file_metapb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreLabel) ProtoMessage() {}

func (x *StoreLabel) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreLabel.ProtoReflect.Descriptor instead.
func (*StoreLabel) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{1}
}

func (x *StoreLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Store struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Address to handle client requests (kv, cop, etc.)
	Address string        `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	State   StoreState    `protobuf:"varint,3,opt,name=state,proto3,enum=metapb.StoreState" json:"state,omitempty"`
	Labels  []*StoreLabel `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Version string        `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Address to handle peer requests (raft messages from other store).
	// Empty means same as address.
	PeerAddress string `protobuf:"bytes,6,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	// Status address provides the HTTP service for external components
	StatusAddress string `protobuf:"bytes,7,opt,name=status_address,json=statusAddress,proto3" json:"status_address,omitempty"`
	GitHash       string `protobuf:"bytes,8,opt,name=git_hash,json=gitHash,proto3" json:"git_hash,omitempty"`
	// The start timestamp of the current store
	StartTimestamp int64  `protobuf:"varint,9,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	DeployPath     string `protobuf:"bytes,10,opt,name=deploy_path,json=deployPath,proto3" json:"deploy_path,omitempty"`
	// The last heartbeat timestamp of the store.
	LastHeartbeat int64 `protobuf:"varint,11,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// If the store is physically destroyed, which means it can never up again.
	PhysicallyDestroyed bool `protobuf:"varint,12,opt,name=physically_destroyed,json=physicallyDestroyed,proto3" json:"physically_destroyed,omitempty"`
	// NodeState is used to replace StoreState which will be deprecated in the future.
	NodeState     NodeState `protobuf:"varint,13,opt,name=node_state,json=nodeState,proto3,enum=metapb.NodeState" json:"node_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_metapb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Store) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Store) GetState() StoreState {
	if x != nil {
		return x.State
	}
	return StoreState_Up
}

func (x *Store) GetLabels() []*StoreLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Store) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Store) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *Store) GetStatusAddress() string {
	if x != nil {
		return x.StatusAddress
	}
	return ""
}

func (x *Store) GetGitHash() string {
	if x != nil {
		return x.GitHash
	}
	return ""
}

func (x *Store) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Store) GetDeployPath() string {
	if x != nil {
		return x.DeployPath
	}
	return ""
}

func (x *Store) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *Store) GetPhysicallyDestroyed() bool {
	if x != nil {
		return x.PhysicallyDestroyed
	}
	return false
}

func (x *Store) GetNodeState() NodeState {
	if x != nil {
		return x.NodeState
	}
	return NodeState_Preparing
}

type RegionEpoch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Conf change version, auto increment when add or remove peer
	ConfVer uint64 `protobuf:"varint,1,opt,name=conf_ver,json=confVer,proto3" json:"conf_ver,omitempty"`
	// Region version, auto increment when split or merge
	Version       uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionEpoch) Reset() {
	*x = RegionEpoch{}
	mi := &file_metapb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionEpoch) ProtoMessage() {}

func (x *RegionEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionEpoch.ProtoReflect.Descriptor instead.
func (*RegionEpoch) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{3}
}

func (x *RegionEpoch) GetConfVer() uint64 {
	if x != nil {
		return x.ConfVer
	}
	return 0
}

func (x *RegionEpoch) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BucketStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total read in bytes of each bucket
	ReadBytes []uint64 `protobuf:"varint,1,rep,packed,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	// total write in bytes of each bucket
	WriteBytes []uint64 `protobuf:"varint,2,rep,packed,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	// total read qps of each bucket
	ReadQps []uint64 `protobuf:"varint,3,rep,packed,name=read_qps,json=readQps,proto3" json:"read_qps,omitempty"`
	// total write qps of each bucket
	WriteQps []uint64 `protobuf:"varint,4,rep,packed,name=write_qps,json=writeQps,proto3" json:"write_qps,omitempty"`
	// total read keys of each bucket
	ReadKeys []uint64 `protobuf:"varint,5,rep,packed,name=read_keys,json=readKeys,proto3" json:"read_keys,omitempty"`
	// total write keys of each bucket
	WriteKeys     []uint64 `protobuf:"varint,6,rep,packed,name=write_keys,json=writeKeys,proto3" json:"write_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketStats) Reset() {
	*x = BucketStats{}
	mi := &file_metapb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketStats) ProtoMessage() {}

func (x *BucketStats) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketStats.ProtoReflect.Descriptor instead.
func (*BucketStats) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{4}
}

func (x *BucketStats) GetReadBytes() []uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return nil
}

func (x *BucketStats) GetWriteBytes() []uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return nil
}

func (x *BucketStats) GetReadQps() []uint64 {
	if x != nil {
		return x.ReadQps
	}
	return nil
}

func (x *BucketStats) GetWriteQps() []uint64 {
	if x != nil {
		return x.WriteQps
	}
	return nil
}

func (x *BucketStats) GetReadKeys() []uint64 {
	if x != nil {
		return x.ReadKeys
	}
	return nil
}

func (x *BucketStats) GetWriteKeys() []uint64 {
	if x != nil {
		return x.WriteKeys
	}
	return nil
}

type Buckets struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RegionId uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// A hint indicate if keys have changed.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// keys of buckets, include start/end key of region
	Keys [][]byte `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	// bucket stats
	Stats *BucketStats `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	// The period in milliseconds that stats are collected with in
	PeriodInMs    uint64 `protobuf:"varint,5,opt,name=period_in_ms,json=periodInMs,proto3" json:"period_in_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buckets) Reset() {
	*x = Buckets{}
	mi := &file_metapb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buckets) ProtoMessage() {}

func (x *Buckets) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buckets.ProtoReflect.Descriptor instead.
func (*Buckets) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{5}
}

func (x *Buckets) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *Buckets) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Buckets) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Buckets) GetStats() *BucketStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Buckets) GetPeriodInMs() uint64 {
	if x != nil {
		return x.PeriodInMs
	}
	return 0
}

type BucketMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A hint indicate if keys have changed.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// keys of buckets, include start/end key of region
	Keys          [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketMeta) Reset() {
	*x = BucketMeta{}
	mi := &file_metapb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketMeta) ProtoMessage() {}

func (x *BucketMeta) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketMeta.ProtoReflect.Descriptor instead.
func (*BucketMeta) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{6}
}

func (x *BucketMeta) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BucketMeta) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type Region struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Region key range [start_key, end_key).
	StartKey    []byte       `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey      []byte       `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	RegionEpoch *RegionEpoch `protobuf:"bytes,4,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	Peers       []*Peer      `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	// Encryption metadata for start_key and end_key. encryption_meta.iv is IV for start_key.
	// IV for end_key is calculated from (encryption_meta.iv + len(start_key)).
	// The field is only used by PD and should be ignored otherwise.
	// If encryption_meta is empty (i.e. nil), it means start_key and end_key are unencrypted.
	EncryptionMeta *encryptionpb.EncryptionMeta `protobuf:"bytes,6,opt,name=encryption_meta,json=encryptionMeta,proto3" json:"encryption_meta,omitempty"`
	// The flashback state indicates whether this region is in the flashback state.
	// TODO: only check by `flashback_start_ts` in the future. Keep for compatibility now.
	IsInFlashback bool `protobuf:"varint,7,opt,name=is_in_flashback,json=isInFlashback,proto3" json:"is_in_flashback,omitempty"`
	// The start_ts that the current flashback progress is using.
	FlashbackStartTs uint64 `protobuf:"varint,8,opt,name=flashback_start_ts,json=flashbackStartTs,proto3" json:"flashback_start_ts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_metapb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{7}
}

func (x *Region) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Region) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *Region) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *Region) GetRegionEpoch() *RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *Region) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Region) GetEncryptionMeta() *encryptionpb.EncryptionMeta {
	if x != nil {
		return x.EncryptionMeta
	}
	return nil
}

func (x *Region) GetIsInFlashback() bool {
	if x != nil {
		return x.IsInFlashback
	}
	return false
}

func (x *Region) GetFlashbackStartTs() uint64 {
	if x != nil {
		return x.FlashbackStartTs
	}
	return 0
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Role          PeerRole               `protobuf:"varint,3,opt,name=role,proto3,enum=metapb.PeerRole" json:"role,omitempty"`
	IsWitness     bool                   `protobuf:"varint,4,opt,name=is_witness,json=isWitness,proto3" json:"is_witness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_metapb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_metapb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_metapb_proto_rawDescGZIP(), []int{8}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *Peer) GetRole() PeerRole {
	if x != nil {
		return x.Role
	}
	return PeerRole_Voter
}

func (x *Peer) GetIsWitness() bool {
	if x != nil {
		return x.IsWitness
	}
	return false
}

var File_metapb_proto protoreflect.FileDescriptor

const file_metapb_proto_rawDesc = "" +
	"\n" +
	"\fmetapb.proto\x12\x06metapb\x1a\x12encryptionpb.proto\x1a\x0frustproto.proto\"?\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12$\n" +
	"\x0emax_peer_count\x18\x02 \x01(\rR\fmaxPeerCount\"4\n" +
	"\n" +
	"StoreLabel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xdc\x03\n" +
	"\x05Store\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12(\n" +
	"\x05state\x18\x03 \x01(\x0e2\x12.metapb.StoreStateR\x05state\x12*\n" +
	"\x06labels\x18\x04 \x03(\v2\x12.metapb.StoreLabelR\x06labels\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12!\n" +
	"\fpeer_address\x18\x06 \x01(\tR\vpeerAddress\x12%\n" +
	"\x0estatus_address\x18\a \x01(\tR\rstatusAddress\x12\x19\n" +
	"\bgit_hash\x18\b \x01(\tR\agitHash\x12'\n" +
	"\x0fstart_timestamp\x18\t \x01(\x03R\x0estartTimestamp\x12\x1f\n" +
	"\vdeploy_path\x18\n" +
	" \x01(\tR\n" +
	"deployPath\x12%\n" +
	"\x0elast_heartbeat\x18\v \x01(\x03R\rlastHeartbeat\x121\n" +
	"\x14physically_destroyed\x18\f \x01(\bR\x13physicallyDestroyed\x120\n" +
	"\n" +
	"node_state\x18\r \x01(\x0e2\x11.metapb.NodeStateR\tnodeState\"B\n" +
	"\vRegionEpoch\x12\x19\n" +
	"\bconf_ver\x18\x01 \x01(\x04R\aconfVer\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xc1\x01\n" +
	"\vBucketStats\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x01 \x03(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x02 \x03(\x04R\n" +
	"writeBytes\x12\x19\n" +
	"\bread_qps\x18\x03 \x03(\x04R\areadQps\x12\x1b\n" +
	"\twrite_qps\x18\x04 \x03(\x04R\bwriteQps\x12\x1b\n" +
	"\tread_keys\x18\x05 \x03(\x04R\breadKeys\x12\x1d\n" +
	"\n" +
	"write_keys\x18\x06 \x03(\x04R\twriteKeys\"\xa1\x01\n" +
	"\aBuckets\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04keys\x18\x03 \x03(\fR\x04keys\x12)\n" +
	"\x05stats\x18\x04 \x01(\v2\x13.metapb.BucketStatsR\x05stats\x12 \n" +
	"\fperiod_in_ms\x18\x05 \x01(\x04R\n" +
	"periodInMs\":\n" +
	"\n" +
	"BucketMeta\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"\xc7\x02\n" +
	"\x06Region\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tstart_key\x18\x02 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x03 \x01(\fR\x06endKey\x126\n" +
	"\fregion_epoch\x18\x04 \x01(\v2\x13.metapb.RegionEpochR\vregionEpoch\x12\"\n" +
	"\x05peers\x18\x05 \x03(\v2\f.metapb.PeerR\x05peers\x12E\n" +
	"\x0fencryption_meta\x18\x06 \x01(\v2\x1c.encryptionpb.EncryptionMetaR\x0eencryptionMeta\x12&\n" +
	"\x0fis_in_flashback\x18\a \x01(\bR\risInFlashback\x12,\n" +
	"\x12flashback_start_ts\x18\b \x01(\x04R\x10flashbackStartTs\"v\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.metapb.PeerRoleR\x04role\x12\x1d\n" +
	"\n" +
	"is_witness\x18\x04 \x01(\bR\tisWitness*0\n" +
	"\n" +
	"StoreState\x12\x06\n" +
	"\x02Up\x10\x00\x12\v\n" +
	"\aOffline\x10\x01\x12\r\n" +
	"\tTombstone\x10\x02*B\n" +
	"\tNodeState\x12\r\n" +
	"\tPreparing\x10\x00\x12\v\n" +
	"\aServing\x10\x01\x12\f\n" +
	"\bRemoving\x10\x02\x12\v\n" +
	"\aRemoved\x10\x03*H\n" +
	"\bPeerRole\x12\t\n" +
	"\x05Voter\x10\x00\x12\v\n" +
	"\aLearner\x10\x01\x12\x11\n" +
	"\rIncomingVoter\x10\x02\x12\x11\n" +
	"\rDemotingVoter\x10\x03B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_metapb_proto_rawDescOnce sync.Once
	file_metapb_proto_rawDescData []byte
)

func file_metapb_proto_rawDescGZIP() []byte {
	file_metapb_proto_rawDescOnce.Do(func() {
		file_metapb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metapb_proto_rawDesc), len(file_metapb_proto_rawDesc)))
	})
	return file_metapb_proto_rawDescData
}

var file_metapb_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_metapb_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_metapb_proto_goTypes = []any{
	(StoreState)(0),                     // 0: metapb.StoreState
	(NodeState)(0),                      // 1: metapb.NodeState
	(PeerRole)(0),                       // 2: metapb.PeerRole
	(*Cluster)(nil),                     // 3: metapb.Cluster
	(*StoreLabel)(nil),                  // 4: metapb.StoreLabel
	(*Store)(nil),                       // 5: metapb.Store
	(*RegionEpoch)(nil),                 // 6: metapb.RegionEpoch
	(*BucketStats)(nil),                 // 7: metapb.BucketStats
	(*Buckets)(nil),                     // 8: metapb.Buckets
	(*BucketMeta)(nil),                  // 9: metapb.BucketMeta
	(*Region)(nil),                      // 10: metapb.Region
	(*Peer)(nil),                        // 11: metapb.Peer
	(*encryptionpb.EncryptionMeta)(nil), // 12: encryptionpb.EncryptionMeta
}
var file_metapb_proto_depIdxs = []int32{
	0,  // 0: metapb.Store.state:type_name -> metapb.StoreState
	4,  // 1: metapb.Store.labels:type_name -> metapb.StoreLabel
	1,  // 2: metapb.Store.node_state:type_name -> metapb.NodeState
	7,  // 3: metapb.Buckets.stats:type_name -> metapb.BucketStats
	6,  // 4: metapb.Region.region_epoch:type_name -> metapb.RegionEpoch
	11, // 5: metapb.Region.peers:type_name -> metapb.Peer
	12, // 6: metapb.Region.encryption_meta:type_name -> encryptionpb.EncryptionMeta
	2,  // 7: metapb.Peer.role:type_name -> metapb.PeerRole
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_metapb_proto_init() }
func file_metapb_proto_init() {
	if File_metapb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metapb_proto_rawDesc), len(file_metapb_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metapb_proto_goTypes,
		DependencyIndexes: file_metapb_proto_depIdxs,
		EnumInfos:         file_metapb_proto_enumTypes,
		MessageInfos:      file_metapb_proto_msgTypes,
	}.Build()
	File_metapb_proto = out.File
	file_metapb_proto_goTypes = nil
	file_metapb_proto_depIdxs = nil
}
