// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: autoid.proto

package autoid

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbID          int64                  `protobuf:"varint,1,opt,name=dbID,proto3" json:"dbID,omitempty"`
	TblID         int64                  `protobuf:"varint,2,opt,name=tblID,proto3" json:"tblID,omitempty"`
	IsUnsigned    bool                   `protobuf:"varint,3,opt,name=isUnsigned,proto3" json:"isUnsigned,omitempty"`
	N             uint64                 `protobuf:"varint,4,opt,name=n,proto3" json:"n,omitempty"`
	Increment     int64                  `protobuf:"varint,5,opt,name=increment,proto3" json:"increment,omitempty"`
	Offset        int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	KeyspaceID    uint32                 `protobuf:"varint,7,opt,name=keyspaceID,proto3" json:"keyspaceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoIDRequest) Reset() {
	*x = AutoIDRequest{}
	mi := &file_autoid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoIDRequest) ProtoMessage() {}

func (x *AutoIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoIDRequest.ProtoReflect.Descriptor instead.
func (*AutoIDRequest) Descriptor() ([]byte, []int) {
	return file_autoid_proto_rawDescGZIP(), []int{0}
}

func (x *AutoIDRequest) GetDbID() int64 {
	if x != nil {
		return x.DbID
	}
	return 0
}

func (x *AutoIDRequest) GetTblID() int64 {
	if x != nil {
		return x.TblID
	}
	return 0
}

func (x *AutoIDRequest) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

func (x *AutoIDRequest) GetN() uint64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *AutoIDRequest) GetIncrement() int64 {
	if x != nil {
		return x.Increment
	}
	return 0
}

func (x *AutoIDRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AutoIDRequest) GetKeyspaceID() uint32 {
	if x != nil {
		return x.KeyspaceID
	}
	return 0
}

type AutoIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int64                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Errmsg        []byte                 `protobuf:"bytes,3,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoIDResponse) Reset() {
	*x = AutoIDResponse{}
	mi := &file_autoid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoIDResponse) ProtoMessage() {}

func (x *AutoIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoIDResponse.ProtoReflect.Descriptor instead.
func (*AutoIDResponse) Descriptor() ([]byte, []int) {
	return file_autoid_proto_rawDescGZIP(), []int{1}
}

func (x *AutoIDResponse) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AutoIDResponse) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AutoIDResponse) GetErrmsg() []byte {
	if x != nil {
		return x.Errmsg
	}
	return nil
}

type RebaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbID          int64                  `protobuf:"varint,1,opt,name=dbID,proto3" json:"dbID,omitempty"`
	TblID         int64                  `protobuf:"varint,2,opt,name=tblID,proto3" json:"tblID,omitempty"`
	IsUnsigned    bool                   `protobuf:"varint,3,opt,name=isUnsigned,proto3" json:"isUnsigned,omitempty"`
	Base          int64                  `protobuf:"varint,4,opt,name=base,proto3" json:"base,omitempty"`
	Force         bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebaseRequest) Reset() {
	*x = RebaseRequest{}
	mi := &file_autoid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseRequest) ProtoMessage() {}

func (x *RebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseRequest.ProtoReflect.Descriptor instead.
func (*RebaseRequest) Descriptor() ([]byte, []int) {
	return file_autoid_proto_rawDescGZIP(), []int{2}
}

func (x *RebaseRequest) GetDbID() int64 {
	if x != nil {
		return x.DbID
	}
	return 0
}

func (x *RebaseRequest) GetTblID() int64 {
	if x != nil {
		return x.TblID
	}
	return 0
}

func (x *RebaseRequest) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

func (x *RebaseRequest) GetBase() int64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *RebaseRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RebaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errmsg        []byte                 `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebaseResponse) Reset() {
	*x = RebaseResponse{}
	mi := &file_autoid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseResponse) ProtoMessage() {}

func (x *RebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseResponse.ProtoReflect.Descriptor instead.
func (*RebaseResponse) Descriptor() ([]byte, []int) {
	return file_autoid_proto_rawDescGZIP(), []int{3}
}

func (x *RebaseResponse) GetErrmsg() []byte {
	if x != nil {
		return x.Errmsg
	}
	return nil
}

var File_autoid_proto protoreflect.FileDescriptor

const file_autoid_proto_rawDesc = "" +
	"\n" +
	"\fautoid.proto\x12\x06autoid\x1a\x0frustproto.proto\"\xbd\x01\n" +
	"\rAutoIDRequest\x12\x12\n" +
	"\x04dbID\x18\x01 \x01(\x03R\x04dbID\x12\x14\n" +
	"\x05tblID\x18\x02 \x01(\x03R\x05tblID\x12\x1e\n" +
	"\n" +
	"isUnsigned\x18\x03 \x01(\bR\n" +
	"isUnsigned\x12\f\n" +
	"\x01n\x18\x04 \x01(\x04R\x01n\x12\x1c\n" +
	"\tincrement\x18\x05 \x01(\x03R\tincrement\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\x12\x1e\n" +
	"\n" +
	"keyspaceID\x18\a \x01(\rR\n" +
	"keyspaceID\"L\n" +
	"\x0eAutoIDResponse\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x03R\x03max\x12\x16\n" +
	"\x06errmsg\x18\x03 \x01(\fR\x06errmsg\"\x83\x01\n" +
	"\rRebaseRequest\x12\x12\n" +
	"\x04dbID\x18\x01 \x01(\x03R\x04dbID\x12\x14\n" +
	"\x05tblID\x18\x02 \x01(\x03R\x05tblID\x12\x1e\n" +
	"\n" +
	"isUnsigned\x18\x03 \x01(\bR\n" +
	"isUnsigned\x12\x12\n" +
	"\x04base\x18\x04 \x01(\x03R\x04base\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\"(\n" +
	"\x0eRebaseResponse\x12\x16\n" +
	"\x06errmsg\x18\x01 \x01(\fR\x06errmsg2\x88\x01\n" +
	"\vAutoIDAlloc\x12>\n" +
	"\vAllocAutoID\x12\x15.autoid.AutoIDRequest\x1a\x16.autoid.AutoIDResponse\"\x00\x129\n" +
	"\x06Rebase\x12\x15.autoid.RebaseRequest\x1a\x16.autoid.RebaseResponse\"\x00B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_autoid_proto_rawDescOnce sync.Once
	file_autoid_proto_rawDescData []byte
)

func file_autoid_proto_rawDescGZIP() []byte {
	file_autoid_proto_rawDescOnce.Do(func() {
		file_autoid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autoid_proto_rawDesc), len(file_autoid_proto_rawDesc)))
	})
	return file_autoid_proto_rawDescData
}

var file_autoid_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_autoid_proto_goTypes = []any{
	(*AutoIDRequest)(nil),  // 0: autoid.AutoIDRequest
	(*AutoIDResponse)(nil), // 1: autoid.AutoIDResponse
	(*RebaseRequest)(nil),  // 2: autoid.RebaseRequest
	(*RebaseResponse)(nil), // 3: autoid.RebaseResponse
}
var file_autoid_proto_depIdxs = []int32{
	0, // 0: autoid.AutoIDAlloc.AllocAutoID:input_type -> autoid.AutoIDRequest
	2, // 1: autoid.AutoIDAlloc.Rebase:input_type -> autoid.RebaseRequest
	1, // 2: autoid.AutoIDAlloc.AllocAutoID:output_type -> autoid.AutoIDResponse
	3, // 3: autoid.AutoIDAlloc.Rebase:output_type -> autoid.RebaseResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_autoid_proto_init() }
func file_autoid_proto_init() {
	if File_autoid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autoid_proto_rawDesc), len(file_autoid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autoid_proto_goTypes,
		DependencyIndexes: file_autoid_proto_depIdxs,
		MessageInfos:      file_autoid_proto_msgTypes,
	}.Build()
	File_autoid_proto = out.File
	file_autoid_proto_goTypes = nil
	file_autoid_proto_depIdxs = nil
}
