// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: debugpb.proto

package debugpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	eraftpb "github.com/pingcap/kvproto/pkg/eraftpb"
	kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"
	raft_serverpb "github.com/pingcap/kvproto/pkg/raft_serverpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DB int32

const (
	DB_INVALID DB = 0
	DB_KV      DB = 1
	DB_RAFT    DB = 2
)

// Enum value maps for DB.
var (
	DB_name = map[int32]string{
		0: "INVALID",
		1: "KV",
		2: "RAFT",
	}
	DB_value = map[string]int32{
		"INVALID": 0,
		"KV":      1,
		"RAFT":    2,
	}
)

func (x DB) Enum() *DB {
	p := new(DB)
	*p = x
	return p
}

func (x DB) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DB) Descriptor() protoreflect.EnumDescriptor {
	return file_debugpb_proto_enumTypes[0].Descriptor()
}

func (DB) Type() protoreflect.EnumType {
	return &file_debugpb_proto_enumTypes[0]
}

func (x DB) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DB.Descriptor instead.
func (DB) EnumDescriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{0}
}

type MODULE int32

const (
	MODULE_UNUSED      MODULE = 0
	MODULE_KVDB        MODULE = 1
	MODULE_RAFTDB      MODULE = 2
	MODULE_READPOOL    MODULE = 3
	MODULE_SERVER      MODULE = 4
	MODULE_STORAGE     MODULE = 5
	MODULE_PD          MODULE = 6
	MODULE_METRIC      MODULE = 7
	MODULE_COPROCESSOR MODULE = 8
	MODULE_SECURITY    MODULE = 9
	MODULE_IMPORT      MODULE = 10
)

// Enum value maps for MODULE.
var (
	MODULE_name = map[int32]string{
		0:  "UNUSED",
		1:  "KVDB",
		2:  "RAFTDB",
		3:  "READPOOL",
		4:  "SERVER",
		5:  "STORAGE",
		6:  "PD",
		7:  "METRIC",
		8:  "COPROCESSOR",
		9:  "SECURITY",
		10: "IMPORT",
	}
	MODULE_value = map[string]int32{
		"UNUSED":      0,
		"KVDB":        1,
		"RAFTDB":      2,
		"READPOOL":    3,
		"SERVER":      4,
		"STORAGE":     5,
		"PD":          6,
		"METRIC":      7,
		"COPROCESSOR": 8,
		"SECURITY":    9,
		"IMPORT":      10,
	}
)

func (x MODULE) Enum() *MODULE {
	p := new(MODULE)
	*p = x
	return p
}

func (x MODULE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MODULE) Descriptor() protoreflect.EnumDescriptor {
	return file_debugpb_proto_enumTypes[1].Descriptor()
}

func (MODULE) Type() protoreflect.EnumType {
	return &file_debugpb_proto_enumTypes[1]
}

func (x MODULE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MODULE.Descriptor instead.
func (MODULE) EnumDescriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{1}
}

type BottommostLevelCompaction int32

const (
	// Skip bottommost level compaction
	BottommostLevelCompaction_Skip BottommostLevelCompaction = 0
	// Force bottommost level compaction
	BottommostLevelCompaction_Force BottommostLevelCompaction = 1
	// Compact bottommost level if there is a compaction filter.
	BottommostLevelCompaction_IfHaveCompactionFilter BottommostLevelCompaction = 2
)

// Enum value maps for BottommostLevelCompaction.
var (
	BottommostLevelCompaction_name = map[int32]string{
		0: "Skip",
		1: "Force",
		2: "IfHaveCompactionFilter",
	}
	BottommostLevelCompaction_value = map[string]int32{
		"Skip":                   0,
		"Force":                  1,
		"IfHaveCompactionFilter": 2,
	}
)

func (x BottommostLevelCompaction) Enum() *BottommostLevelCompaction {
	p := new(BottommostLevelCompaction)
	*p = x
	return p
}

func (x BottommostLevelCompaction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BottommostLevelCompaction) Descriptor() protoreflect.EnumDescriptor {
	return file_debugpb_proto_enumTypes[2].Descriptor()
}

func (BottommostLevelCompaction) Type() protoreflect.EnumType {
	return &file_debugpb_proto_enumTypes[2]
}

func (x BottommostLevelCompaction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BottommostLevelCompaction.Descriptor instead.
func (BottommostLevelCompaction) EnumDescriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{2}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            DB                     `protobuf:"varint,1,opt,name=db,proto3,enum=debugpb.DB" json:"db,omitempty"`
	Cf            string                 `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_debugpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetDb() DB {
	if x != nil {
		return x.Db
	}
	return DB_INVALID
}

func (x *GetRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_debugpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RaftLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	LogIndex      uint64                 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLogRequest) Reset() {
	*x = RaftLogRequest{}
	mi := &file_debugpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLogRequest) ProtoMessage() {}

func (x *RaftLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLogRequest.ProtoReflect.Descriptor instead.
func (*RaftLogRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{2}
}

func (x *RaftLogRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RaftLogRequest) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

type RaftLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *eraftpb.Entry         `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftLogResponse) Reset() {
	*x = RaftLogResponse{}
	mi := &file_debugpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLogResponse) ProtoMessage() {}

func (x *RaftLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLogResponse.ProtoReflect.Descriptor instead.
func (*RaftLogResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{3}
}

func (x *RaftLogResponse) GetEntry() *eraftpb.Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RegionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionInfoRequest) Reset() {
	*x = RegionInfoRequest{}
	mi := &file_debugpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfoRequest) ProtoMessage() {}

func (x *RegionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfoRequest.ProtoReflect.Descriptor instead.
func (*RegionInfoRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{4}
}

func (x *RegionInfoRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type RegionInfoResponse struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	RaftLocalState   *raft_serverpb.RaftLocalState   `protobuf:"bytes,1,opt,name=raft_local_state,json=raftLocalState,proto3" json:"raft_local_state,omitempty"`
	RaftApplyState   *raft_serverpb.RaftApplyState   `protobuf:"bytes,2,opt,name=raft_apply_state,json=raftApplyState,proto3" json:"raft_apply_state,omitempty"`
	RegionLocalState *raft_serverpb.RegionLocalState `protobuf:"bytes,3,opt,name=region_local_state,json=regionLocalState,proto3" json:"region_local_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegionInfoResponse) Reset() {
	*x = RegionInfoResponse{}
	mi := &file_debugpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfoResponse) ProtoMessage() {}

func (x *RegionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfoResponse.ProtoReflect.Descriptor instead.
func (*RegionInfoResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{5}
}

func (x *RegionInfoResponse) GetRaftLocalState() *raft_serverpb.RaftLocalState {
	if x != nil {
		return x.RaftLocalState
	}
	return nil
}

func (x *RegionInfoResponse) GetRaftApplyState() *raft_serverpb.RaftApplyState {
	if x != nil {
		return x.RaftApplyState
	}
	return nil
}

func (x *RegionInfoResponse) GetRegionLocalState() *raft_serverpb.RegionLocalState {
	if x != nil {
		return x.RegionLocalState
	}
	return nil
}

type RegionSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Cfs           []string               `protobuf:"bytes,2,rep,name=cfs,proto3" json:"cfs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSizeRequest) Reset() {
	*x = RegionSizeRequest{}
	mi := &file_debugpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSizeRequest) ProtoMessage() {}

func (x *RegionSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSizeRequest.ProtoReflect.Descriptor instead.
func (*RegionSizeRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{6}
}

func (x *RegionSizeRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RegionSizeRequest) GetCfs() []string {
	if x != nil {
		return x.Cfs
	}
	return nil
}

type RegionSizeResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entries       []*RegionSizeResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSizeResponse) Reset() {
	*x = RegionSizeResponse{}
	mi := &file_debugpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSizeResponse) ProtoMessage() {}

func (x *RegionSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSizeResponse.ProtoReflect.Descriptor instead.
func (*RegionSizeResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{7}
}

func (x *RegionSizeResponse) GetEntries() []*RegionSizeResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ScanMvccRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromKey       []byte                 `protobuf:"bytes,1,opt,name=from_key,json=fromKey,proto3" json:"from_key,omitempty"`
	ToKey         []byte                 `protobuf:"bytes,2,opt,name=to_key,json=toKey,proto3" json:"to_key,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanMvccRequest) Reset() {
	*x = ScanMvccRequest{}
	mi := &file_debugpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanMvccRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMvccRequest) ProtoMessage() {}

func (x *ScanMvccRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMvccRequest.ProtoReflect.Descriptor instead.
func (*ScanMvccRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{8}
}

func (x *ScanMvccRequest) GetFromKey() []byte {
	if x != nil {
		return x.FromKey
	}
	return nil
}

func (x *ScanMvccRequest) GetToKey() []byte {
	if x != nil {
		return x.ToKey
	}
	return nil
}

func (x *ScanMvccRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ScanMvccResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Info          *kvrpcpb.MvccInfo      `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanMvccResponse) Reset() {
	*x = ScanMvccResponse{}
	mi := &file_debugpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanMvccResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanMvccResponse) ProtoMessage() {}

func (x *ScanMvccResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanMvccResponse.ProtoReflect.Descriptor instead.
func (*ScanMvccResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{9}
}

func (x *ScanMvccResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScanMvccResponse) GetInfo() *kvrpcpb.MvccInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CompactRequest struct {
	state                     protoimpl.MessageState    `protogen:"open.v1"`
	Db                        DB                        `protobuf:"varint,1,opt,name=db,proto3,enum=debugpb.DB" json:"db,omitempty"`
	Cf                        string                    `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	FromKey                   []byte                    `protobuf:"bytes,3,opt,name=from_key,json=fromKey,proto3" json:"from_key,omitempty"`
	ToKey                     []byte                    `protobuf:"bytes,4,opt,name=to_key,json=toKey,proto3" json:"to_key,omitempty"`
	Threads                   uint32                    `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	BottommostLevelCompaction BottommostLevelCompaction `protobuf:"varint,6,opt,name=bottommost_level_compaction,json=bottommostLevelCompaction,proto3,enum=debugpb.BottommostLevelCompaction" json:"bottommost_level_compaction,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_debugpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{10}
}

func (x *CompactRequest) GetDb() DB {
	if x != nil {
		return x.Db
	}
	return DB_INVALID
}

func (x *CompactRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *CompactRequest) GetFromKey() []byte {
	if x != nil {
		return x.FromKey
	}
	return nil
}

func (x *CompactRequest) GetToKey() []byte {
	if x != nil {
		return x.ToKey
	}
	return nil
}

func (x *CompactRequest) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CompactRequest) GetBottommostLevelCompaction() BottommostLevelCompaction {
	if x != nil {
		return x.BottommostLevelCompaction
	}
	return BottommostLevelCompaction_Skip
}

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_debugpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{11}
}

type InjectFailPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Actions       string                 `protobuf:"bytes,2,opt,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFailPointRequest) Reset() {
	*x = InjectFailPointRequest{}
	mi := &file_debugpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFailPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFailPointRequest) ProtoMessage() {}

func (x *InjectFailPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFailPointRequest.ProtoReflect.Descriptor instead.
func (*InjectFailPointRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{12}
}

func (x *InjectFailPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InjectFailPointRequest) GetActions() string {
	if x != nil {
		return x.Actions
	}
	return ""
}

type InjectFailPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFailPointResponse) Reset() {
	*x = InjectFailPointResponse{}
	mi := &file_debugpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFailPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFailPointResponse) ProtoMessage() {}

func (x *InjectFailPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFailPointResponse.ProtoReflect.Descriptor instead.
func (*InjectFailPointResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{13}
}

type RecoverFailPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverFailPointRequest) Reset() {
	*x = RecoverFailPointRequest{}
	mi := &file_debugpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverFailPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverFailPointRequest) ProtoMessage() {}

func (x *RecoverFailPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverFailPointRequest.ProtoReflect.Descriptor instead.
func (*RecoverFailPointRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{14}
}

func (x *RecoverFailPointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RecoverFailPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverFailPointResponse) Reset() {
	*x = RecoverFailPointResponse{}
	mi := &file_debugpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverFailPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverFailPointResponse) ProtoMessage() {}

func (x *RecoverFailPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverFailPointResponse.ProtoReflect.Descriptor instead.
func (*RecoverFailPointResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{15}
}

type ListFailPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFailPointsRequest) Reset() {
	*x = ListFailPointsRequest{}
	mi := &file_debugpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFailPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFailPointsRequest) ProtoMessage() {}

func (x *ListFailPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFailPointsRequest.ProtoReflect.Descriptor instead.
func (*ListFailPointsRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{16}
}

type ListFailPointsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Entries       []*ListFailPointsResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFailPointsResponse) Reset() {
	*x = ListFailPointsResponse{}
	mi := &file_debugpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFailPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFailPointsResponse) ProtoMessage() {}

func (x *ListFailPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFailPointsResponse.ProtoReflect.Descriptor instead.
func (*ListFailPointsResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{17}
}

func (x *ListFailPointsResponse) GetEntries() []*ListFailPointsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_debugpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{18}
}

func (x *GetMetricsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prometheus    string                 `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	RocksdbKv     string                 `protobuf:"bytes,2,opt,name=rocksdb_kv,json=rocksdbKv,proto3" json:"rocksdb_kv,omitempty"`
	RocksdbRaft   string                 `protobuf:"bytes,3,opt,name=rocksdb_raft,json=rocksdbRaft,proto3" json:"rocksdb_raft,omitempty"`
	Jemalloc      string                 `protobuf:"bytes,4,opt,name=jemalloc,proto3" json:"jemalloc,omitempty"`
	StoreId       uint64                 `protobuf:"varint,5,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_debugpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{19}
}

func (x *GetMetricsResponse) GetPrometheus() string {
	if x != nil {
		return x.Prometheus
	}
	return ""
}

func (x *GetMetricsResponse) GetRocksdbKv() string {
	if x != nil {
		return x.RocksdbKv
	}
	return ""
}

func (x *GetMetricsResponse) GetRocksdbRaft() string {
	if x != nil {
		return x.RocksdbRaft
	}
	return ""
}

func (x *GetMetricsResponse) GetJemalloc() string {
	if x != nil {
		return x.Jemalloc
	}
	return ""
}

func (x *GetMetricsResponse) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type RegionConsistencyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionConsistencyCheckRequest) Reset() {
	*x = RegionConsistencyCheckRequest{}
	mi := &file_debugpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionConsistencyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionConsistencyCheckRequest) ProtoMessage() {}

func (x *RegionConsistencyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionConsistencyCheckRequest.ProtoReflect.Descriptor instead.
func (*RegionConsistencyCheckRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{20}
}

func (x *RegionConsistencyCheckRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type RegionConsistencyCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionConsistencyCheckResponse) Reset() {
	*x = RegionConsistencyCheckResponse{}
	mi := &file_debugpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionConsistencyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionConsistencyCheckResponse) ProtoMessage() {}

func (x *RegionConsistencyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionConsistencyCheckResponse.ProtoReflect.Descriptor instead.
func (*RegionConsistencyCheckResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{21}
}

type ModifyTikvConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        MODULE                 `protobuf:"varint,1,opt,name=module,proto3,enum=debugpb.MODULE" json:"module,omitempty"`
	ConfigName    string                 `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigValue   string                 `protobuf:"bytes,3,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyTikvConfigRequest) Reset() {
	*x = ModifyTikvConfigRequest{}
	mi := &file_debugpb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyTikvConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTikvConfigRequest) ProtoMessage() {}

func (x *ModifyTikvConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTikvConfigRequest.ProtoReflect.Descriptor instead.
func (*ModifyTikvConfigRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{22}
}

func (x *ModifyTikvConfigRequest) GetModule() MODULE {
	if x != nil {
		return x.Module
	}
	return MODULE_UNUSED
}

func (x *ModifyTikvConfigRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ModifyTikvConfigRequest) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

type ModifyTikvConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyTikvConfigResponse) Reset() {
	*x = ModifyTikvConfigResponse{}
	mi := &file_debugpb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyTikvConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTikvConfigResponse) ProtoMessage() {}

func (x *ModifyTikvConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTikvConfigResponse.ProtoReflect.Descriptor instead.
func (*ModifyTikvConfigResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{23}
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_debugpb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{24}
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetRegionPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionPropertiesRequest) Reset() {
	*x = GetRegionPropertiesRequest{}
	mi := &file_debugpb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionPropertiesRequest) ProtoMessage() {}

func (x *GetRegionPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionPropertiesRequest.ProtoReflect.Descriptor instead.
func (*GetRegionPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{25}
}

func (x *GetRegionPropertiesRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type GetRegionPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Props         []*Property            `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionPropertiesResponse) Reset() {
	*x = GetRegionPropertiesResponse{}
	mi := &file_debugpb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionPropertiesResponse) ProtoMessage() {}

func (x *GetRegionPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionPropertiesResponse.ProtoReflect.Descriptor instead.
func (*GetRegionPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{26}
}

func (x *GetRegionPropertiesResponse) GetProps() []*Property {
	if x != nil {
		return x.Props
	}
	return nil
}

type GetStoreInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreInfoRequest) Reset() {
	*x = GetStoreInfoRequest{}
	mi := &file_debugpb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreInfoRequest) ProtoMessage() {}

func (x *GetStoreInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStoreInfoRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{27}
}

type GetStoreInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	ApiVersion    kvrpcpb.APIVersion     `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3,enum=kvrpcpb.APIVersion" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreInfoResponse) Reset() {
	*x = GetStoreInfoResponse{}
	mi := &file_debugpb_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreInfoResponse) ProtoMessage() {}

func (x *GetStoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{28}
}

func (x *GetStoreInfoResponse) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *GetStoreInfoResponse) GetApiVersion() kvrpcpb.APIVersion {
	if x != nil {
		return x.ApiVersion
	}
	return kvrpcpb.APIVersion(0)
}

type GetClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoRequest) Reset() {
	*x = GetClusterInfoRequest{}
	mi := &file_debugpb_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoRequest) ProtoMessage() {}

func (x *GetClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{29}
}

type GetClusterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoResponse) Reset() {
	*x = GetClusterInfoResponse{}
	mi := &file_debugpb_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoResponse) ProtoMessage() {}

func (x *GetClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*GetClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{30}
}

func (x *GetClusterInfoResponse) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

type GetAllRegionsInStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRegionsInStoreRequest) Reset() {
	*x = GetAllRegionsInStoreRequest{}
	mi := &file_debugpb_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRegionsInStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRegionsInStoreRequest) ProtoMessage() {}

func (x *GetAllRegionsInStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRegionsInStoreRequest.ProtoReflect.Descriptor instead.
func (*GetAllRegionsInStoreRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{31}
}

type GetAllRegionsInStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []uint64               `protobuf:"varint,1,rep,packed,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRegionsInStoreResponse) Reset() {
	*x = GetAllRegionsInStoreResponse{}
	mi := &file_debugpb_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRegionsInStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRegionsInStoreResponse) ProtoMessage() {}

func (x *GetAllRegionsInStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRegionsInStoreResponse.ProtoReflect.Descriptor instead.
func (*GetAllRegionsInStoreResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{32}
}

func (x *GetAllRegionsInStoreResponse) GetRegions() []uint64 {
	if x != nil {
		return x.Regions
	}
	return nil
}

type ResetToVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetToVersionRequest) Reset() {
	*x = ResetToVersionRequest{}
	mi := &file_debugpb_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetToVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetToVersionRequest) ProtoMessage() {}

func (x *ResetToVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetToVersionRequest.ProtoReflect.Descriptor instead.
func (*ResetToVersionRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{33}
}

func (x *ResetToVersionRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type ResetToVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetToVersionResponse) Reset() {
	*x = ResetToVersionResponse{}
	mi := &file_debugpb_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetToVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetToVersionResponse) ProtoMessage() {}

func (x *ResetToVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetToVersionResponse.ProtoReflect.Descriptor instead.
func (*ResetToVersionResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{34}
}

type GetRangePropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangePropertiesRequest) Reset() {
	*x = GetRangePropertiesRequest{}
	mi := &file_debugpb_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangePropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangePropertiesRequest) ProtoMessage() {}

func (x *GetRangePropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangePropertiesRequest.ProtoReflect.Descriptor instead.
func (*GetRangePropertiesRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{35}
}

func (x *GetRangePropertiesRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *GetRangePropertiesRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

type GetRangePropertiesResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Properties    []*GetRangePropertiesResponse_RangeProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangePropertiesResponse) Reset() {
	*x = GetRangePropertiesResponse{}
	mi := &file_debugpb_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangePropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangePropertiesResponse) ProtoMessage() {}

func (x *GetRangePropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangePropertiesResponse.ProtoReflect.Descriptor instead.
func (*GetRangePropertiesResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{36}
}

func (x *GetRangePropertiesResponse) GetProperties() []*GetRangePropertiesResponse_RangeProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type FlashbackToVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *kvrpcpb.Context       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	RegionId      uint64                 `protobuf:"varint,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,4,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,5,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	StartTs       uint64                 `protobuf:"varint,6,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	CommitTs      uint64                 `protobuf:"varint,7,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashbackToVersionRequest) Reset() {
	*x = FlashbackToVersionRequest{}
	mi := &file_debugpb_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashbackToVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashbackToVersionRequest) ProtoMessage() {}

func (x *FlashbackToVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashbackToVersionRequest.ProtoReflect.Descriptor instead.
func (*FlashbackToVersionRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{37}
}

func (x *FlashbackToVersionRequest) GetContext() *kvrpcpb.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *FlashbackToVersionRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FlashbackToVersionRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *FlashbackToVersionRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *FlashbackToVersionRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *FlashbackToVersionRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *FlashbackToVersionRequest) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

type FlashbackToVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashbackToVersionResponse) Reset() {
	*x = FlashbackToVersionResponse{}
	mi := &file_debugpb_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashbackToVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashbackToVersionResponse) ProtoMessage() {}

func (x *FlashbackToVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashbackToVersionResponse.ProtoReflect.Descriptor instead.
func (*FlashbackToVersionResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{38}
}

func (x *FlashbackToVersionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRegionReadProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	LogLocks      bool                   `protobuf:"varint,2,opt,name=log_locks,json=logLocks,proto3" json:"log_locks,omitempty"`         // when set to true, print a log of the locks with min start_ts in the resolver.
	MinStartTs    uint64                 `protobuf:"varint,3,opt,name=min_start_ts,json=minStartTs,proto3" json:"min_start_ts,omitempty"` // only print locks whose start_ts >= min_start_ts. Can be used to find certain transaction.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionReadProgressRequest) Reset() {
	*x = GetRegionReadProgressRequest{}
	mi := &file_debugpb_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionReadProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionReadProgressRequest) ProtoMessage() {}

func (x *GetRegionReadProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionReadProgressRequest.ProtoReflect.Descriptor instead.
func (*GetRegionReadProgressRequest) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{39}
}

func (x *GetRegionReadProgressRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *GetRegionReadProgressRequest) GetLogLocks() bool {
	if x != nil {
		return x.LogLocks
	}
	return false
}

func (x *GetRegionReadProgressRequest) GetMinStartTs() uint64 {
	if x != nil {
		return x.MinStartTs
	}
	return 0
}

type GetRegionReadProgressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// below are from region_read_progress module
	SafeTs                        uint64 `protobuf:"varint,1,opt,name=safe_ts,json=safeTs,proto3" json:"safe_ts,omitempty"`
	AppliedIndex                  uint64 `protobuf:"varint,2,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	PendingFrontAppliedIndex      uint64 `protobuf:"varint,3,opt,name=pending_front_applied_index,json=pendingFrontAppliedIndex,proto3" json:"pending_front_applied_index,omitempty"`
	PendingFrontTs                uint64 `protobuf:"varint,4,opt,name=pending_front_ts,json=pendingFrontTs,proto3" json:"pending_front_ts,omitempty"`
	PendingBackAppliedIndex       uint64 `protobuf:"varint,5,opt,name=pending_back_applied_index,json=pendingBackAppliedIndex,proto3" json:"pending_back_applied_index,omitempty"`
	PendingBackTs                 uint64 `protobuf:"varint,6,opt,name=pending_back_ts,json=pendingBackTs,proto3" json:"pending_back_ts,omitempty"`
	RegionReadProgressPaused      bool   `protobuf:"varint,7,opt,name=region_read_progress_paused,json=regionReadProgressPaused,proto3" json:"region_read_progress_paused,omitempty"`
	DurationToLastUpdateSafeTsMs  uint64 `protobuf:"varint,8,opt,name=duration_to_last_update_safe_ts_ms,json=durationToLastUpdateSafeTsMs,proto3" json:"duration_to_last_update_safe_ts_ms,omitempty"`
	DurationToLastConsumeLeaderMs uint64 `protobuf:"varint,9,opt,name=duration_to_last_consume_leader_ms,json=durationToLastConsumeLeaderMs,proto3" json:"duration_to_last_consume_leader_ms,omitempty"`
	RegionReadProgressExist       bool   `protobuf:"varint,10,opt,name=region_read_progress_exist,json=regionReadProgressExist,proto3" json:"region_read_progress_exist,omitempty"`
	ReadStateTs                   uint64 `protobuf:"varint,18,opt,name=read_state_ts,json=readStateTs,proto3" json:"read_state_ts,omitempty"`
	ReadStateApplyIndex           uint64 `protobuf:"varint,19,opt,name=read_state_apply_index,json=readStateApplyIndex,proto3" json:"read_state_apply_index,omitempty"`
	Discard                       bool   `protobuf:"varint,20,opt,name=discard,proto3" json:"discard,omitempty"`
	// below are from resolved-ts module
	ResolvedTs           uint64 `protobuf:"varint,11,opt,name=resolved_ts,json=resolvedTs,proto3" json:"resolved_ts,omitempty"`
	ResolverTrackedIndex uint64 `protobuf:"varint,12,opt,name=resolver_tracked_index,json=resolverTrackedIndex,proto3" json:"resolver_tracked_index,omitempty"`
	ResolverExist        bool   `protobuf:"varint,13,opt,name=resolver_exist,json=resolverExist,proto3" json:"resolver_exist,omitempty"`
	ResolverStopped      bool   `protobuf:"varint,14,opt,name=resolver_stopped,json=resolverStopped,proto3" json:"resolver_stopped,omitempty"`
	NumLocks             uint64 `protobuf:"varint,16,opt,name=num_locks,json=numLocks,proto3" json:"num_locks,omitempty"`
	NumTransactions      uint64 `protobuf:"varint,17,opt,name=num_transactions,json=numTransactions,proto3" json:"num_transactions,omitempty"`
	Error                string `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetRegionReadProgressResponse) Reset() {
	*x = GetRegionReadProgressResponse{}
	mi := &file_debugpb_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionReadProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionReadProgressResponse) ProtoMessage() {}

func (x *GetRegionReadProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionReadProgressResponse.ProtoReflect.Descriptor instead.
func (*GetRegionReadProgressResponse) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{40}
}

func (x *GetRegionReadProgressResponse) GetSafeTs() uint64 {
	if x != nil {
		return x.SafeTs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetPendingFrontAppliedIndex() uint64 {
	if x != nil {
		return x.PendingFrontAppliedIndex
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetPendingFrontTs() uint64 {
	if x != nil {
		return x.PendingFrontTs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetPendingBackAppliedIndex() uint64 {
	if x != nil {
		return x.PendingBackAppliedIndex
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetPendingBackTs() uint64 {
	if x != nil {
		return x.PendingBackTs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetRegionReadProgressPaused() bool {
	if x != nil {
		return x.RegionReadProgressPaused
	}
	return false
}

func (x *GetRegionReadProgressResponse) GetDurationToLastUpdateSafeTsMs() uint64 {
	if x != nil {
		return x.DurationToLastUpdateSafeTsMs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetDurationToLastConsumeLeaderMs() uint64 {
	if x != nil {
		return x.DurationToLastConsumeLeaderMs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetRegionReadProgressExist() bool {
	if x != nil {
		return x.RegionReadProgressExist
	}
	return false
}

func (x *GetRegionReadProgressResponse) GetReadStateTs() uint64 {
	if x != nil {
		return x.ReadStateTs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetReadStateApplyIndex() uint64 {
	if x != nil {
		return x.ReadStateApplyIndex
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetDiscard() bool {
	if x != nil {
		return x.Discard
	}
	return false
}

func (x *GetRegionReadProgressResponse) GetResolvedTs() uint64 {
	if x != nil {
		return x.ResolvedTs
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetResolverTrackedIndex() uint64 {
	if x != nil {
		return x.ResolverTrackedIndex
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetResolverExist() bool {
	if x != nil {
		return x.ResolverExist
	}
	return false
}

func (x *GetRegionReadProgressResponse) GetResolverStopped() bool {
	if x != nil {
		return x.ResolverStopped
	}
	return false
}

func (x *GetRegionReadProgressResponse) GetNumLocks() uint64 {
	if x != nil {
		return x.NumLocks
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetNumTransactions() uint64 {
	if x != nil {
		return x.NumTransactions
	}
	return 0
}

func (x *GetRegionReadProgressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegionSizeResponse_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cf            string                 `protobuf:"bytes,1,opt,name=cf,proto3" json:"cf,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSizeResponse_Entry) Reset() {
	*x = RegionSizeResponse_Entry{}
	mi := &file_debugpb_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSizeResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSizeResponse_Entry) ProtoMessage() {}

func (x *RegionSizeResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSizeResponse_Entry.ProtoReflect.Descriptor instead.
func (*RegionSizeResponse_Entry) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RegionSizeResponse_Entry) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *RegionSizeResponse_Entry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFailPointsResponse_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Actions       string                 `protobuf:"bytes,2,opt,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFailPointsResponse_Entry) Reset() {
	*x = ListFailPointsResponse_Entry{}
	mi := &file_debugpb_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFailPointsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFailPointsResponse_Entry) ProtoMessage() {}

func (x *ListFailPointsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFailPointsResponse_Entry.ProtoReflect.Descriptor instead.
func (*ListFailPointsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ListFailPointsResponse_Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListFailPointsResponse_Entry) GetActions() string {
	if x != nil {
		return x.Actions
	}
	return ""
}

type GetRangePropertiesResponse_RangeProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangePropertiesResponse_RangeProperty) Reset() {
	*x = GetRangePropertiesResponse_RangeProperty{}
	mi := &file_debugpb_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangePropertiesResponse_RangeProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangePropertiesResponse_RangeProperty) ProtoMessage() {}

func (x *GetRangePropertiesResponse_RangeProperty) ProtoReflect() protoreflect.Message {
	mi := &file_debugpb_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangePropertiesResponse_RangeProperty.ProtoReflect.Descriptor instead.
func (*GetRangePropertiesResponse_RangeProperty) Descriptor() ([]byte, []int) {
	return file_debugpb_proto_rawDescGZIP(), []int{36, 0}
}

func (x *GetRangePropertiesResponse_RangeProperty) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRangePropertiesResponse_RangeProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_debugpb_proto protoreflect.FileDescriptor

const file_debugpb_proto_rawDesc = "" +
	"\n" +
	"\rdebugpb.proto\x12\adebugpb\x1a\reraftpb.proto\x1a\rkvrpcpb.proto\x1a\x13raft_serverpb.proto\x1a\x0frustproto.proto\"K\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\x02db\x18\x01 \x01(\x0e2\v.debugpb.DBR\x02db\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"J\n" +
	"\x0eRaftLogRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tlog_index\x18\x02 \x01(\x04R\blogIndex\"7\n" +
	"\x0fRaftLogResponse\x12$\n" +
	"\x05entry\x18\x01 \x01(\v2\x0e.eraftpb.EntryR\x05entry\"0\n" +
	"\x11RegionInfoRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"\xf5\x01\n" +
	"\x12RegionInfoResponse\x12G\n" +
	"\x10raft_local_state\x18\x01 \x01(\v2\x1d.raft_serverpb.RaftLocalStateR\x0eraftLocalState\x12G\n" +
	"\x10raft_apply_state\x18\x02 \x01(\v2\x1d.raft_serverpb.RaftApplyStateR\x0eraftApplyState\x12M\n" +
	"\x12region_local_state\x18\x03 \x01(\v2\x1f.raft_serverpb.RegionLocalStateR\x10regionLocalState\"B\n" +
	"\x11RegionSizeRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x10\n" +
	"\x03cfs\x18\x02 \x03(\tR\x03cfs\"~\n" +
	"\x12RegionSizeResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.debugpb.RegionSizeResponse.EntryR\aentries\x1a+\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02cf\x18\x01 \x01(\tR\x02cf\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"Y\n" +
	"\x0fScanMvccRequest\x12\x19\n" +
	"\bfrom_key\x18\x01 \x01(\fR\afromKey\x12\x15\n" +
	"\x06to_key\x18\x02 \x01(\fR\x05toKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"K\n" +
	"\x10ScanMvccResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12%\n" +
	"\x04info\x18\x02 \x01(\v2\x11.kvrpcpb.MvccInfoR\x04info\"\xed\x01\n" +
	"\x0eCompactRequest\x12\x1b\n" +
	"\x02db\x18\x01 \x01(\x0e2\v.debugpb.DBR\x02db\x12\x0e\n" +
	"\x02cf\x18\x02 \x01(\tR\x02cf\x12\x19\n" +
	"\bfrom_key\x18\x03 \x01(\fR\afromKey\x12\x15\n" +
	"\x06to_key\x18\x04 \x01(\fR\x05toKey\x12\x18\n" +
	"\athreads\x18\x05 \x01(\rR\athreads\x12b\n" +
	"\x1bbottommost_level_compaction\x18\x06 \x01(\x0e2\".debugpb.BottommostLevelCompactionR\x19bottommostLevelCompaction\"\x11\n" +
	"\x0fCompactResponse\"F\n" +
	"\x16InjectFailPointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aactions\x18\x02 \x01(\tR\aactions\"\x19\n" +
	"\x17InjectFailPointResponse\"-\n" +
	"\x17RecoverFailPointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\x18RecoverFailPointResponse\"\x17\n" +
	"\x15ListFailPointsRequest\"\x90\x01\n" +
	"\x16ListFailPointsResponse\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.debugpb.ListFailPointsResponse.EntryR\aentries\x1a5\n" +
	"\x05Entry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aactions\x18\x02 \x01(\tR\aactions\"%\n" +
	"\x11GetMetricsRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"\xad\x01\n" +
	"\x12GetMetricsResponse\x12\x1e\n" +
	"\n" +
	"prometheus\x18\x01 \x01(\tR\n" +
	"prometheus\x12\x1d\n" +
	"\n" +
	"rocksdb_kv\x18\x02 \x01(\tR\trocksdbKv\x12!\n" +
	"\frocksdb_raft\x18\x03 \x01(\tR\vrocksdbRaft\x12\x1a\n" +
	"\bjemalloc\x18\x04 \x01(\tR\bjemalloc\x12\x19\n" +
	"\bstore_id\x18\x05 \x01(\x04R\astoreId\"<\n" +
	"\x1dRegionConsistencyCheckRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\" \n" +
	"\x1eRegionConsistencyCheckResponse\"\x86\x01\n" +
	"\x17ModifyTikvConfigRequest\x12'\n" +
	"\x06module\x18\x01 \x01(\x0e2\x0f.debugpb.MODULER\x06module\x12\x1f\n" +
	"\vconfig_name\x18\x02 \x01(\tR\n" +
	"configName\x12!\n" +
	"\fconfig_value\x18\x03 \x01(\tR\vconfigValue\"\x1a\n" +
	"\x18ModifyTikvConfigResponse\"4\n" +
	"\bProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"9\n" +
	"\x1aGetRegionPropertiesRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"F\n" +
	"\x1bGetRegionPropertiesResponse\x12'\n" +
	"\x05props\x18\x01 \x03(\v2\x11.debugpb.PropertyR\x05props\"\x15\n" +
	"\x13GetStoreInfoRequest\"g\n" +
	"\x14GetStoreInfoResponse\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x124\n" +
	"\vapi_version\x18\x02 \x01(\x0e2\x13.kvrpcpb.APIVersionR\n" +
	"apiVersion\"\x17\n" +
	"\x15GetClusterInfoRequest\"7\n" +
	"\x16GetClusterInfoResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\"\x1d\n" +
	"\x1bGetAllRegionsInStoreRequest\"8\n" +
	"\x1cGetAllRegionsInStoreResponse\x12\x18\n" +
	"\aregions\x18\x01 \x03(\x04R\aregions\"'\n" +
	"\x15ResetToVersionRequest\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x04R\x02ts\"\x18\n" +
	"\x16ResetToVersionResponse\"Q\n" +
	"\x19GetRangePropertiesRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\"\xa8\x01\n" +
	"\x1aGetRangePropertiesResponse\x12Q\n" +
	"\n" +
	"properties\x18\x01 \x03(\v21.debugpb.GetRangePropertiesResponse.RangePropertyR\n" +
	"properties\x1a7\n" +
	"\rRangeProperty\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xec\x01\n" +
	"\x19FlashbackToVersionRequest\x12*\n" +
	"\acontext\x18\x01 \x01(\v2\x10.kvrpcpb.ContextR\acontext\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1b\n" +
	"\tregion_id\x18\x03 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tstart_key\x18\x04 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x05 \x01(\fR\x06endKey\x12\x19\n" +
	"\bstart_ts\x18\x06 \x01(\x04R\astartTs\x12\x1b\n" +
	"\tcommit_ts\x18\a \x01(\x04R\bcommitTs\"2\n" +
	"\x1aFlashbackToVersionResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"z\n" +
	"\x1cGetRegionReadProgressRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tlog_locks\x18\x02 \x01(\bR\blogLocks\x12 \n" +
	"\fmin_start_ts\x18\x03 \x01(\x04R\n" +
	"minStartTs\"\xb6\a\n" +
	"\x1dGetRegionReadProgressResponse\x12\x17\n" +
	"\asafe_ts\x18\x01 \x01(\x04R\x06safeTs\x12#\n" +
	"\rapplied_index\x18\x02 \x01(\x04R\fappliedIndex\x12=\n" +
	"\x1bpending_front_applied_index\x18\x03 \x01(\x04R\x18pendingFrontAppliedIndex\x12(\n" +
	"\x10pending_front_ts\x18\x04 \x01(\x04R\x0ependingFrontTs\x12;\n" +
	"\x1apending_back_applied_index\x18\x05 \x01(\x04R\x17pendingBackAppliedIndex\x12&\n" +
	"\x0fpending_back_ts\x18\x06 \x01(\x04R\rpendingBackTs\x12=\n" +
	"\x1bregion_read_progress_paused\x18\a \x01(\bR\x18regionReadProgressPaused\x12H\n" +
	"\"duration_to_last_update_safe_ts_ms\x18\b \x01(\x04R\x1cdurationToLastUpdateSafeTsMs\x12I\n" +
	"\"duration_to_last_consume_leader_ms\x18\t \x01(\x04R\x1ddurationToLastConsumeLeaderMs\x12;\n" +
	"\x1aregion_read_progress_exist\x18\n" +
	" \x01(\bR\x17regionReadProgressExist\x12\"\n" +
	"\rread_state_ts\x18\x12 \x01(\x04R\vreadStateTs\x123\n" +
	"\x16read_state_apply_index\x18\x13 \x01(\x04R\x13readStateApplyIndex\x12\x18\n" +
	"\adiscard\x18\x14 \x01(\bR\adiscard\x12\x1f\n" +
	"\vresolved_ts\x18\v \x01(\x04R\n" +
	"resolvedTs\x124\n" +
	"\x16resolver_tracked_index\x18\f \x01(\x04R\x14resolverTrackedIndex\x12%\n" +
	"\x0eresolver_exist\x18\r \x01(\bR\rresolverExist\x12)\n" +
	"\x10resolver_stopped\x18\x0e \x01(\bR\x0fresolverStopped\x12\x1b\n" +
	"\tnum_locks\x18\x10 \x01(\x04R\bnumLocks\x12)\n" +
	"\x10num_transactions\x18\x11 \x01(\x04R\x0fnumTransactions\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error*#\n" +
	"\x02DB\x12\v\n" +
	"\aINVALID\x10\x00\x12\x06\n" +
	"\x02KV\x10\x01\x12\b\n" +
	"\x04RAFT\x10\x02*\x90\x01\n" +
	"\x06MODULE\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x00\x12\b\n" +
	"\x04KVDB\x10\x01\x12\n" +
	"\n" +
	"\x06RAFTDB\x10\x02\x12\f\n" +
	"\bREADPOOL\x10\x03\x12\n" +
	"\n" +
	"\x06SERVER\x10\x04\x12\v\n" +
	"\aSTORAGE\x10\x05\x12\x06\n" +
	"\x02PD\x10\x06\x12\n" +
	"\n" +
	"\x06METRIC\x10\a\x12\x0f\n" +
	"\vCOPROCESSOR\x10\b\x12\f\n" +
	"\bSECURITY\x10\t\x12\n" +
	"\n" +
	"\x06IMPORT\x10\n" +
	"*L\n" +
	"\x19BottommostLevelCompaction\x12\b\n" +
	"\x04Skip\x10\x00\x12\t\n" +
	"\x05Force\x10\x01\x12\x1a\n" +
	"\x16IfHaveCompactionFilter\x10\x022\x9b\r\n" +
	"\x05Debug\x122\n" +
	"\x03Get\x12\x13.debugpb.GetRequest\x1a\x14.debugpb.GetResponse\"\x00\x12>\n" +
	"\aRaftLog\x12\x17.debugpb.RaftLogRequest\x1a\x18.debugpb.RaftLogResponse\"\x00\x12G\n" +
	"\n" +
	"RegionInfo\x12\x1a.debugpb.RegionInfoRequest\x1a\x1b.debugpb.RegionInfoResponse\"\x00\x12G\n" +
	"\n" +
	"RegionSize\x12\x1a.debugpb.RegionSizeRequest\x1a\x1b.debugpb.RegionSizeResponse\"\x00\x12C\n" +
	"\bScanMvcc\x12\x18.debugpb.ScanMvccRequest\x1a\x19.debugpb.ScanMvccResponse\"\x000\x01\x12>\n" +
	"\aCompact\x12\x17.debugpb.CompactRequest\x1a\x18.debugpb.CompactResponse\"\x00\x12V\n" +
	"\x0fInjectFailPoint\x12\x1f.debugpb.InjectFailPointRequest\x1a .debugpb.InjectFailPointResponse\"\x00\x12Y\n" +
	"\x10RecoverFailPoint\x12 .debugpb.RecoverFailPointRequest\x1a!.debugpb.RecoverFailPointResponse\"\x00\x12S\n" +
	"\x0eListFailPoints\x12\x1e.debugpb.ListFailPointsRequest\x1a\x1f.debugpb.ListFailPointsResponse\"\x00\x12G\n" +
	"\n" +
	"GetMetrics\x12\x1a.debugpb.GetMetricsRequest\x1a\x1b.debugpb.GetMetricsResponse\"\x00\x12k\n" +
	"\x16CheckRegionConsistency\x12&.debugpb.RegionConsistencyCheckRequest\x1a'.debugpb.RegionConsistencyCheckResponse\"\x00\x12Y\n" +
	"\x10ModifyTikvConfig\x12 .debugpb.ModifyTikvConfigRequest\x1a!.debugpb.ModifyTikvConfigResponse\"\x00\x12b\n" +
	"\x13GetRegionProperties\x12#.debugpb.GetRegionPropertiesRequest\x1a$.debugpb.GetRegionPropertiesResponse\"\x00\x12M\n" +
	"\fGetStoreInfo\x12\x1c.debugpb.GetStoreInfoRequest\x1a\x1d.debugpb.GetStoreInfoResponse\"\x00\x12S\n" +
	"\x0eGetClusterInfo\x12\x1e.debugpb.GetClusterInfoRequest\x1a\x1f.debugpb.GetClusterInfoResponse\"\x00\x12e\n" +
	"\x14GetAllRegionsInStore\x12$.debugpb.GetAllRegionsInStoreRequest\x1a%.debugpb.GetAllRegionsInStoreResponse\"\x00\x12S\n" +
	"\x0eResetToVersion\x12\x1e.debugpb.ResetToVersionRequest\x1a\x1f.debugpb.ResetToVersionResponse\"\x00\x12_\n" +
	"\x12GetRangeProperties\x12\".debugpb.GetRangePropertiesRequest\x1a#.debugpb.GetRangePropertiesResponse\"\x00\x12_\n" +
	"\x12FlashbackToVersion\x12\".debugpb.FlashbackToVersionRequest\x1a#.debugpb.FlashbackToVersionResponse\"\x00\x12h\n" +
	"\x15GetRegionReadProgress\x12%.debugpb.GetRegionReadProgressRequest\x1a&.debugpb.GetRegionReadProgressResponse\"\x00B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_debugpb_proto_rawDescOnce sync.Once
	file_debugpb_proto_rawDescData []byte
)

func file_debugpb_proto_rawDescGZIP() []byte {
	file_debugpb_proto_rawDescOnce.Do(func() {
		file_debugpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debugpb_proto_rawDesc), len(file_debugpb_proto_rawDesc)))
	})
	return file_debugpb_proto_rawDescData
}

var file_debugpb_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_debugpb_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_debugpb_proto_goTypes = []any{
	(DB)(0),                                          // 0: debugpb.DB
	(MODULE)(0),                                      // 1: debugpb.MODULE
	(BottommostLevelCompaction)(0),                   // 2: debugpb.BottommostLevelCompaction
	(*GetRequest)(nil),                               // 3: debugpb.GetRequest
	(*GetResponse)(nil),                              // 4: debugpb.GetResponse
	(*RaftLogRequest)(nil),                           // 5: debugpb.RaftLogRequest
	(*RaftLogResponse)(nil),                          // 6: debugpb.RaftLogResponse
	(*RegionInfoRequest)(nil),                        // 7: debugpb.RegionInfoRequest
	(*RegionInfoResponse)(nil),                       // 8: debugpb.RegionInfoResponse
	(*RegionSizeRequest)(nil),                        // 9: debugpb.RegionSizeRequest
	(*RegionSizeResponse)(nil),                       // 10: debugpb.RegionSizeResponse
	(*ScanMvccRequest)(nil),                          // 11: debugpb.ScanMvccRequest
	(*ScanMvccResponse)(nil),                         // 12: debugpb.ScanMvccResponse
	(*CompactRequest)(nil),                           // 13: debugpb.CompactRequest
	(*CompactResponse)(nil),                          // 14: debugpb.CompactResponse
	(*InjectFailPointRequest)(nil),                   // 15: debugpb.InjectFailPointRequest
	(*InjectFailPointResponse)(nil),                  // 16: debugpb.InjectFailPointResponse
	(*RecoverFailPointRequest)(nil),                  // 17: debugpb.RecoverFailPointRequest
	(*RecoverFailPointResponse)(nil),                 // 18: debugpb.RecoverFailPointResponse
	(*ListFailPointsRequest)(nil),                    // 19: debugpb.ListFailPointsRequest
	(*ListFailPointsResponse)(nil),                   // 20: debugpb.ListFailPointsResponse
	(*GetMetricsRequest)(nil),                        // 21: debugpb.GetMetricsRequest
	(*GetMetricsResponse)(nil),                       // 22: debugpb.GetMetricsResponse
	(*RegionConsistencyCheckRequest)(nil),            // 23: debugpb.RegionConsistencyCheckRequest
	(*RegionConsistencyCheckResponse)(nil),           // 24: debugpb.RegionConsistencyCheckResponse
	(*ModifyTikvConfigRequest)(nil),                  // 25: debugpb.ModifyTikvConfigRequest
	(*ModifyTikvConfigResponse)(nil),                 // 26: debugpb.ModifyTikvConfigResponse
	(*Property)(nil),                                 // 27: debugpb.Property
	(*GetRegionPropertiesRequest)(nil),               // 28: debugpb.GetRegionPropertiesRequest
	(*GetRegionPropertiesResponse)(nil),              // 29: debugpb.GetRegionPropertiesResponse
	(*GetStoreInfoRequest)(nil),                      // 30: debugpb.GetStoreInfoRequest
	(*GetStoreInfoResponse)(nil),                     // 31: debugpb.GetStoreInfoResponse
	(*GetClusterInfoRequest)(nil),                    // 32: debugpb.GetClusterInfoRequest
	(*GetClusterInfoResponse)(nil),                   // 33: debugpb.GetClusterInfoResponse
	(*GetAllRegionsInStoreRequest)(nil),              // 34: debugpb.GetAllRegionsInStoreRequest
	(*GetAllRegionsInStoreResponse)(nil),             // 35: debugpb.GetAllRegionsInStoreResponse
	(*ResetToVersionRequest)(nil),                    // 36: debugpb.ResetToVersionRequest
	(*ResetToVersionResponse)(nil),                   // 37: debugpb.ResetToVersionResponse
	(*GetRangePropertiesRequest)(nil),                // 38: debugpb.GetRangePropertiesRequest
	(*GetRangePropertiesResponse)(nil),               // 39: debugpb.GetRangePropertiesResponse
	(*FlashbackToVersionRequest)(nil),                // 40: debugpb.FlashbackToVersionRequest
	(*FlashbackToVersionResponse)(nil),               // 41: debugpb.FlashbackToVersionResponse
	(*GetRegionReadProgressRequest)(nil),             // 42: debugpb.GetRegionReadProgressRequest
	(*GetRegionReadProgressResponse)(nil),            // 43: debugpb.GetRegionReadProgressResponse
	(*RegionSizeResponse_Entry)(nil),                 // 44: debugpb.RegionSizeResponse.Entry
	(*ListFailPointsResponse_Entry)(nil),             // 45: debugpb.ListFailPointsResponse.Entry
	(*GetRangePropertiesResponse_RangeProperty)(nil), // 46: debugpb.GetRangePropertiesResponse.RangeProperty
	(*eraftpb.Entry)(nil),                            // 47: eraftpb.Entry
	(*raft_serverpb.RaftLocalState)(nil),             // 48: raft_serverpb.RaftLocalState
	(*raft_serverpb.RaftApplyState)(nil),             // 49: raft_serverpb.RaftApplyState
	(*raft_serverpb.RegionLocalState)(nil),           // 50: raft_serverpb.RegionLocalState
	(*kvrpcpb.MvccInfo)(nil),                         // 51: kvrpcpb.MvccInfo
	(kvrpcpb.APIVersion)(0),                          // 52: kvrpcpb.APIVersion
	(*kvrpcpb.Context)(nil),                          // 53: kvrpcpb.Context
}
var file_debugpb_proto_depIdxs = []int32{
	0,  // 0: debugpb.GetRequest.db:type_name -> debugpb.DB
	47, // 1: debugpb.RaftLogResponse.entry:type_name -> eraftpb.Entry
	48, // 2: debugpb.RegionInfoResponse.raft_local_state:type_name -> raft_serverpb.RaftLocalState
	49, // 3: debugpb.RegionInfoResponse.raft_apply_state:type_name -> raft_serverpb.RaftApplyState
	50, // 4: debugpb.RegionInfoResponse.region_local_state:type_name -> raft_serverpb.RegionLocalState
	44, // 5: debugpb.RegionSizeResponse.entries:type_name -> debugpb.RegionSizeResponse.Entry
	51, // 6: debugpb.ScanMvccResponse.info:type_name -> kvrpcpb.MvccInfo
	0,  // 7: debugpb.CompactRequest.db:type_name -> debugpb.DB
	2,  // 8: debugpb.CompactRequest.bottommost_level_compaction:type_name -> debugpb.BottommostLevelCompaction
	45, // 9: debugpb.ListFailPointsResponse.entries:type_name -> debugpb.ListFailPointsResponse.Entry
	1,  // 10: debugpb.ModifyTikvConfigRequest.module:type_name -> debugpb.MODULE
	27, // 11: debugpb.GetRegionPropertiesResponse.props:type_name -> debugpb.Property
	52, // 12: debugpb.GetStoreInfoResponse.api_version:type_name -> kvrpcpb.APIVersion
	46, // 13: debugpb.GetRangePropertiesResponse.properties:type_name -> debugpb.GetRangePropertiesResponse.RangeProperty
	53, // 14: debugpb.FlashbackToVersionRequest.context:type_name -> kvrpcpb.Context
	3,  // 15: debugpb.Debug.Get:input_type -> debugpb.GetRequest
	5,  // 16: debugpb.Debug.RaftLog:input_type -> debugpb.RaftLogRequest
	7,  // 17: debugpb.Debug.RegionInfo:input_type -> debugpb.RegionInfoRequest
	9,  // 18: debugpb.Debug.RegionSize:input_type -> debugpb.RegionSizeRequest
	11, // 19: debugpb.Debug.ScanMvcc:input_type -> debugpb.ScanMvccRequest
	13, // 20: debugpb.Debug.Compact:input_type -> debugpb.CompactRequest
	15, // 21: debugpb.Debug.InjectFailPoint:input_type -> debugpb.InjectFailPointRequest
	17, // 22: debugpb.Debug.RecoverFailPoint:input_type -> debugpb.RecoverFailPointRequest
	19, // 23: debugpb.Debug.ListFailPoints:input_type -> debugpb.ListFailPointsRequest
	21, // 24: debugpb.Debug.GetMetrics:input_type -> debugpb.GetMetricsRequest
	23, // 25: debugpb.Debug.CheckRegionConsistency:input_type -> debugpb.RegionConsistencyCheckRequest
	25, // 26: debugpb.Debug.ModifyTikvConfig:input_type -> debugpb.ModifyTikvConfigRequest
	28, // 27: debugpb.Debug.GetRegionProperties:input_type -> debugpb.GetRegionPropertiesRequest
	30, // 28: debugpb.Debug.GetStoreInfo:input_type -> debugpb.GetStoreInfoRequest
	32, // 29: debugpb.Debug.GetClusterInfo:input_type -> debugpb.GetClusterInfoRequest
	34, // 30: debugpb.Debug.GetAllRegionsInStore:input_type -> debugpb.GetAllRegionsInStoreRequest
	36, // 31: debugpb.Debug.ResetToVersion:input_type -> debugpb.ResetToVersionRequest
	38, // 32: debugpb.Debug.GetRangeProperties:input_type -> debugpb.GetRangePropertiesRequest
	40, // 33: debugpb.Debug.FlashbackToVersion:input_type -> debugpb.FlashbackToVersionRequest
	42, // 34: debugpb.Debug.GetRegionReadProgress:input_type -> debugpb.GetRegionReadProgressRequest
	4,  // 35: debugpb.Debug.Get:output_type -> debugpb.GetResponse
	6,  // 36: debugpb.Debug.RaftLog:output_type -> debugpb.RaftLogResponse
	8,  // 37: debugpb.Debug.RegionInfo:output_type -> debugpb.RegionInfoResponse
	10, // 38: debugpb.Debug.RegionSize:output_type -> debugpb.RegionSizeResponse
	12, // 39: debugpb.Debug.ScanMvcc:output_type -> debugpb.ScanMvccResponse
	14, // 40: debugpb.Debug.Compact:output_type -> debugpb.CompactResponse
	16, // 41: debugpb.Debug.InjectFailPoint:output_type -> debugpb.InjectFailPointResponse
	18, // 42: debugpb.Debug.RecoverFailPoint:output_type -> debugpb.RecoverFailPointResponse
	20, // 43: debugpb.Debug.ListFailPoints:output_type -> debugpb.ListFailPointsResponse
	22, // 44: debugpb.Debug.GetMetrics:output_type -> debugpb.GetMetricsResponse
	24, // 45: debugpb.Debug.CheckRegionConsistency:output_type -> debugpb.RegionConsistencyCheckResponse
	26, // 46: debugpb.Debug.ModifyTikvConfig:output_type -> debugpb.ModifyTikvConfigResponse
	29, // 47: debugpb.Debug.GetRegionProperties:output_type -> debugpb.GetRegionPropertiesResponse
	31, // 48: debugpb.Debug.GetStoreInfo:output_type -> debugpb.GetStoreInfoResponse
	33, // 49: debugpb.Debug.GetClusterInfo:output_type -> debugpb.GetClusterInfoResponse
	35, // 50: debugpb.Debug.GetAllRegionsInStore:output_type -> debugpb.GetAllRegionsInStoreResponse
	37, // 51: debugpb.Debug.ResetToVersion:output_type -> debugpb.ResetToVersionResponse
	39, // 52: debugpb.Debug.GetRangeProperties:output_type -> debugpb.GetRangePropertiesResponse
	41, // 53: debugpb.Debug.FlashbackToVersion:output_type -> debugpb.FlashbackToVersionResponse
	43, // 54: debugpb.Debug.GetRegionReadProgress:output_type -> debugpb.GetRegionReadProgressResponse
	35, // [35:55] is the sub-list for method output_type
	15, // [15:35] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_debugpb_proto_init() }
func file_debugpb_proto_init() {
	if File_debugpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debugpb_proto_rawDesc), len(file_debugpb_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_debugpb_proto_goTypes,
		DependencyIndexes: file_debugpb_proto_depIdxs,
		EnumInfos:         file_debugpb_proto_enumTypes,
		MessageInfos:      file_debugpb_proto_msgTypes,
	}.Build()
	File_debugpb_proto = out.File
	file_debugpb_proto_goTypes = nil
	file_debugpb_proto_depIdxs = nil
}
