// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: configpb.proto

package configpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_UNKNOWN                StatusCode = 0
	StatusCode_OK                     StatusCode = 1
	StatusCode_WRONG_VERSION          StatusCode = 2
	StatusCode_NOT_CHANGE             StatusCode = 3
	StatusCode_COMPONENT_NOT_FOUND    StatusCode = 4
	StatusCode_COMPONENT_ID_NOT_FOUND StatusCode = 5
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "WRONG_VERSION",
		3: "NOT_CHANGE",
		4: "COMPONENT_NOT_FOUND",
		5: "COMPONENT_ID_NOT_FOUND",
	}
	StatusCode_value = map[string]int32{
		"UNKNOWN":                0,
		"OK":                     1,
		"WRONG_VERSION":          2,
		"NOT_CHANGE":             3,
		"COMPONENT_NOT_FOUND":    4,
		"COMPONENT_ID_NOT_FOUND": 5,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_configpb_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_configpb_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=configpb.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_configpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_UNKNOWN
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The version is used to tell the configuration which can be shared
// or not apart.
// Global version represents the version of these configuration
// which can be shared, each kind of component only have one.
// For local version, every component will have one to represent
// the version of these configuration which cannot be shared.
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Local         uint64                 `protobuf:"varint,1,opt,name=local,proto3" json:"local,omitempty"`
	Global        uint64                 `protobuf:"varint,2,opt,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_configpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{1}
}

func (x *Version) GetLocal() uint64 {
	if x != nil {
		return x.Local
	}
	return 0
}

func (x *Version) GetGlobal() uint64 {
	if x != nil {
		return x.Global
	}
	return 0
}

type Local struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Local) Reset() {
	*x = Local{}
	mi := &file_configpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Local) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Local) ProtoMessage() {}

func (x *Local) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Local.ProtoReflect.Descriptor instead.
func (*Local) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{2}
}

func (x *Local) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type Global struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Global) Reset() {
	*x = Global{}
	mi := &file_configpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{3}
}

func (x *Global) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type ConfigKind struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ConfigKind_Local
	//	*ConfigKind_Global
	Kind          isConfigKind_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigKind) Reset() {
	*x = ConfigKind{}
	mi := &file_configpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigKind) ProtoMessage() {}

func (x *ConfigKind) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigKind.ProtoReflect.Descriptor instead.
func (*ConfigKind) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigKind) GetKind() isConfigKind_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ConfigKind) GetLocal() *Local {
	if x != nil {
		if x, ok := x.Kind.(*ConfigKind_Local); ok {
			return x.Local
		}
	}
	return nil
}

func (x *ConfigKind) GetGlobal() *Global {
	if x != nil {
		if x, ok := x.Kind.(*ConfigKind_Global); ok {
			return x.Global
		}
	}
	return nil
}

type isConfigKind_Kind interface {
	isConfigKind_Kind()
}

type ConfigKind_Local struct {
	Local *Local `protobuf:"bytes,1,opt,name=local,proto3,oneof"`
}

type ConfigKind_Global struct {
	Global *Global `protobuf:"bytes,2,opt,name=global,proto3,oneof"`
}

func (*ConfigKind_Local) isConfigKind_Kind() {}

func (*ConfigKind_Global) isConfigKind_Kind() {}

type ConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_configpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LocalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	ComponentId   string                 `protobuf:"bytes,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalConfig) Reset() {
	*x = LocalConfig{}
	mi := &file_configpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalConfig) ProtoMessage() {}

func (x *LocalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalConfig.ProtoReflect.Descriptor instead.
func (*LocalConfig) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{6}
}

func (x *LocalConfig) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *LocalConfig) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LocalConfig) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *LocalConfig) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_configpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{7}
}

func (x *Header) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	ComponentId   string                 `protobuf:"bytes,4,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_configpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateRequest) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *CreateRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *CreateRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *CreateRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_configpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{9}
}

func (x *CreateResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *CreateResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_configpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LocalConfigs  []*LocalConfig         `protobuf:"bytes,3,rep,name=local_configs,json=localConfigs,proto3" json:"local_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_configpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAllResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetAllResponse) GetLocalConfigs() []*LocalConfig {
	if x != nil {
		return x.LocalConfigs
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	ComponentId   string                 `protobuf:"bytes,4,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_configpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{12}
}

func (x *GetRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetRequest) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *GetRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_configpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{13}
}

func (x *GetResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          *ConfigKind            `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Entries       []*ConfigEntry         `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_configpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateRequest) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateRequest) GetKind() *ConfigKind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UpdateRequest) GetEntries() []*ConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_configpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          *ConfigKind            `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_configpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteRequest) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DeleteRequest) GetKind() *ConfigKind {
	if x != nil {
		return x.Kind
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_configpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_configpb_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DeleteResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_configpb_proto protoreflect.FileDescriptor

const file_configpb_proto_rawDesc = "" +
	"\n" +
	"\x0econfigpb.proto\x12\bconfigpb\x1a\x0frustproto.proto\x1a\x1cgoogle/api/annotations.proto\"L\n" +
	"\x06Status\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.configpb.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\aVersion\x12\x14\n" +
	"\x05local\x18\x01 \x01(\x04R\x05local\x12\x16\n" +
	"\x06global\x18\x02 \x01(\x04R\x06global\"*\n" +
	"\x05Local\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\"&\n" +
	"\x06Global\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\"i\n" +
	"\n" +
	"ConfigKind\x12'\n" +
	"\x05local\x18\x01 \x01(\v2\x0f.configpb.LocalH\x00R\x05local\x12*\n" +
	"\x06global\x18\x02 \x01(\v2\x10.configpb.GlobalH\x00R\x06globalB\x06\n" +
	"\x04kind\"7\n" +
	"\vConfigEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x93\x01\n" +
	"\vLocalConfig\x12+\n" +
	"\aversion\x18\x01 \x01(\v2\x11.configpb.VersionR\aversion\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12!\n" +
	"\fcomponent_id\x18\x03 \x01(\tR\vcomponentId\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\"'\n" +
	"\x06Header\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\"\xbf\x01\n" +
	"\rCreateRequest\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12+\n" +
	"\aversion\x18\x02 \x01(\v2\x11.configpb.VersionR\aversion\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12!\n" +
	"\fcomponent_id\x18\x04 \x01(\tR\vcomponentId\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\"\xa9\x01\n" +
	"\x0eCreateResponse\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.configpb.StatusR\x06status\x12+\n" +
	"\aversion\x18\x03 \x01(\v2\x11.configpb.VersionR\aversion\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\"9\n" +
	"\rGetAllRequest\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\"\xa0\x01\n" +
	"\x0eGetAllResponse\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.configpb.StatusR\x06status\x12:\n" +
	"\rlocal_configs\x18\x03 \x03(\v2\x15.configpb.LocalConfigR\flocalConfigs\"\xa4\x01\n" +
	"\n" +
	"GetRequest\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12+\n" +
	"\aversion\x18\x02 \x01(\v2\x11.configpb.VersionR\aversion\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12!\n" +
	"\fcomponent_id\x18\x04 \x01(\tR\vcomponentId\"\xa6\x01\n" +
	"\vGetResponse\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.configpb.StatusR\x06status\x12+\n" +
	"\aversion\x18\x03 \x01(\v2\x11.configpb.VersionR\aversion\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\"\xc1\x01\n" +
	"\rUpdateRequest\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12+\n" +
	"\aversion\x18\x02 \x01(\v2\x11.configpb.VersionR\aversion\x12(\n" +
	"\x04kind\x18\x03 \x01(\v2\x14.configpb.ConfigKindR\x04kind\x12/\n" +
	"\aentries\x18\x04 \x03(\v2\x15.configpb.ConfigEntryR\aentries\"\xa9\x01\n" +
	"\x0eUpdateResponse\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.configpb.StatusR\x06status\x12+\n" +
	"\aversion\x18\x03 \x01(\v2\x11.configpb.VersionR\aversion\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\"\x90\x01\n" +
	"\rDeleteRequest\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12+\n" +
	"\aversion\x18\x02 \x01(\v2\x11.configpb.VersionR\aversion\x12(\n" +
	"\x04kind\x18\x03 \x01(\v2\x14.configpb.ConfigKindR\x04kind\"\x91\x01\n" +
	"\x0eDeleteResponse\x12(\n" +
	"\x06header\x18\x01 \x01(\v2\x10.configpb.HeaderR\x06header\x12(\n" +
	"\x06status\x18\x02 \x01(\v2\x10.configpb.StatusR\x06status\x12+\n" +
	"\aversion\x18\x03 \x01(\v2\x11.configpb.VersionR\aversion*y\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x11\n" +
	"\rWRONG_VERSION\x10\x02\x12\x0e\n" +
	"\n" +
	"NOT_CHANGE\x10\x03\x12\x17\n" +
	"\x13COMPONENT_NOT_FOUND\x10\x04\x12\x1a\n" +
	"\x16COMPONENT_ID_NOT_FOUND\x10\x052\xf3\x02\n" +
	"\x06Config\x12=\n" +
	"\x06Create\x12\x17.configpb.CreateRequest\x1a\x18.configpb.CreateResponse\"\x00\x12=\n" +
	"\x06GetAll\x12\x17.configpb.GetAllRequest\x1a\x18.configpb.GetAllResponse\"\x00\x12F\n" +
	"\x03Get\x12\x14.configpb.GetRequest\x1a\x15.configpb.GetResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/component\x12R\n" +
	"\x06Update\x12\x17.configpb.UpdateRequest\x1a\x18.configpb.UpdateResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/component\x12O\n" +
	"\x06Delete\x12\x17.configpb.DeleteRequest\x1a\x18.configpb.DeleteResponse\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/componentB\x04ب\b\x01b\x06proto3"

var (
	file_configpb_proto_rawDescOnce sync.Once
	file_configpb_proto_rawDescData []byte
)

func file_configpb_proto_rawDescGZIP() []byte {
	file_configpb_proto_rawDescOnce.Do(func() {
		file_configpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configpb_proto_rawDesc), len(file_configpb_proto_rawDesc)))
	})
	return file_configpb_proto_rawDescData
}

var file_configpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_configpb_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_configpb_proto_goTypes = []any{
	(StatusCode)(0),        // 0: configpb.StatusCode
	(*Status)(nil),         // 1: configpb.Status
	(*Version)(nil),        // 2: configpb.Version
	(*Local)(nil),          // 3: configpb.Local
	(*Global)(nil),         // 4: configpb.Global
	(*ConfigKind)(nil),     // 5: configpb.ConfigKind
	(*ConfigEntry)(nil),    // 6: configpb.ConfigEntry
	(*LocalConfig)(nil),    // 7: configpb.LocalConfig
	(*Header)(nil),         // 8: configpb.Header
	(*CreateRequest)(nil),  // 9: configpb.CreateRequest
	(*CreateResponse)(nil), // 10: configpb.CreateResponse
	(*GetAllRequest)(nil),  // 11: configpb.GetAllRequest
	(*GetAllResponse)(nil), // 12: configpb.GetAllResponse
	(*GetRequest)(nil),     // 13: configpb.GetRequest
	(*GetResponse)(nil),    // 14: configpb.GetResponse
	(*UpdateRequest)(nil),  // 15: configpb.UpdateRequest
	(*UpdateResponse)(nil), // 16: configpb.UpdateResponse
	(*DeleteRequest)(nil),  // 17: configpb.DeleteRequest
	(*DeleteResponse)(nil), // 18: configpb.DeleteResponse
}
var file_configpb_proto_depIdxs = []int32{
	0,  // 0: configpb.Status.code:type_name -> configpb.StatusCode
	3,  // 1: configpb.ConfigKind.local:type_name -> configpb.Local
	4,  // 2: configpb.ConfigKind.global:type_name -> configpb.Global
	2,  // 3: configpb.LocalConfig.version:type_name -> configpb.Version
	8,  // 4: configpb.CreateRequest.header:type_name -> configpb.Header
	2,  // 5: configpb.CreateRequest.version:type_name -> configpb.Version
	8,  // 6: configpb.CreateResponse.header:type_name -> configpb.Header
	1,  // 7: configpb.CreateResponse.status:type_name -> configpb.Status
	2,  // 8: configpb.CreateResponse.version:type_name -> configpb.Version
	8,  // 9: configpb.GetAllRequest.header:type_name -> configpb.Header
	8,  // 10: configpb.GetAllResponse.header:type_name -> configpb.Header
	1,  // 11: configpb.GetAllResponse.status:type_name -> configpb.Status
	7,  // 12: configpb.GetAllResponse.local_configs:type_name -> configpb.LocalConfig
	8,  // 13: configpb.GetRequest.header:type_name -> configpb.Header
	2,  // 14: configpb.GetRequest.version:type_name -> configpb.Version
	8,  // 15: configpb.GetResponse.header:type_name -> configpb.Header
	1,  // 16: configpb.GetResponse.status:type_name -> configpb.Status
	2,  // 17: configpb.GetResponse.version:type_name -> configpb.Version
	8,  // 18: configpb.UpdateRequest.header:type_name -> configpb.Header
	2,  // 19: configpb.UpdateRequest.version:type_name -> configpb.Version
	5,  // 20: configpb.UpdateRequest.kind:type_name -> configpb.ConfigKind
	6,  // 21: configpb.UpdateRequest.entries:type_name -> configpb.ConfigEntry
	8,  // 22: configpb.UpdateResponse.header:type_name -> configpb.Header
	1,  // 23: configpb.UpdateResponse.status:type_name -> configpb.Status
	2,  // 24: configpb.UpdateResponse.version:type_name -> configpb.Version
	8,  // 25: configpb.DeleteRequest.header:type_name -> configpb.Header
	2,  // 26: configpb.DeleteRequest.version:type_name -> configpb.Version
	5,  // 27: configpb.DeleteRequest.kind:type_name -> configpb.ConfigKind
	8,  // 28: configpb.DeleteResponse.header:type_name -> configpb.Header
	1,  // 29: configpb.DeleteResponse.status:type_name -> configpb.Status
	2,  // 30: configpb.DeleteResponse.version:type_name -> configpb.Version
	9,  // 31: configpb.Config.Create:input_type -> configpb.CreateRequest
	11, // 32: configpb.Config.GetAll:input_type -> configpb.GetAllRequest
	13, // 33: configpb.Config.Get:input_type -> configpb.GetRequest
	15, // 34: configpb.Config.Update:input_type -> configpb.UpdateRequest
	17, // 35: configpb.Config.Delete:input_type -> configpb.DeleteRequest
	10, // 36: configpb.Config.Create:output_type -> configpb.CreateResponse
	12, // 37: configpb.Config.GetAll:output_type -> configpb.GetAllResponse
	14, // 38: configpb.Config.Get:output_type -> configpb.GetResponse
	16, // 39: configpb.Config.Update:output_type -> configpb.UpdateResponse
	18, // 40: configpb.Config.Delete:output_type -> configpb.DeleteResponse
	36, // [36:41] is the sub-list for method output_type
	31, // [31:36] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_configpb_proto_init() }
func file_configpb_proto_init() {
	if File_configpb_proto != nil {
		return
	}
	file_configpb_proto_msgTypes[4].OneofWrappers = []any{
		(*ConfigKind_Local)(nil),
		(*ConfigKind_Global)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configpb_proto_rawDesc), len(file_configpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configpb_proto_goTypes,
		DependencyIndexes: file_configpb_proto_depIdxs,
		EnumInfos:         file_configpb_proto_enumTypes,
		MessageInfos:      file_configpb_proto_msgTypes,
	}.Build()
	File_configpb_proto = out.File
	file_configpb_proto_goTypes = nil
	file_configpb_proto_depIdxs = nil
}
