// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: replication_modepb.proto

package replication_modepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationMode int32

const (
	// The standard mode. Replicate logs to majority peer.
	ReplicationMode_MAJORITY ReplicationMode = 0
	// DR mode. Replicate logs among 2 DCs.
	ReplicationMode_DR_AUTO_SYNC ReplicationMode = 1
)

// Enum value maps for ReplicationMode.
var (
	ReplicationMode_name = map[int32]string{
		0: "MAJORITY",
		1: "DR_AUTO_SYNC",
	}
	ReplicationMode_value = map[string]int32{
		"MAJORITY":     0,
		"DR_AUTO_SYNC": 1,
	}
)

func (x ReplicationMode) Enum() *ReplicationMode {
	p := new(ReplicationMode)
	*p = x
	return p
}

func (x ReplicationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_modepb_proto_enumTypes[0].Descriptor()
}

func (ReplicationMode) Type() protoreflect.EnumType {
	return &file_replication_modepb_proto_enumTypes[0]
}

func (x ReplicationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicationMode.Descriptor instead.
func (ReplicationMode) EnumDescriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{0}
}

type DRAutoSyncState int32

const (
	// Raft logs need to sync between different DCs
	DRAutoSyncState_SYNC DRAutoSyncState = 0
	// Wait for switching to ASYNC. Stop sync raft logs between DCs.
	DRAutoSyncState_ASYNC_WAIT DRAutoSyncState = 1
	// Raft logs need to sync to majority peers
	DRAutoSyncState_ASYNC DRAutoSyncState = 2
	// Switching from ASYNC to SYNC mode
	DRAutoSyncState_SYNC_RECOVER DRAutoSyncState = 3
)

// Enum value maps for DRAutoSyncState.
var (
	DRAutoSyncState_name = map[int32]string{
		0: "SYNC",
		1: "ASYNC_WAIT",
		2: "ASYNC",
		3: "SYNC_RECOVER",
	}
	DRAutoSyncState_value = map[string]int32{
		"SYNC":         0,
		"ASYNC_WAIT":   1,
		"ASYNC":        2,
		"SYNC_RECOVER": 3,
	}
)

func (x DRAutoSyncState) Enum() *DRAutoSyncState {
	p := new(DRAutoSyncState)
	*p = x
	return p
}

func (x DRAutoSyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DRAutoSyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_modepb_proto_enumTypes[1].Descriptor()
}

func (DRAutoSyncState) Type() protoreflect.EnumType {
	return &file_replication_modepb_proto_enumTypes[1]
}

func (x DRAutoSyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DRAutoSyncState.Descriptor instead.
func (DRAutoSyncState) EnumDescriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{1}
}

type RegionReplicationState int32

const (
	// The region's state is unknown
	RegionReplicationState_UNKNOWN RegionReplicationState = 0
	// Logs sync to majority peers
	RegionReplicationState_SIMPLE_MAJORITY RegionReplicationState = 1
	// Logs sync to different DCs
	RegionReplicationState_INTEGRITY_OVER_LABEL RegionReplicationState = 2
)

// Enum value maps for RegionReplicationState.
var (
	RegionReplicationState_name = map[int32]string{
		0: "UNKNOWN",
		1: "SIMPLE_MAJORITY",
		2: "INTEGRITY_OVER_LABEL",
	}
	RegionReplicationState_value = map[string]int32{
		"UNKNOWN":              0,
		"SIMPLE_MAJORITY":      1,
		"INTEGRITY_OVER_LABEL": 2,
	}
)

func (x RegionReplicationState) Enum() *RegionReplicationState {
	p := new(RegionReplicationState)
	*p = x
	return p
}

func (x RegionReplicationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionReplicationState) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_modepb_proto_enumTypes[2].Descriptor()
}

func (RegionReplicationState) Type() protoreflect.EnumType {
	return &file_replication_modepb_proto_enumTypes[2]
}

func (x RegionReplicationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionReplicationState.Descriptor instead.
func (RegionReplicationState) EnumDescriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{2}
}

// The replication status sync from PD to TiKV.
type ReplicationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          ReplicationMode        `protobuf:"varint,1,opt,name=mode,proto3,enum=replication_modepb.ReplicationMode" json:"mode,omitempty"`
	DrAutoSync    *DRAutoSync            `protobuf:"bytes,2,opt,name=dr_auto_sync,json=drAutoSync,proto3" json:"dr_auto_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationStatus) Reset() {
	*x = ReplicationStatus{}
	mi := &file_replication_modepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStatus) ProtoMessage() {}

func (x *ReplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_replication_modepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStatus.ProtoReflect.Descriptor instead.
func (*ReplicationStatus) Descriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationStatus) GetMode() ReplicationMode {
	if x != nil {
		return x.Mode
	}
	return ReplicationMode_MAJORITY
}

func (x *ReplicationStatus) GetDrAutoSync() *DRAutoSync {
	if x != nil {
		return x.DrAutoSync
	}
	return nil
}

// The status of dr-autosync mode.
type DRAutoSync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key of the label that used for distinguish different DC.
	LabelKey string          `protobuf:"bytes,1,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`
	State    DRAutoSyncState `protobuf:"varint,2,opt,name=state,proto3,enum=replication_modepb.DRAutoSyncState" json:"state,omitempty"`
	// Unique ID of the state, it increases after each state transfer.
	StateId uint64 `protobuf:"varint,3,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	// Duration to wait before switching to SYNC by force (in seconds)
	WaitSyncTimeoutHint int32 `protobuf:"varint,4,opt,name=wait_sync_timeout_hint,json=waitSyncTimeoutHint,proto3" json:"wait_sync_timeout_hint,omitempty"`
	// Stores should only sync messages with available stores when state is ASYNC or ASYNC_WAIT.
	AvailableStores []uint64 `protobuf:"varint,5,rep,packed,name=available_stores,json=availableStores,proto3" json:"available_stores,omitempty"`
	// Stores should forbid region split.
	PauseRegionSplit bool `protobuf:"varint,6,opt,name=pause_region_split,json=pauseRegionSplit,proto3" json:"pause_region_split,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DRAutoSync) Reset() {
	*x = DRAutoSync{}
	mi := &file_replication_modepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DRAutoSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DRAutoSync) ProtoMessage() {}

func (x *DRAutoSync) ProtoReflect() protoreflect.Message {
	mi := &file_replication_modepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DRAutoSync.ProtoReflect.Descriptor instead.
func (*DRAutoSync) Descriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{1}
}

func (x *DRAutoSync) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *DRAutoSync) GetState() DRAutoSyncState {
	if x != nil {
		return x.State
	}
	return DRAutoSyncState_SYNC
}

func (x *DRAutoSync) GetStateId() uint64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *DRAutoSync) GetWaitSyncTimeoutHint() int32 {
	if x != nil {
		return x.WaitSyncTimeoutHint
	}
	return 0
}

func (x *DRAutoSync) GetAvailableStores() []uint64 {
	if x != nil {
		return x.AvailableStores
	}
	return nil
}

func (x *DRAutoSync) GetPauseRegionSplit() bool {
	if x != nil {
		return x.PauseRegionSplit
	}
	return false
}

// The replication status sync from TiKV to PD.
type RegionReplicationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State RegionReplicationState `protobuf:"varint,1,opt,name=state,proto3,enum=replication_modepb.RegionReplicationState" json:"state,omitempty"`
	// Unique ID of the state, it increases after each state transfer.
	StateId       uint64 `protobuf:"varint,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionReplicationStatus) Reset() {
	*x = RegionReplicationStatus{}
	mi := &file_replication_modepb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionReplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionReplicationStatus) ProtoMessage() {}

func (x *RegionReplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_replication_modepb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionReplicationStatus.ProtoReflect.Descriptor instead.
func (*RegionReplicationStatus) Descriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{2}
}

func (x *RegionReplicationStatus) GetState() RegionReplicationState {
	if x != nil {
		return x.State
	}
	return RegionReplicationState_UNKNOWN
}

func (x *RegionReplicationStatus) GetStateId() uint64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

type StoreDRAutoSyncStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         DRAutoSyncState        `protobuf:"varint,1,opt,name=state,proto3,enum=replication_modepb.DRAutoSyncState" json:"state,omitempty"`
	StateId       uint64                 `protobuf:"varint,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDRAutoSyncStatus) Reset() {
	*x = StoreDRAutoSyncStatus{}
	mi := &file_replication_modepb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDRAutoSyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDRAutoSyncStatus) ProtoMessage() {}

func (x *StoreDRAutoSyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_replication_modepb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDRAutoSyncStatus.ProtoReflect.Descriptor instead.
func (*StoreDRAutoSyncStatus) Descriptor() ([]byte, []int) {
	return file_replication_modepb_proto_rawDescGZIP(), []int{3}
}

func (x *StoreDRAutoSyncStatus) GetState() DRAutoSyncState {
	if x != nil {
		return x.State
	}
	return DRAutoSyncState_SYNC
}

func (x *StoreDRAutoSyncStatus) GetStateId() uint64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

var File_replication_modepb_proto protoreflect.FileDescriptor

const file_replication_modepb_proto_rawDesc = "" +
	"\n" +
	"\x18replication_modepb.proto\x12\x12replication_modepb\x1a\x0frustproto.proto\"\x8e\x01\n" +
	"\x11ReplicationStatus\x127\n" +
	"\x04mode\x18\x01 \x01(\x0e2#.replication_modepb.ReplicationModeR\x04mode\x12@\n" +
	"\fdr_auto_sync\x18\x02 \x01(\v2\x1e.replication_modepb.DRAutoSyncR\n" +
	"drAutoSync\"\x8d\x02\n" +
	"\n" +
	"DRAutoSync\x12\x1b\n" +
	"\tlabel_key\x18\x01 \x01(\tR\blabelKey\x129\n" +
	"\x05state\x18\x02 \x01(\x0e2#.replication_modepb.DRAutoSyncStateR\x05state\x12\x19\n" +
	"\bstate_id\x18\x03 \x01(\x04R\astateId\x123\n" +
	"\x16wait_sync_timeout_hint\x18\x04 \x01(\x05R\x13waitSyncTimeoutHint\x12)\n" +
	"\x10available_stores\x18\x05 \x03(\x04R\x0favailableStores\x12,\n" +
	"\x12pause_region_split\x18\x06 \x01(\bR\x10pauseRegionSplit\"v\n" +
	"\x17RegionReplicationStatus\x12@\n" +
	"\x05state\x18\x01 \x01(\x0e2*.replication_modepb.RegionReplicationStateR\x05state\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\x04R\astateId\"m\n" +
	"\x15StoreDRAutoSyncStatus\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.replication_modepb.DRAutoSyncStateR\x05state\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\x04R\astateId*1\n" +
	"\x0fReplicationMode\x12\f\n" +
	"\bMAJORITY\x10\x00\x12\x10\n" +
	"\fDR_AUTO_SYNC\x10\x01*H\n" +
	"\x0fDRAutoSyncState\x12\b\n" +
	"\x04SYNC\x10\x00\x12\x0e\n" +
	"\n" +
	"ASYNC_WAIT\x10\x01\x12\t\n" +
	"\x05ASYNC\x10\x02\x12\x10\n" +
	"\fSYNC_RECOVER\x10\x03*T\n" +
	"\x16RegionReplicationState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSIMPLE_MAJORITY\x10\x01\x12\x18\n" +
	"\x14INTEGRITY_OVER_LABEL\x10\x02B\x04ب\b\x01b\x06proto3"

var (
	file_replication_modepb_proto_rawDescOnce sync.Once
	file_replication_modepb_proto_rawDescData []byte
)

func file_replication_modepb_proto_rawDescGZIP() []byte {
	file_replication_modepb_proto_rawDescOnce.Do(func() {
		file_replication_modepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_modepb_proto_rawDesc), len(file_replication_modepb_proto_rawDesc)))
	})
	return file_replication_modepb_proto_rawDescData
}

var file_replication_modepb_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_replication_modepb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_replication_modepb_proto_goTypes = []any{
	(ReplicationMode)(0),            // 0: replication_modepb.ReplicationMode
	(DRAutoSyncState)(0),            // 1: replication_modepb.DRAutoSyncState
	(RegionReplicationState)(0),     // 2: replication_modepb.RegionReplicationState
	(*ReplicationStatus)(nil),       // 3: replication_modepb.ReplicationStatus
	(*DRAutoSync)(nil),              // 4: replication_modepb.DRAutoSync
	(*RegionReplicationStatus)(nil), // 5: replication_modepb.RegionReplicationStatus
	(*StoreDRAutoSyncStatus)(nil),   // 6: replication_modepb.StoreDRAutoSyncStatus
}
var file_replication_modepb_proto_depIdxs = []int32{
	0, // 0: replication_modepb.ReplicationStatus.mode:type_name -> replication_modepb.ReplicationMode
	4, // 1: replication_modepb.ReplicationStatus.dr_auto_sync:type_name -> replication_modepb.DRAutoSync
	1, // 2: replication_modepb.DRAutoSync.state:type_name -> replication_modepb.DRAutoSyncState
	2, // 3: replication_modepb.RegionReplicationStatus.state:type_name -> replication_modepb.RegionReplicationState
	1, // 4: replication_modepb.StoreDRAutoSyncStatus.state:type_name -> replication_modepb.DRAutoSyncState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_replication_modepb_proto_init() }
func file_replication_modepb_proto_init() {
	if File_replication_modepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_modepb_proto_rawDesc), len(file_replication_modepb_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replication_modepb_proto_goTypes,
		DependencyIndexes: file_replication_modepb_proto_depIdxs,
		EnumInfos:         file_replication_modepb_proto_enumTypes,
		MessageInfos:      file_replication_modepb_proto_msgTypes,
	}.Build()
	File_replication_modepb_proto = out.File
	file_replication_modepb_proto_goTypes = nil
	file_replication_modepb_proto_depIdxs = nil
}
