// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: tracepb.proto

package tracepb

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TraceRecordPubSub_Subscribe_FullMethodName = "/tracepb.TraceRecordPubSub/Subscribe"
)

// TraceRecordPubSubClient is the client API for TraceRecordPubSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceRecordPubSubClient interface {
	// Subscribe the Trace records generated on this service. The service will periodically (e.g. per minute)
	// publishes Trace records to clients via gRPC stream.
	Subscribe(ctx context.Context, in *TraceRecordRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceRecord], error)
}

type traceRecordPubSubClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceRecordPubSubClient(cc grpc.ClientConnInterface) TraceRecordPubSubClient {
	return &traceRecordPubSubClient{cc}
}

func (c *traceRecordPubSubClient) Subscribe(ctx context.Context, in *TraceRecordRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TraceRecordPubSub_ServiceDesc.Streams[0], TraceRecordPubSub_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TraceRecordRequest, TraceRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TraceRecordPubSub_SubscribeClient = grpc.ServerStreamingClient[TraceRecord]

// TraceRecordPubSubServer is the server API for TraceRecordPubSub service.
// All implementations must embed UnimplementedTraceRecordPubSubServer
// for forward compatibility.
type TraceRecordPubSubServer interface {
	// Subscribe the Trace records generated on this service. The service will periodically (e.g. per minute)
	// publishes Trace records to clients via gRPC stream.
	Subscribe(*TraceRecordRequest, grpc.ServerStreamingServer[TraceRecord]) error
	mustEmbedUnimplementedTraceRecordPubSubServer()
}

// UnimplementedTraceRecordPubSubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTraceRecordPubSubServer struct{}

func (UnimplementedTraceRecordPubSubServer) Subscribe(*TraceRecordRequest, grpc.ServerStreamingServer[TraceRecord]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTraceRecordPubSubServer) mustEmbedUnimplementedTraceRecordPubSubServer() {}
func (UnimplementedTraceRecordPubSubServer) testEmbeddedByValue()                           {}

// UnsafeTraceRecordPubSubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceRecordPubSubServer will
// result in compilation errors.
type UnsafeTraceRecordPubSubServer interface {
	mustEmbedUnimplementedTraceRecordPubSubServer()
}

func RegisterTraceRecordPubSubServer(s grpc.ServiceRegistrar, srv TraceRecordPubSubServer) {
	// If the following call panics, it indicates UnimplementedTraceRecordPubSubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TraceRecordPubSub_ServiceDesc, srv)
}

func _TraceRecordPubSub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TraceRecordRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TraceRecordPubSubServer).Subscribe(m, &grpc.GenericServerStream[TraceRecordRequest, TraceRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TraceRecordPubSub_SubscribeServer = grpc.ServerStreamingServer[TraceRecord]

// TraceRecordPubSub_ServiceDesc is the grpc.ServiceDesc for TraceRecordPubSub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TraceRecordPubSub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracepb.TraceRecordPubSub",
	HandlerType: (*TraceRecordPubSubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TraceRecordPubSub_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tracepb.proto",
}
