// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: schedulingpb.proto

package schedulingpb

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scheduling_StoreHeartbeat_FullMethodName  = "/schedulingpb.Scheduling/StoreHeartbeat"
	Scheduling_RegionHeartbeat_FullMethodName = "/schedulingpb.Scheduling/RegionHeartbeat"
	Scheduling_SplitRegions_FullMethodName    = "/schedulingpb.Scheduling/SplitRegions"
	Scheduling_ScatterRegions_FullMethodName  = "/schedulingpb.Scheduling/ScatterRegions"
	Scheduling_GetOperator_FullMethodName     = "/schedulingpb.Scheduling/GetOperator"
	Scheduling_AskBatchSplit_FullMethodName   = "/schedulingpb.Scheduling/AskBatchSplit"
	Scheduling_RegionBuckets_FullMethodName   = "/schedulingpb.Scheduling/RegionBuckets"
)

// SchedulingClient is the client API for Scheduling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingClient interface {
	StoreHeartbeat(ctx context.Context, in *StoreHeartbeatRequest, opts ...grpc.CallOption) (*StoreHeartbeatResponse, error)
	RegionHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegionHeartbeatRequest, RegionHeartbeatResponse], error)
	SplitRegions(ctx context.Context, in *SplitRegionsRequest, opts ...grpc.CallOption) (*SplitRegionsResponse, error)
	ScatterRegions(ctx context.Context, in *ScatterRegionsRequest, opts ...grpc.CallOption) (*ScatterRegionsResponse, error)
	GetOperator(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*GetOperatorResponse, error)
	AskBatchSplit(ctx context.Context, in *AskBatchSplitRequest, opts ...grpc.CallOption) (*AskBatchSplitResponse, error)
	RegionBuckets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegionBucketsRequest, RegionBucketsResponse], error)
}

type schedulingClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingClient(cc grpc.ClientConnInterface) SchedulingClient {
	return &schedulingClient{cc}
}

func (c *schedulingClient) StoreHeartbeat(ctx context.Context, in *StoreHeartbeatRequest, opts ...grpc.CallOption) (*StoreHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreHeartbeatResponse)
	err := c.cc.Invoke(ctx, Scheduling_StoreHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) RegionHeartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegionHeartbeatRequest, RegionHeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scheduling_ServiceDesc.Streams[0], Scheduling_RegionHeartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegionHeartbeatRequest, RegionHeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduling_RegionHeartbeatClient = grpc.BidiStreamingClient[RegionHeartbeatRequest, RegionHeartbeatResponse]

func (c *schedulingClient) SplitRegions(ctx context.Context, in *SplitRegionsRequest, opts ...grpc.CallOption) (*SplitRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplitRegionsResponse)
	err := c.cc.Invoke(ctx, Scheduling_SplitRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) ScatterRegions(ctx context.Context, in *ScatterRegionsRequest, opts ...grpc.CallOption) (*ScatterRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScatterRegionsResponse)
	err := c.cc.Invoke(ctx, Scheduling_ScatterRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) GetOperator(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*GetOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperatorResponse)
	err := c.cc.Invoke(ctx, Scheduling_GetOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) AskBatchSplit(ctx context.Context, in *AskBatchSplitRequest, opts ...grpc.CallOption) (*AskBatchSplitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskBatchSplitResponse)
	err := c.cc.Invoke(ctx, Scheduling_AskBatchSplit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) RegionBuckets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RegionBucketsRequest, RegionBucketsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scheduling_ServiceDesc.Streams[1], Scheduling_RegionBuckets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegionBucketsRequest, RegionBucketsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduling_RegionBucketsClient = grpc.BidiStreamingClient[RegionBucketsRequest, RegionBucketsResponse]

// SchedulingServer is the server API for Scheduling service.
// All implementations must embed UnimplementedSchedulingServer
// for forward compatibility.
type SchedulingServer interface {
	StoreHeartbeat(context.Context, *StoreHeartbeatRequest) (*StoreHeartbeatResponse, error)
	RegionHeartbeat(grpc.BidiStreamingServer[RegionHeartbeatRequest, RegionHeartbeatResponse]) error
	SplitRegions(context.Context, *SplitRegionsRequest) (*SplitRegionsResponse, error)
	ScatterRegions(context.Context, *ScatterRegionsRequest) (*ScatterRegionsResponse, error)
	GetOperator(context.Context, *GetOperatorRequest) (*GetOperatorResponse, error)
	AskBatchSplit(context.Context, *AskBatchSplitRequest) (*AskBatchSplitResponse, error)
	RegionBuckets(grpc.BidiStreamingServer[RegionBucketsRequest, RegionBucketsResponse]) error
	mustEmbedUnimplementedSchedulingServer()
}

// UnimplementedSchedulingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingServer struct{}

func (UnimplementedSchedulingServer) StoreHeartbeat(context.Context, *StoreHeartbeatRequest) (*StoreHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreHeartbeat not implemented")
}
func (UnimplementedSchedulingServer) RegionHeartbeat(grpc.BidiStreamingServer[RegionHeartbeatRequest, RegionHeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method RegionHeartbeat not implemented")
}
func (UnimplementedSchedulingServer) SplitRegions(context.Context, *SplitRegionsRequest) (*SplitRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SplitRegions not implemented")
}
func (UnimplementedSchedulingServer) ScatterRegions(context.Context, *ScatterRegionsRequest) (*ScatterRegionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScatterRegions not implemented")
}
func (UnimplementedSchedulingServer) GetOperator(context.Context, *GetOperatorRequest) (*GetOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperator not implemented")
}
func (UnimplementedSchedulingServer) AskBatchSplit(context.Context, *AskBatchSplitRequest) (*AskBatchSplitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AskBatchSplit not implemented")
}
func (UnimplementedSchedulingServer) RegionBuckets(grpc.BidiStreamingServer[RegionBucketsRequest, RegionBucketsResponse]) error {
	return status.Error(codes.Unimplemented, "method RegionBuckets not implemented")
}
func (UnimplementedSchedulingServer) mustEmbedUnimplementedSchedulingServer() {}
func (UnimplementedSchedulingServer) testEmbeddedByValue()                    {}

// UnsafeSchedulingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServer will
// result in compilation errors.
type UnsafeSchedulingServer interface {
	mustEmbedUnimplementedSchedulingServer()
}

func RegisterSchedulingServer(s grpc.ServiceRegistrar, srv SchedulingServer) {
	// If the following call panics, it indicates UnimplementedSchedulingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scheduling_ServiceDesc, srv)
}

func _Scheduling_StoreHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).StoreHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduling_StoreHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).StoreHeartbeat(ctx, req.(*StoreHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_RegionHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulingServer).RegionHeartbeat(&grpc.GenericServerStream[RegionHeartbeatRequest, RegionHeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduling_RegionHeartbeatServer = grpc.BidiStreamingServer[RegionHeartbeatRequest, RegionHeartbeatResponse]

func _Scheduling_SplitRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).SplitRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduling_SplitRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).SplitRegions(ctx, req.(*SplitRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_ScatterRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScatterRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).ScatterRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduling_ScatterRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).ScatterRegions(ctx, req.(*ScatterRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_GetOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).GetOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduling_GetOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).GetOperator(ctx, req.(*GetOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_AskBatchSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskBatchSplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).AskBatchSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduling_AskBatchSplit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).AskBatchSplit(ctx, req.(*AskBatchSplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_RegionBuckets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulingServer).RegionBuckets(&grpc.GenericServerStream[RegionBucketsRequest, RegionBucketsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduling_RegionBucketsServer = grpc.BidiStreamingServer[RegionBucketsRequest, RegionBucketsResponse]

// Scheduling_ServiceDesc is the grpc.ServiceDesc for Scheduling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedulingpb.Scheduling",
	HandlerType: (*SchedulingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreHeartbeat",
			Handler:    _Scheduling_StoreHeartbeat_Handler,
		},
		{
			MethodName: "SplitRegions",
			Handler:    _Scheduling_SplitRegions_Handler,
		},
		{
			MethodName: "ScatterRegions",
			Handler:    _Scheduling_ScatterRegions_Handler,
		},
		{
			MethodName: "GetOperator",
			Handler:    _Scheduling_GetOperator_Handler,
		},
		{
			MethodName: "AskBatchSplit",
			Handler:    _Scheduling_AskBatchSplit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegionHeartbeat",
			Handler:       _Scheduling_RegionHeartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RegionBuckets",
			Handler:       _Scheduling_RegionBuckets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "schedulingpb.proto",
}
