// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cdcpb.proto

package cdcpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	errorpb "github.com/pingcap/kvproto/pkg/errorpb"
	kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"
	metapb "github.com/pingcap/kvproto/pkg/metapb"
	raft_cmdpb "github.com/pingcap/kvproto/pkg/raft_cmdpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event_LogType int32

const (
	Event_UNKNOWN     Event_LogType = 0
	Event_PREWRITE    Event_LogType = 1
	Event_COMMIT      Event_LogType = 2
	Event_ROLLBACK    Event_LogType = 3
	Event_COMMITTED   Event_LogType = 4
	Event_INITIALIZED Event_LogType = 5
)

// Enum value maps for Event_LogType.
var (
	Event_LogType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PREWRITE",
		2: "COMMIT",
		3: "ROLLBACK",
		4: "COMMITTED",
		5: "INITIALIZED",
	}
	Event_LogType_value = map[string]int32{
		"UNKNOWN":     0,
		"PREWRITE":    1,
		"COMMIT":      2,
		"ROLLBACK":    3,
		"COMMITTED":   4,
		"INITIALIZED": 5,
	}
)

func (x Event_LogType) Enum() *Event_LogType {
	p := new(Event_LogType)
	*p = x
	return p
}

func (x Event_LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_cdcpb_proto_enumTypes[0].Descriptor()
}

func (Event_LogType) Type() protoreflect.EnumType {
	return &file_cdcpb_proto_enumTypes[0]
}

func (x Event_LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_LogType.Descriptor instead.
func (Event_LogType) EnumDescriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8, 0}
}

type Event_Row_OpType int32

const (
	Event_Row_UNKNOWN Event_Row_OpType = 0
	Event_Row_PUT     Event_Row_OpType = 1
	Event_Row_DELETE  Event_Row_OpType = 2
)

// Enum value maps for Event_Row_OpType.
var (
	Event_Row_OpType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PUT",
		2: "DELETE",
	}
	Event_Row_OpType_value = map[string]int32{
		"UNKNOWN": 0,
		"PUT":     1,
		"DELETE":  2,
	}
)

func (x Event_Row_OpType) Enum() *Event_Row_OpType {
	p := new(Event_Row_OpType)
	*p = x
	return p
}

func (x Event_Row_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_Row_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_cdcpb_proto_enumTypes[1].Descriptor()
}

func (Event_Row_OpType) Type() protoreflect.EnumType {
	return &file_cdcpb_proto_enumTypes[1]
}

func (x Event_Row_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_Row_OpType.Descriptor instead.
func (Event_Row_OpType) EnumDescriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8, 0, 0}
}

// KvAPI specifies to capture data written by different KV API.
// See more details in https://github.com/tikv/rfcs/blob/master/text/0069-api-v2.md.
type ChangeDataRequest_KvAPI int32

const (
	ChangeDataRequest_TiDB  ChangeDataRequest_KvAPI = 0
	ChangeDataRequest_RawKV ChangeDataRequest_KvAPI = 1
	ChangeDataRequest_TxnKV ChangeDataRequest_KvAPI = 2
)

// Enum value maps for ChangeDataRequest_KvAPI.
var (
	ChangeDataRequest_KvAPI_name = map[int32]string{
		0: "TiDB",
		1: "RawKV",
		2: "TxnKV",
	}
	ChangeDataRequest_KvAPI_value = map[string]int32{
		"TiDB":  0,
		"RawKV": 1,
		"TxnKV": 2,
	}
)

func (x ChangeDataRequest_KvAPI) Enum() *ChangeDataRequest_KvAPI {
	p := new(ChangeDataRequest_KvAPI)
	*p = x
	return p
}

func (x ChangeDataRequest_KvAPI) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeDataRequest_KvAPI) Descriptor() protoreflect.EnumDescriptor {
	return file_cdcpb_proto_enumTypes[2].Descriptor()
}

func (ChangeDataRequest_KvAPI) Type() protoreflect.EnumType {
	return &file_cdcpb_proto_enumTypes[2]
}

func (x ChangeDataRequest_KvAPI) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeDataRequest_KvAPI.Descriptor instead.
func (ChangeDataRequest_KvAPI) EnumDescriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{11, 0}
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TicdcVersion  string                 `protobuf:"bytes,2,opt,name=ticdc_version,json=ticdcVersion,proto3" json:"ticdc_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_cdcpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *Header) GetTicdcVersion() string {
	if x != nil {
		return x.TicdcVersion
	}
	return ""
}

type DuplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuplicateRequest) Reset() {
	*x = DuplicateRequest{}
	mi := &file_cdcpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuplicateRequest) ProtoMessage() {}

func (x *DuplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuplicateRequest.ProtoReflect.Descriptor instead.
func (*DuplicateRequest) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{1}
}

func (x *DuplicateRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type Compatibility struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequiredVersion string                 `protobuf:"bytes,1,opt,name=required_version,json=requiredVersion,proto3" json:"required_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Compatibility) Reset() {
	*x = Compatibility{}
	mi := &file_cdcpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compatibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compatibility) ProtoMessage() {}

func (x *Compatibility) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compatibility.ProtoReflect.Descriptor instead.
func (*Compatibility) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{2}
}

func (x *Compatibility) GetRequiredVersion() string {
	if x != nil {
		return x.RequiredVersion
	}
	return ""
}

// ClusterIDMismatch is an error variable that
// tells people that the cluster ID of the request does not match the TiKV cluster ID.
type ClusterIDMismatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current tikv cluster ID.
	Current uint64 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	// The cluster ID of the TiCDC request.
	Request       uint64 `protobuf:"varint,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterIDMismatch) Reset() {
	*x = ClusterIDMismatch{}
	mi := &file_cdcpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterIDMismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterIDMismatch) ProtoMessage() {}

func (x *ClusterIDMismatch) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterIDMismatch.ProtoReflect.Descriptor instead.
func (*ClusterIDMismatch) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterIDMismatch) GetCurrent() uint64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ClusterIDMismatch) GetRequest() uint64 {
	if x != nil {
		return x.Request
	}
	return 0
}

// Congested is an error variable that
// tells people that the TiKV-CDC is congested.
type Congested struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The region ID that triggers the congestion.
	RegionId      uint64 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Congested) Reset() {
	*x = Congested{}
	mi := &file_cdcpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Congested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Congested) ProtoMessage() {}

func (x *Congested) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Congested.ProtoReflect.Descriptor instead.
func (*Congested) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{4}
}

func (x *Congested) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type Error struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	NotLeader         *errorpb.NotLeader      `protobuf:"bytes,1,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	RegionNotFound    *errorpb.RegionNotFound `protobuf:"bytes,2,opt,name=region_not_found,json=regionNotFound,proto3" json:"region_not_found,omitempty"`
	EpochNotMatch     *errorpb.EpochNotMatch  `protobuf:"bytes,3,opt,name=epoch_not_match,json=epochNotMatch,proto3" json:"epoch_not_match,omitempty"`
	DuplicateRequest  *DuplicateRequest       `protobuf:"bytes,4,opt,name=duplicate_request,json=duplicateRequest,proto3" json:"duplicate_request,omitempty"`
	Compatibility     *Compatibility          `protobuf:"bytes,5,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	ClusterIdMismatch *ClusterIDMismatch      `protobuf:"bytes,6,opt,name=cluster_id_mismatch,json=clusterIdMismatch,proto3" json:"cluster_id_mismatch,omitempty"`
	ServerIsBusy      *errorpb.ServerIsBusy   `protobuf:"bytes,7,opt,name=server_is_busy,json=serverIsBusy,proto3" json:"server_is_busy,omitempty"`
	Congested         *Congested              `protobuf:"bytes,8,opt,name=congested,proto3" json:"congested,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_cdcpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetNotLeader() *errorpb.NotLeader {
	if x != nil {
		return x.NotLeader
	}
	return nil
}

func (x *Error) GetRegionNotFound() *errorpb.RegionNotFound {
	if x != nil {
		return x.RegionNotFound
	}
	return nil
}

func (x *Error) GetEpochNotMatch() *errorpb.EpochNotMatch {
	if x != nil {
		return x.EpochNotMatch
	}
	return nil
}

func (x *Error) GetDuplicateRequest() *DuplicateRequest {
	if x != nil {
		return x.DuplicateRequest
	}
	return nil
}

func (x *Error) GetCompatibility() *Compatibility {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *Error) GetClusterIdMismatch() *ClusterIDMismatch {
	if x != nil {
		return x.ClusterIdMismatch
	}
	return nil
}

func (x *Error) GetServerIsBusy() *errorpb.ServerIsBusy {
	if x != nil {
		return x.ServerIsBusy
	}
	return nil
}

func (x *Error) GetCongested() *Congested {
	if x != nil {
		return x.Congested
	}
	return nil
}

type TxnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Primary       []byte                 `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnInfo) Reset() {
	*x = TxnInfo{}
	mi := &file_cdcpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnInfo) ProtoMessage() {}

func (x *TxnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnInfo.ProtoReflect.Descriptor instead.
func (*TxnInfo) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{6}
}

func (x *TxnInfo) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnInfo) GetPrimary() []byte {
	if x != nil {
		return x.Primary
	}
	return nil
}

type TxnStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	MinCommitTs   uint64                 `protobuf:"varint,2,opt,name=min_commit_ts,json=minCommitTs,proto3" json:"min_commit_ts,omitempty"`
	CommitTs      uint64                 `protobuf:"varint,3,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	IsRolledBack  bool                   `protobuf:"varint,4,opt,name=is_rolled_back,json=isRolledBack,proto3" json:"is_rolled_back,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnStatus) Reset() {
	*x = TxnStatus{}
	mi := &file_cdcpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnStatus) ProtoMessage() {}

func (x *TxnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnStatus.ProtoReflect.Descriptor instead.
func (*TxnStatus) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{7}
}

func (x *TxnStatus) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *TxnStatus) GetMinCommitTs() uint64 {
	if x != nil {
		return x.MinCommitTs
	}
	return 0
}

func (x *TxnStatus) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

func (x *TxnStatus) GetIsRolledBack() bool {
	if x != nil {
		return x.IsRolledBack
	}
	return false
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RegionId  uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Index     uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	RequestId uint64                 `protobuf:"varint,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_Entries_
	//	*Event_Admin_
	//	*Event_Error
	//	*Event_ResolvedTs
	//	*Event_LongTxn_
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_cdcpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *Event) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Event) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetEntries() *Event_Entries {
	if x != nil {
		if x, ok := x.Event.(*Event_Entries_); ok {
			return x.Entries
		}
	}
	return nil
}

func (x *Event) GetAdmin() *Event_Admin {
	if x != nil {
		if x, ok := x.Event.(*Event_Admin_); ok {
			return x.Admin
		}
	}
	return nil
}

func (x *Event) GetError() *Error {
	if x != nil {
		if x, ok := x.Event.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in cdcpb.proto.
func (x *Event) GetResolvedTs() uint64 {
	if x != nil {
		if x, ok := x.Event.(*Event_ResolvedTs); ok {
			return x.ResolvedTs
		}
	}
	return 0
}

func (x *Event) GetLongTxn() *Event_LongTxn {
	if x != nil {
		if x, ok := x.Event.(*Event_LongTxn_); ok {
			return x.LongTxn
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Entries_ struct {
	Entries *Event_Entries `protobuf:"bytes,3,opt,name=entries,proto3,oneof"`
}

type Event_Admin_ struct {
	Admin *Event_Admin `protobuf:"bytes,4,opt,name=admin,proto3,oneof"`
}

type Event_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type Event_ResolvedTs struct {
	// Deprecated: Marked as deprecated in cdcpb.proto.
	ResolvedTs uint64 `protobuf:"varint,6,opt,name=resolved_ts,json=resolvedTs,proto3,oneof"`
}

type Event_LongTxn_ struct {
	// Note that field 7 is taken by request_id.
	LongTxn *Event_LongTxn `protobuf:"bytes,8,opt,name=long_txn,json=longTxn,proto3,oneof"` // More region level events ...
}

func (*Event_Entries_) isEvent_Event() {}

func (*Event_Admin_) isEvent_Event() {}

func (*Event_Error) isEvent_Event() {}

func (*Event_ResolvedTs) isEvent_Event() {}

func (*Event_LongTxn_) isEvent_Event() {}

// NOTE: events and resolved_ts won't appear simultaneously in one ChangeDataEvent.
type ChangeDataEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	ResolvedTs    *ResolvedTs            `protobuf:"bytes,2,opt,name=resolved_ts,json=resolvedTs,proto3" json:"resolved_ts,omitempty"` // More store level events ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDataEvent) Reset() {
	*x = ChangeDataEvent{}
	mi := &file_cdcpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataEvent) ProtoMessage() {}

func (x *ChangeDataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataEvent.ProtoReflect.Descriptor instead.
func (*ChangeDataEvent) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeDataEvent) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ChangeDataEvent) GetResolvedTs() *ResolvedTs {
	if x != nil {
		return x.ResolvedTs
	}
	return nil
}

type ResolvedTs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []uint64               `protobuf:"varint,1,rep,packed,name=regions,proto3" json:"regions,omitempty"`
	Ts            uint64                 `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	RequestId     uint64                 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedTs) Reset() {
	*x = ResolvedTs{}
	mi := &file_cdcpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedTs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedTs) ProtoMessage() {}

func (x *ResolvedTs) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedTs.ProtoReflect.Descriptor instead.
func (*ResolvedTs) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{10}
}

func (x *ResolvedTs) GetRegions() []uint64 {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *ResolvedTs) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *ResolvedTs) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type ChangeDataRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Header       *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RegionId     uint64                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch  *metapb.RegionEpoch    `protobuf:"bytes,3,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	CheckpointTs uint64                 `protobuf:"varint,4,opt,name=checkpoint_ts,json=checkpointTs,proto3" json:"checkpoint_ts,omitempty"`
	StartKey     []byte                 `protobuf:"bytes,5,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey       []byte                 `protobuf:"bytes,6,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	// Used for CDC to identify events corresponding to different requests.
	// Generally in one call stream, a region can be subscribed multiple
	// times with different `request_id`s.
	RequestId uint64          `protobuf:"varint,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExtraOp   kvrpcpb.ExtraOp `protobuf:"varint,8,opt,name=extra_op,json=extraOp,proto3,enum=kvrpcpb.ExtraOp" json:"extra_op,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*ChangeDataRequest_Register_
	//	*ChangeDataRequest_NotifyTxnStatus_
	//	*ChangeDataRequest_Deregister_
	Request isChangeDataRequest_Request `protobuf_oneof:"request"`
	KvApi   ChangeDataRequest_KvAPI     `protobuf:"varint,11,opt,name=kv_api,json=kvApi,proto3,enum=cdcpb.ChangeDataRequest_KvAPI" json:"kv_api,omitempty"`
	// Whether to filter out the value write by cdc itself.
	FilterLoop    bool `protobuf:"varint,12,opt,name=filter_loop,json=filterLoop,proto3" json:"filter_loop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDataRequest) Reset() {
	*x = ChangeDataRequest{}
	mi := &file_cdcpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataRequest) ProtoMessage() {}

func (x *ChangeDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataRequest.ProtoReflect.Descriptor instead.
func (*ChangeDataRequest) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeDataRequest) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ChangeDataRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *ChangeDataRequest) GetRegionEpoch() *metapb.RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *ChangeDataRequest) GetCheckpointTs() uint64 {
	if x != nil {
		return x.CheckpointTs
	}
	return 0
}

func (x *ChangeDataRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ChangeDataRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ChangeDataRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChangeDataRequest) GetExtraOp() kvrpcpb.ExtraOp {
	if x != nil {
		return x.ExtraOp
	}
	return kvrpcpb.ExtraOp(0)
}

func (x *ChangeDataRequest) GetRequest() isChangeDataRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ChangeDataRequest) GetRegister() *ChangeDataRequest_Register {
	if x != nil {
		if x, ok := x.Request.(*ChangeDataRequest_Register_); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ChangeDataRequest) GetNotifyTxnStatus() *ChangeDataRequest_NotifyTxnStatus {
	if x != nil {
		if x, ok := x.Request.(*ChangeDataRequest_NotifyTxnStatus_); ok {
			return x.NotifyTxnStatus
		}
	}
	return nil
}

func (x *ChangeDataRequest) GetDeregister() *ChangeDataRequest_Deregister {
	if x != nil {
		if x, ok := x.Request.(*ChangeDataRequest_Deregister_); ok {
			return x.Deregister
		}
	}
	return nil
}

func (x *ChangeDataRequest) GetKvApi() ChangeDataRequest_KvAPI {
	if x != nil {
		return x.KvApi
	}
	return ChangeDataRequest_TiDB
}

func (x *ChangeDataRequest) GetFilterLoop() bool {
	if x != nil {
		return x.FilterLoop
	}
	return false
}

type isChangeDataRequest_Request interface {
	isChangeDataRequest_Request()
}

type ChangeDataRequest_Register_ struct {
	// A normal request that trying to register change data feed on a region.
	Register *ChangeDataRequest_Register `protobuf:"bytes,9,opt,name=register,proto3,oneof"`
}

type ChangeDataRequest_NotifyTxnStatus_ struct {
	// Notify the region that some of the running transactions on the region has a pushed
	// min_commit_ts so that the resolved_ts can be advanced.
	NotifyTxnStatus *ChangeDataRequest_NotifyTxnStatus `protobuf:"bytes,10,opt,name=notify_txn_status,json=notifyTxnStatus,proto3,oneof"`
}

type ChangeDataRequest_Deregister_ struct {
	Deregister *ChangeDataRequest_Deregister `protobuf:"bytes,13,opt,name=deregister,proto3,oneof"`
}

func (*ChangeDataRequest_Register_) isChangeDataRequest_Request() {}

func (*ChangeDataRequest_NotifyTxnStatus_) isChangeDataRequest_Request() {}

func (*ChangeDataRequest_Deregister_) isChangeDataRequest_Request() {}

type Event_Row struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StartTs  uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	CommitTs uint64                 `protobuf:"varint,2,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	Type     Event_LogType          `protobuf:"varint,3,opt,name=type,proto3,enum=cdcpb.Event_LogType" json:"type,omitempty"`
	// generation is for pipelined DML protocol. See kvrpcpb.FlushRequest.generation.
	Generation uint64           `protobuf:"varint,10,opt,name=generation,proto3" json:"generation,omitempty"`
	OpType     Event_Row_OpType `protobuf:"varint,4,opt,name=op_type,json=opType,proto3,enum=cdcpb.Event_Row_OpType" json:"op_type,omitempty"`
	Key        []byte           `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Value      []byte           `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	OldValue   []byte           `protobuf:"bytes,7,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	// expire_ts_unix_secs is used for RawKV (see `ChangeDataRequest.KvApi`),
	// and represents the expiration time of this row.
	// Absolute time, seconds since Unix epoch.
	ExpireTsUnixSecs uint64 `protobuf:"varint,8,opt,name=expire_ts_unix_secs,json=expireTsUnixSecs,proto3" json:"expire_ts_unix_secs,omitempty"`
	// The source of this row.
	TxnSource     uint64 `protobuf:"varint,9,opt,name=txn_source,json=txnSource,proto3" json:"txn_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Row) Reset() {
	*x = Event_Row{}
	mi := &file_cdcpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Row) ProtoMessage() {}

func (x *Event_Row) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Row.ProtoReflect.Descriptor instead.
func (*Event_Row) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Event_Row) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *Event_Row) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

func (x *Event_Row) GetType() Event_LogType {
	if x != nil {
		return x.Type
	}
	return Event_UNKNOWN
}

func (x *Event_Row) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Event_Row) GetOpType() Event_Row_OpType {
	if x != nil {
		return x.OpType
	}
	return Event_Row_UNKNOWN
}

func (x *Event_Row) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Event_Row) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Event_Row) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *Event_Row) GetExpireTsUnixSecs() uint64 {
	if x != nil {
		return x.ExpireTsUnixSecs
	}
	return 0
}

func (x *Event_Row) GetTxnSource() uint64 {
	if x != nil {
		return x.TxnSource
	}
	return 0
}

type Event_Entries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Event_Row           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Entries) Reset() {
	*x = Event_Entries{}
	mi := &file_cdcpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Entries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Entries) ProtoMessage() {}

func (x *Event_Entries) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Entries.ProtoReflect.Descriptor instead.
func (*Event_Entries) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Event_Entries) GetEntries() []*Event_Row {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Event_Admin struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AdminRequest  *raft_cmdpb.AdminRequest  `protobuf:"bytes,1,opt,name=admin_request,json=adminRequest,proto3" json:"admin_request,omitempty"`
	AdminResponse *raft_cmdpb.AdminResponse `protobuf:"bytes,2,opt,name=admin_response,json=adminResponse,proto3" json:"admin_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Admin) Reset() {
	*x = Event_Admin{}
	mi := &file_cdcpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Admin) ProtoMessage() {}

func (x *Event_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Admin.ProtoReflect.Descriptor instead.
func (*Event_Admin) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8, 2}
}

func (x *Event_Admin) GetAdminRequest() *raft_cmdpb.AdminRequest {
	if x != nil {
		return x.AdminRequest
	}
	return nil
}

func (x *Event_Admin) GetAdminResponse() *raft_cmdpb.AdminResponse {
	if x != nil {
		return x.AdminResponse
	}
	return nil
}

type Event_LongTxn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnInfo       []*TxnInfo             `protobuf:"bytes,1,rep,name=txn_info,json=txnInfo,proto3" json:"txn_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_LongTxn) Reset() {
	*x = Event_LongTxn{}
	mi := &file_cdcpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_LongTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_LongTxn) ProtoMessage() {}

func (x *Event_LongTxn) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_LongTxn.ProtoReflect.Descriptor instead.
func (*Event_LongTxn) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{8, 3}
}

func (x *Event_LongTxn) GetTxnInfo() []*TxnInfo {
	if x != nil {
		return x.TxnInfo
	}
	return nil
}

type ChangeDataRequest_Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDataRequest_Register) Reset() {
	*x = ChangeDataRequest_Register{}
	mi := &file_cdcpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDataRequest_Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataRequest_Register) ProtoMessage() {}

func (x *ChangeDataRequest_Register) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataRequest_Register.ProtoReflect.Descriptor instead.
func (*ChangeDataRequest_Register) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{11, 0}
}

type ChangeDataRequest_Deregister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDataRequest_Deregister) Reset() {
	*x = ChangeDataRequest_Deregister{}
	mi := &file_cdcpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDataRequest_Deregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataRequest_Deregister) ProtoMessage() {}

func (x *ChangeDataRequest_Deregister) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataRequest_Deregister.ProtoReflect.Descriptor instead.
func (*ChangeDataRequest_Deregister) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{11, 1}
}

type ChangeDataRequest_NotifyTxnStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnStatus     []*TxnStatus           `protobuf:"bytes,1,rep,name=txn_status,json=txnStatus,proto3" json:"txn_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDataRequest_NotifyTxnStatus) Reset() {
	*x = ChangeDataRequest_NotifyTxnStatus{}
	mi := &file_cdcpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDataRequest_NotifyTxnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDataRequest_NotifyTxnStatus) ProtoMessage() {}

func (x *ChangeDataRequest_NotifyTxnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cdcpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDataRequest_NotifyTxnStatus.ProtoReflect.Descriptor instead.
func (*ChangeDataRequest_NotifyTxnStatus) Descriptor() ([]byte, []int) {
	return file_cdcpb_proto_rawDescGZIP(), []int{11, 2}
}

func (x *ChangeDataRequest_NotifyTxnStatus) GetTxnStatus() []*TxnStatus {
	if x != nil {
		return x.TxnStatus
	}
	return nil
}

var File_cdcpb_proto protoreflect.FileDescriptor

const file_cdcpb_proto_rawDesc = "" +
	"\n" +
	"\vcdcpb.proto\x12\x05cdcpb\x1a\x10raft_cmdpb.proto\x1a\fmetapb.proto\x1a\rerrorpb.proto\x1a\rkvrpcpb.proto\x1a\x0frustproto.proto\"L\n" +
	"\x06Header\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12#\n" +
	"\rticdc_version\x18\x02 \x01(\tR\fticdcVersion\"/\n" +
	"\x10DuplicateRequest\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\":\n" +
	"\rCompatibility\x12)\n" +
	"\x10required_version\x18\x01 \x01(\tR\x0frequiredVersion\"G\n" +
	"\x11ClusterIDMismatch\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x04R\acurrent\x12\x18\n" +
	"\arequest\x18\x02 \x01(\x04R\arequest\"(\n" +
	"\tCongested\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"\xf6\x03\n" +
	"\x05Error\x121\n" +
	"\n" +
	"not_leader\x18\x01 \x01(\v2\x12.errorpb.NotLeaderR\tnotLeader\x12A\n" +
	"\x10region_not_found\x18\x02 \x01(\v2\x17.errorpb.RegionNotFoundR\x0eregionNotFound\x12>\n" +
	"\x0fepoch_not_match\x18\x03 \x01(\v2\x16.errorpb.EpochNotMatchR\repochNotMatch\x12D\n" +
	"\x11duplicate_request\x18\x04 \x01(\v2\x17.cdcpb.DuplicateRequestR\x10duplicateRequest\x12:\n" +
	"\rcompatibility\x18\x05 \x01(\v2\x14.cdcpb.CompatibilityR\rcompatibility\x12H\n" +
	"\x13cluster_id_mismatch\x18\x06 \x01(\v2\x18.cdcpb.ClusterIDMismatchR\x11clusterIdMismatch\x12;\n" +
	"\x0eserver_is_busy\x18\a \x01(\v2\x15.errorpb.ServerIsBusyR\fserverIsBusy\x12.\n" +
	"\tcongested\x18\b \x01(\v2\x10.cdcpb.CongestedR\tcongested\">\n" +
	"\aTxnInfo\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\fR\aprimary\"\x8d\x01\n" +
	"\tTxnStatus\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\"\n" +
	"\rmin_commit_ts\x18\x02 \x01(\x04R\vminCommitTs\x12\x1b\n" +
	"\tcommit_ts\x18\x03 \x01(\x04R\bcommitTs\x12$\n" +
	"\x0eis_rolled_back\x18\x04 \x01(\bR\fisRolledBack\"\x93\b\n" +
	"\x05Event\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\x04R\trequestId\x120\n" +
	"\aentries\x18\x03 \x01(\v2\x14.cdcpb.Event.EntriesH\x00R\aentries\x12*\n" +
	"\x05admin\x18\x04 \x01(\v2\x12.cdcpb.Event.AdminH\x00R\x05admin\x12$\n" +
	"\x05error\x18\x05 \x01(\v2\f.cdcpb.ErrorH\x00R\x05error\x12%\n" +
	"\vresolved_ts\x18\x06 \x01(\x04B\x02\x18\x01H\x00R\n" +
	"resolvedTs\x121\n" +
	"\blong_txn\x18\b \x01(\v2\x14.cdcpb.Event.LongTxnH\x00R\alongTxn\x1a\xf8\x02\n" +
	"\x03Row\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x1b\n" +
	"\tcommit_ts\x18\x02 \x01(\x04R\bcommitTs\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.cdcpb.Event.LogTypeR\x04type\x12\x1e\n" +
	"\n" +
	"generation\x18\n" +
	" \x01(\x04R\n" +
	"generation\x120\n" +
	"\aop_type\x18\x04 \x01(\x0e2\x17.cdcpb.Event.Row.OpTypeR\x06opType\x12\x10\n" +
	"\x03key\x18\x05 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12\x1b\n" +
	"\told_value\x18\a \x01(\fR\boldValue\x12-\n" +
	"\x13expire_ts_unix_secs\x18\b \x01(\x04R\x10expireTsUnixSecs\x12\x1d\n" +
	"\n" +
	"txn_source\x18\t \x01(\x04R\ttxnSource\"*\n" +
	"\x06OpType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x1a5\n" +
	"\aEntries\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.cdcpb.Event.RowR\aentries\x1a\x88\x01\n" +
	"\x05Admin\x12=\n" +
	"\radmin_request\x18\x01 \x01(\v2\x18.raft_cmdpb.AdminRequestR\fadminRequest\x12@\n" +
	"\x0eadmin_response\x18\x02 \x01(\v2\x19.raft_cmdpb.AdminResponseR\radminResponse\x1a4\n" +
	"\aLongTxn\x12)\n" +
	"\btxn_info\x18\x01 \x03(\v2\x0e.cdcpb.TxnInfoR\atxnInfo\"^\n" +
	"\aLogType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bPREWRITE\x10\x01\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x02\x12\f\n" +
	"\bROLLBACK\x10\x03\x12\r\n" +
	"\tCOMMITTED\x10\x04\x12\x0f\n" +
	"\vINITIALIZED\x10\x05B\a\n" +
	"\x05event\"k\n" +
	"\x0fChangeDataEvent\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.cdcpb.EventR\x06events\x122\n" +
	"\vresolved_ts\x18\x02 \x01(\v2\x11.cdcpb.ResolvedTsR\n" +
	"resolvedTs\"U\n" +
	"\n" +
	"ResolvedTs\x12\x18\n" +
	"\aregions\x18\x01 \x03(\x04R\aregions\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x04R\x02ts\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId\"\x80\x06\n" +
	"\x11ChangeDataRequest\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.cdcpb.HeaderR\x06header\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x04R\bregionId\x126\n" +
	"\fregion_epoch\x18\x03 \x01(\v2\x13.metapb.RegionEpochR\vregionEpoch\x12#\n" +
	"\rcheckpoint_ts\x18\x04 \x01(\x04R\fcheckpointTs\x12\x1b\n" +
	"\tstart_key\x18\x05 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x06 \x01(\fR\x06endKey\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\x04R\trequestId\x12+\n" +
	"\bextra_op\x18\b \x01(\x0e2\x10.kvrpcpb.ExtraOpR\aextraOp\x12?\n" +
	"\bregister\x18\t \x01(\v2!.cdcpb.ChangeDataRequest.RegisterH\x00R\bregister\x12V\n" +
	"\x11notify_txn_status\x18\n" +
	" \x01(\v2(.cdcpb.ChangeDataRequest.NotifyTxnStatusH\x00R\x0fnotifyTxnStatus\x12E\n" +
	"\n" +
	"deregister\x18\r \x01(\v2#.cdcpb.ChangeDataRequest.DeregisterH\x00R\n" +
	"deregister\x125\n" +
	"\x06kv_api\x18\v \x01(\x0e2\x1e.cdcpb.ChangeDataRequest.KvAPIR\x05kvApi\x12\x1f\n" +
	"\vfilter_loop\x18\f \x01(\bR\n" +
	"filterLoop\x1a\n" +
	"\n" +
	"\bRegister\x1a\f\n" +
	"\n" +
	"Deregister\x1aB\n" +
	"\x0fNotifyTxnStatus\x12/\n" +
	"\n" +
	"txn_status\x18\x01 \x03(\v2\x10.cdcpb.TxnStatusR\ttxnStatus\"'\n" +
	"\x05KvAPI\x12\b\n" +
	"\x04TiDB\x10\x00\x12\t\n" +
	"\x05RawKV\x10\x01\x12\t\n" +
	"\x05TxnKV\x10\x02B\t\n" +
	"\arequest2\x94\x01\n" +
	"\n" +
	"ChangeData\x12A\n" +
	"\tEventFeed\x12\x18.cdcpb.ChangeDataRequest\x1a\x16.cdcpb.ChangeDataEvent(\x010\x01\x12C\n" +
	"\vEventFeedV2\x12\x18.cdcpb.ChangeDataRequest\x1a\x16.cdcpb.ChangeDataEvent(\x010\x01B\x16ب\b\x01\n" +
	"\x10org.tikv.kvprotob\x06proto3"

var (
	file_cdcpb_proto_rawDescOnce sync.Once
	file_cdcpb_proto_rawDescData []byte
)

func file_cdcpb_proto_rawDescGZIP() []byte {
	file_cdcpb_proto_rawDescOnce.Do(func() {
		file_cdcpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdcpb_proto_rawDesc), len(file_cdcpb_proto_rawDesc)))
	})
	return file_cdcpb_proto_rawDescData
}

var file_cdcpb_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cdcpb_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cdcpb_proto_goTypes = []any{
	(Event_LogType)(0),                        // 0: cdcpb.Event.LogType
	(Event_Row_OpType)(0),                     // 1: cdcpb.Event.Row.OpType
	(ChangeDataRequest_KvAPI)(0),              // 2: cdcpb.ChangeDataRequest.KvAPI
	(*Header)(nil),                            // 3: cdcpb.Header
	(*DuplicateRequest)(nil),                  // 4: cdcpb.DuplicateRequest
	(*Compatibility)(nil),                     // 5: cdcpb.Compatibility
	(*ClusterIDMismatch)(nil),                 // 6: cdcpb.ClusterIDMismatch
	(*Congested)(nil),                         // 7: cdcpb.Congested
	(*Error)(nil),                             // 8: cdcpb.Error
	(*TxnInfo)(nil),                           // 9: cdcpb.TxnInfo
	(*TxnStatus)(nil),                         // 10: cdcpb.TxnStatus
	(*Event)(nil),                             // 11: cdcpb.Event
	(*ChangeDataEvent)(nil),                   // 12: cdcpb.ChangeDataEvent
	(*ResolvedTs)(nil),                        // 13: cdcpb.ResolvedTs
	(*ChangeDataRequest)(nil),                 // 14: cdcpb.ChangeDataRequest
	(*Event_Row)(nil),                         // 15: cdcpb.Event.Row
	(*Event_Entries)(nil),                     // 16: cdcpb.Event.Entries
	(*Event_Admin)(nil),                       // 17: cdcpb.Event.Admin
	(*Event_LongTxn)(nil),                     // 18: cdcpb.Event.LongTxn
	(*ChangeDataRequest_Register)(nil),        // 19: cdcpb.ChangeDataRequest.Register
	(*ChangeDataRequest_Deregister)(nil),      // 20: cdcpb.ChangeDataRequest.Deregister
	(*ChangeDataRequest_NotifyTxnStatus)(nil), // 21: cdcpb.ChangeDataRequest.NotifyTxnStatus
	(*errorpb.NotLeader)(nil),                 // 22: errorpb.NotLeader
	(*errorpb.RegionNotFound)(nil),            // 23: errorpb.RegionNotFound
	(*errorpb.EpochNotMatch)(nil),             // 24: errorpb.EpochNotMatch
	(*errorpb.ServerIsBusy)(nil),              // 25: errorpb.ServerIsBusy
	(*metapb.RegionEpoch)(nil),                // 26: metapb.RegionEpoch
	(kvrpcpb.ExtraOp)(0),                      // 27: kvrpcpb.ExtraOp
	(*raft_cmdpb.AdminRequest)(nil),           // 28: raft_cmdpb.AdminRequest
	(*raft_cmdpb.AdminResponse)(nil),          // 29: raft_cmdpb.AdminResponse
}
var file_cdcpb_proto_depIdxs = []int32{
	22, // 0: cdcpb.Error.not_leader:type_name -> errorpb.NotLeader
	23, // 1: cdcpb.Error.region_not_found:type_name -> errorpb.RegionNotFound
	24, // 2: cdcpb.Error.epoch_not_match:type_name -> errorpb.EpochNotMatch
	4,  // 3: cdcpb.Error.duplicate_request:type_name -> cdcpb.DuplicateRequest
	5,  // 4: cdcpb.Error.compatibility:type_name -> cdcpb.Compatibility
	6,  // 5: cdcpb.Error.cluster_id_mismatch:type_name -> cdcpb.ClusterIDMismatch
	25, // 6: cdcpb.Error.server_is_busy:type_name -> errorpb.ServerIsBusy
	7,  // 7: cdcpb.Error.congested:type_name -> cdcpb.Congested
	16, // 8: cdcpb.Event.entries:type_name -> cdcpb.Event.Entries
	17, // 9: cdcpb.Event.admin:type_name -> cdcpb.Event.Admin
	8,  // 10: cdcpb.Event.error:type_name -> cdcpb.Error
	18, // 11: cdcpb.Event.long_txn:type_name -> cdcpb.Event.LongTxn
	11, // 12: cdcpb.ChangeDataEvent.events:type_name -> cdcpb.Event
	13, // 13: cdcpb.ChangeDataEvent.resolved_ts:type_name -> cdcpb.ResolvedTs
	3,  // 14: cdcpb.ChangeDataRequest.header:type_name -> cdcpb.Header
	26, // 15: cdcpb.ChangeDataRequest.region_epoch:type_name -> metapb.RegionEpoch
	27, // 16: cdcpb.ChangeDataRequest.extra_op:type_name -> kvrpcpb.ExtraOp
	19, // 17: cdcpb.ChangeDataRequest.register:type_name -> cdcpb.ChangeDataRequest.Register
	21, // 18: cdcpb.ChangeDataRequest.notify_txn_status:type_name -> cdcpb.ChangeDataRequest.NotifyTxnStatus
	20, // 19: cdcpb.ChangeDataRequest.deregister:type_name -> cdcpb.ChangeDataRequest.Deregister
	2,  // 20: cdcpb.ChangeDataRequest.kv_api:type_name -> cdcpb.ChangeDataRequest.KvAPI
	0,  // 21: cdcpb.Event.Row.type:type_name -> cdcpb.Event.LogType
	1,  // 22: cdcpb.Event.Row.op_type:type_name -> cdcpb.Event.Row.OpType
	15, // 23: cdcpb.Event.Entries.entries:type_name -> cdcpb.Event.Row
	28, // 24: cdcpb.Event.Admin.admin_request:type_name -> raft_cmdpb.AdminRequest
	29, // 25: cdcpb.Event.Admin.admin_response:type_name -> raft_cmdpb.AdminResponse
	9,  // 26: cdcpb.Event.LongTxn.txn_info:type_name -> cdcpb.TxnInfo
	10, // 27: cdcpb.ChangeDataRequest.NotifyTxnStatus.txn_status:type_name -> cdcpb.TxnStatus
	14, // 28: cdcpb.ChangeData.EventFeed:input_type -> cdcpb.ChangeDataRequest
	14, // 29: cdcpb.ChangeData.EventFeedV2:input_type -> cdcpb.ChangeDataRequest
	12, // 30: cdcpb.ChangeData.EventFeed:output_type -> cdcpb.ChangeDataEvent
	12, // 31: cdcpb.ChangeData.EventFeedV2:output_type -> cdcpb.ChangeDataEvent
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_cdcpb_proto_init() }
func file_cdcpb_proto_init() {
	if File_cdcpb_proto != nil {
		return
	}
	file_cdcpb_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_Entries_)(nil),
		(*Event_Admin_)(nil),
		(*Event_Error)(nil),
		(*Event_ResolvedTs)(nil),
		(*Event_LongTxn_)(nil),
	}
	file_cdcpb_proto_msgTypes[11].OneofWrappers = []any{
		(*ChangeDataRequest_Register_)(nil),
		(*ChangeDataRequest_NotifyTxnStatus_)(nil),
		(*ChangeDataRequest_Deregister_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdcpb_proto_rawDesc), len(file_cdcpb_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cdcpb_proto_goTypes,
		DependencyIndexes: file_cdcpb_proto_depIdxs,
		EnumInfos:         file_cdcpb_proto_enumTypes,
		MessageInfos:      file_cdcpb_proto_msgTypes,
	}.Build()
	File_cdcpb_proto = out.File
	file_cdcpb_proto_goTypes = nil
	file_cdcpb_proto_depIdxs = nil
}
