// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: logbackuppb.proto

package logbackuppb

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogBackup_GetLastFlushTSOfRegion_FullMethodName = "/logbackup.LogBackup/GetLastFlushTSOfRegion"
	LogBackup_SubscribeFlushEvent_FullMethodName    = "/logbackup.LogBackup/SubscribeFlushEvent"
	LogBackup_FlushNow_FullMethodName               = "/logbackup.LogBackup/FlushNow"
)

// LogBackupClient is the client API for LogBackup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The log backup service.
// Generally, most essential interfaces of log backup (say, checkpoint management, task management) are
// provided by adding some key in the embed etcd of PD.
// This interface is mainly provided for the checkpoint advancer and debug usage.
type LogBackupClient interface {
	GetLastFlushTSOfRegion(ctx context.Context, in *GetLastFlushTSOfRegionRequest, opts ...grpc.CallOption) (*GetLastFlushTSOfRegionResponse, error)
	SubscribeFlushEvent(ctx context.Context, in *SubscribeFlushEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeFlushEventResponse], error)
	FlushNow(ctx context.Context, in *FlushNowRequest, opts ...grpc.CallOption) (*FlushNowResponse, error)
}

type logBackupClient struct {
	cc grpc.ClientConnInterface
}

func NewLogBackupClient(cc grpc.ClientConnInterface) LogBackupClient {
	return &logBackupClient{cc}
}

func (c *logBackupClient) GetLastFlushTSOfRegion(ctx context.Context, in *GetLastFlushTSOfRegionRequest, opts ...grpc.CallOption) (*GetLastFlushTSOfRegionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastFlushTSOfRegionResponse)
	err := c.cc.Invoke(ctx, LogBackup_GetLastFlushTSOfRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logBackupClient) SubscribeFlushEvent(ctx context.Context, in *SubscribeFlushEventRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeFlushEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogBackup_ServiceDesc.Streams[0], LogBackup_SubscribeFlushEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeFlushEventRequest, SubscribeFlushEventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogBackup_SubscribeFlushEventClient = grpc.ServerStreamingClient[SubscribeFlushEventResponse]

func (c *logBackupClient) FlushNow(ctx context.Context, in *FlushNowRequest, opts ...grpc.CallOption) (*FlushNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushNowResponse)
	err := c.cc.Invoke(ctx, LogBackup_FlushNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogBackupServer is the server API for LogBackup service.
// All implementations must embed UnimplementedLogBackupServer
// for forward compatibility.
//
// The log backup service.
// Generally, most essential interfaces of log backup (say, checkpoint management, task management) are
// provided by adding some key in the embed etcd of PD.
// This interface is mainly provided for the checkpoint advancer and debug usage.
type LogBackupServer interface {
	GetLastFlushTSOfRegion(context.Context, *GetLastFlushTSOfRegionRequest) (*GetLastFlushTSOfRegionResponse, error)
	SubscribeFlushEvent(*SubscribeFlushEventRequest, grpc.ServerStreamingServer[SubscribeFlushEventResponse]) error
	FlushNow(context.Context, *FlushNowRequest) (*FlushNowResponse, error)
	mustEmbedUnimplementedLogBackupServer()
}

// UnimplementedLogBackupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogBackupServer struct{}

func (UnimplementedLogBackupServer) GetLastFlushTSOfRegion(context.Context, *GetLastFlushTSOfRegionRequest) (*GetLastFlushTSOfRegionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastFlushTSOfRegion not implemented")
}
func (UnimplementedLogBackupServer) SubscribeFlushEvent(*SubscribeFlushEventRequest, grpc.ServerStreamingServer[SubscribeFlushEventResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeFlushEvent not implemented")
}
func (UnimplementedLogBackupServer) FlushNow(context.Context, *FlushNowRequest) (*FlushNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushNow not implemented")
}
func (UnimplementedLogBackupServer) mustEmbedUnimplementedLogBackupServer() {}
func (UnimplementedLogBackupServer) testEmbeddedByValue()                   {}

// UnsafeLogBackupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogBackupServer will
// result in compilation errors.
type UnsafeLogBackupServer interface {
	mustEmbedUnimplementedLogBackupServer()
}

func RegisterLogBackupServer(s grpc.ServiceRegistrar, srv LogBackupServer) {
	// If the following call panics, it indicates UnimplementedLogBackupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogBackup_ServiceDesc, srv)
}

func _LogBackup_GetLastFlushTSOfRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastFlushTSOfRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogBackupServer).GetLastFlushTSOfRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogBackup_GetLastFlushTSOfRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogBackupServer).GetLastFlushTSOfRegion(ctx, req.(*GetLastFlushTSOfRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogBackup_SubscribeFlushEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeFlushEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogBackupServer).SubscribeFlushEvent(m, &grpc.GenericServerStream[SubscribeFlushEventRequest, SubscribeFlushEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogBackup_SubscribeFlushEventServer = grpc.ServerStreamingServer[SubscribeFlushEventResponse]

func _LogBackup_FlushNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogBackupServer).FlushNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogBackup_FlushNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogBackupServer).FlushNow(ctx, req.(*FlushNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogBackup_ServiceDesc is the grpc.ServiceDesc for LogBackup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogBackup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logbackup.LogBackup",
	HandlerType: (*LogBackupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastFlushTSOfRegion",
			Handler:    _LogBackup_GetLastFlushTSOfRegion_Handler,
		},
		{
			MethodName: "FlushNow",
			Handler:    _LogBackup_FlushNow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeFlushEvent",
			Handler:       _LogBackup_SubscribeFlushEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "logbackuppb.proto",
}
